import {readProviderState,type AIProviderProfile} from "./ai-provider-catalog";
import {buildCapabilityRegistry,capabilityDocumentText,chunkCapability,registryVersion,searchCapabilities,stableHash,type CapabilityDocument,type CapabilityHit} from "./capability-rag";
import {authenticatedOwnerKey,getUserDatabase,readUserSnapshot} from "./user-snapshot";

type IndexEventType="capability.created"|"capability.updated"|"capability.deleted"|"capability.enabled"|"capability.disabled"|"module.created"|"tool.created"|"provider.updated"|"data_source.updated"|"workspace_template.updated"|"api_route.updated";
type StoredCapabilityRow={capability_id:string;document_json:string;content_hash:string;version:string;indexed_at:string};
type IndexEventRow={event_id:string;event_type:IndexEventType;capability_id:string|null;status:"pending"|"completed"|"failed"|"retrying";error_message:string|null;retry_count:number;created_at:string;completed_at:string|null};

async function ensureTables(){const db=await getUserDatabase();await db.prepare(`CREATE TABLE IF NOT EXISTS capability_index_documents (
  capability_id TEXT PRIMARY KEY NOT NULL, document_json TEXT NOT NULL, chunks_json TEXT NOT NULL,
  content_hash TEXT NOT NULL, version TEXT NOT NULL, indexed_at TEXT NOT NULL
)`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS capability_index_events (
  event_id TEXT PRIMARY KEY NOT NULL, event_type TEXT NOT NULL, capability_id TEXT,
  status TEXT NOT NULL, error_message TEXT, retry_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL, completed_at TEXT
)`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS capability_index_state (
  index_id TEXT PRIMARY KEY NOT NULL, current_version TEXT NOT NULL, indexed_count INTEGER NOT NULL,
  pending_count INTEGER NOT NULL, failed_count INTEGER NOT NULL, last_success_at TEXT,
  updated_at TEXT NOT NULL
)`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS user_context_index (
  owner_key TEXT NOT NULL, document_id TEXT NOT NULL, document_type TEXT NOT NULL,
  payload_json TEXT NOT NULL, chunks_json TEXT NOT NULL, content_hash TEXT NOT NULL,
  updated_at TEXT NOT NULL, PRIMARY KEY(owner_key,document_id)
)`).run();return db;}

const parse=<T,>(value:string,fallback:T):T=>{try{return JSON.parse(value) as T}catch{return fallback}};
const eventFor=(next:CapabilityDocument,previous?:CapabilityDocument):IndexEventType=>{if(next.capability_id.startsWith("workspace_template_")&&previous)return "workspace_template.updated";if(!previous)return next.category==="module"?"module.created":next.category==="tool"?"tool.created":"capability.created";if(previous.status!==next.status){if(next.status==="disabled"||next.status==="unavailable")return "capability.disabled";if(next.status==="available")return "capability.enabled";}if(next.category==="provider")return "provider.updated";if(next.category==="data_source")return "data_source.updated";if(next.category==="api")return "api_route.updated";return "capability.updated";};
async function recordEvent(db:D1Database,eventType:IndexEventType,capabilityId:string|null,status:IndexEventRow["status"],error:string|null=null,retryCount=0){const now=new Date().toISOString();await db.prepare("INSERT INTO capability_index_events (event_id,event_type,capability_id,status,error_message,retry_count,created_at,completed_at) VALUES (?,?,?,?,?,?,?,?)").bind(`cap_evt_${crypto.randomUUID()}`,eventType,capabilityId,status,error,retryCount,now,status==="completed"?now:null).run();}

export async function syncPlatformCapabilityIndex(providers?:AIProviderProfile[],options:{force?:boolean;capabilityId?:string}={}){
  const db=await ensureTables();const activeProviders=providers??(await readProviderState()).providers;const platformProviders=activeProviders.filter(item=>!item.editable);let registry=buildCapabilityRegistry(platformProviders);if(options.capabilityId)registry=registry.filter(item=>item.capability_id===options.capabilityId);
  const rows=await db.prepare("SELECT capability_id,document_json,content_hash,version,indexed_at FROM capability_index_documents").all() as {results?:StoredCapabilityRow[]};const previous=new Map((rows.results??[]).map(row=>[row.capability_id,row]));const activeIds=new Set(buildCapabilityRegistry(platformProviders).map(item=>item.capability_id));let changed=0,failed=0;
  for(const item of registry){const old=previous.get(item.capability_id);const content=capabilityDocumentText(item);const contentHash=stableHash(content);if(!options.force&&old?.content_hash===contentHash)continue;const eventType=eventFor(item,old?parse<CapabilityDocument>(old.document_json,item):undefined);try{const indexedAt=new Date().toISOString();const chunks=chunkCapability(item,indexedAt);await db.prepare(`INSERT INTO capability_index_documents (capability_id,document_json,chunks_json,content_hash,version,indexed_at) VALUES (?,?,?,?,?,?)
      ON CONFLICT(capability_id) DO UPDATE SET document_json=excluded.document_json,chunks_json=excluded.chunks_json,content_hash=excluded.content_hash,version=excluded.version,indexed_at=excluded.indexed_at`).bind(item.capability_id,JSON.stringify(item),JSON.stringify(chunks),contentHash,item.version,indexedAt).run();await recordEvent(db,eventType,item.capability_id,"completed");changed+=1;}catch(error){failed+=1;await recordEvent(db,eventType,item.capability_id,"failed",error instanceof Error?error.message:"索引失败");}
  }
  if(!options.capabilityId){for(const [id] of previous){if(activeIds.has(id))continue;try{await db.prepare("DELETE FROM capability_index_documents WHERE capability_id=?").bind(id).run();await recordEvent(db,"capability.deleted",id,"completed");changed+=1;}catch(error){failed+=1;await recordEvent(db,"capability.deleted",id,"failed",error instanceof Error?error.message:"删除旧索引失败");}}}
  const all=await db.prepare("SELECT capability_id,document_json,content_hash,version,indexed_at FROM capability_index_documents").all() as {results?:StoredCapabilityRow[]};const allDocs=(all.results??[]).map(row=>parse<CapabilityDocument|null>(row.document_json,null)).filter((item):item is CapabilityDocument=>Boolean(item));const currentVersion=registryVersion(buildCapabilityRegistry(platformProviders));const now=new Date().toISOString();const failures=await db.prepare("SELECT COUNT(*) AS count FROM capability_index_events WHERE status='failed'").all() as {results?:Array<{count:number}>};const failedCount=Number(failures.results?.[0]?.count??0);await db.prepare(`INSERT INTO capability_index_state (index_id,current_version,indexed_count,pending_count,failed_count,last_success_at,updated_at) VALUES ('platform',?,?,?,?,?,?)
    ON CONFLICT(index_id) DO UPDATE SET current_version=excluded.current_version,indexed_count=excluded.indexed_count,pending_count=excluded.pending_count,failed_count=excluded.failed_count,last_success_at=excluded.last_success_at,updated_at=excluded.updated_at`).bind(currentVersion,allDocs.length,0,failedCount,failed?null:now,now).run();return {status:failed?"degraded":"healthy",indexed_count:allDocs.length,changed_count:changed,pending_count:0,failed_count:failedCount,last_success_at:failed?null:now,current_version:currentVersion,stale_documents:[],documents:allDocs};
}
export function summarizeCapabilityIndex(result:Awaited<ReturnType<typeof syncPlatformCapabilityIndex>>){return {status:result.status,indexed_count:result.indexed_count,changed_count:result.changed_count,pending_count:result.pending_count,failed_count:result.failed_count,last_success_at:result.last_success_at,current_version:result.current_version,stale_documents:result.stale_documents};}

function privateDocuments(snapshot:Record<string,unknown>){const documents:Array<{id:string;type:string;payload:unknown}>=[];const add=(key:string,type:string)=>{if(snapshot[key]!==undefined)documents.push({id:`user_${type}_${key}`,type,payload:snapshot[key]});};add("workspaces","workspace");add("quantStrategies","strategy");add("naturalLanguageStrategies","strategy");add("holdings","portfolio");add("watched","watchlist");add("quantSchedules","reminder");add("exploratoryPreferences","preference");add("aiDefaultProviderId","provider_preference");add("aiTaskRouting","provider_preference");return documents;}
export async function syncUserContextIndex(){const owner=await authenticatedOwnerKey();if(!owner)return {status:"unauthorized" as const,indexed_count:0};const state=await readUserSnapshot();const snapshot=(state.status==="ready"?state.snapshot:{}) as Record<string,unknown>;const db=await ensureTables();const docs=privateDocuments(snapshot);const ids=new Set(docs.map(item=>item.id));const existing=await db.prepare("SELECT document_id FROM user_context_index WHERE owner_key=?").bind(owner).all() as {results?:Array<{document_id:string}>};for(const doc of docs){const text=JSON.stringify(doc.payload);const hash=stableHash(text);const chunks=[{chunk_id:`${doc.id}:private`,section:doc.type,content:text.slice(0,12000),content_hash:hash,indexed_at:new Date().toISOString()}];await db.prepare(`INSERT INTO user_context_index (owner_key,document_id,document_type,payload_json,chunks_json,content_hash,updated_at) VALUES (?,?,?,?,?,?,?)
      ON CONFLICT(owner_key,document_id) DO UPDATE SET document_type=excluded.document_type,payload_json=excluded.payload_json,chunks_json=excluded.chunks_json,content_hash=excluded.content_hash,updated_at=excluded.updated_at`).bind(owner,doc.id,doc.type,text,JSON.stringify(chunks),hash,new Date().toISOString()).run();}for(const row of existing.results??[])if(!ids.has(row.document_id))await db.prepare("DELETE FROM user_context_index WHERE owner_key=? AND document_id=?").bind(owner,row.document_id).run();return {status:"healthy" as const,indexed_count:docs.length,owner_scope:"isolated" as const};}

export async function searchPlatformCapabilityIndex(query:string,options:{route?:string;limit?:number}={}):Promise<{hits:CapabilityHit[];index:ReturnType<typeof summarizeCapabilityIndex>;runtime:Record<string,unknown>}>{const providers=(await readProviderState()).providers;const synced=await syncPlatformCapabilityIndex(providers);const user=await syncUserContextIndex();const hits=searchCapabilities(query,synced.documents,options);const selected=providers.find(item=>item.isDefault);const snapshot=await readUserSnapshot();const state=(snapshot.status==="ready"?snapshot.snapshot:{}) as {activeWorkspaceId?:unknown;workspaces?:Array<{id?:string;name?:string}>};const workspace=state.workspaces?.find(item=>item.id===state.activeWorkspaceId)??state.workspaces?.[0]??null;const index=summarizeCapabilityIndex(synced);return {hits,index,runtime:{service_status:index.status,current_provider:selected?{name:selected.displayName,status:selected.connectionStatus,model:selected.model}:null,current_workspace:workspace?{id:workspace.id,name:workspace.name}:null,user_permissions:{authenticated:snapshot.status!=="unauthorized",private_context:user.status==="healthy",automatic_trade:false},checked_at:new Date().toISOString()}};}

export async function capabilityIndexStatus(){const providers=(await readProviderState()).providers;return summarizeCapabilityIndex(await syncPlatformCapabilityIndex(providers));}
export async function rebuildCapabilityIndex(){const db=await ensureTables();await db.prepare("DELETE FROM capability_index_documents").run();return syncPlatformCapabilityIndex(undefined,{force:true});}
export async function reindexCapability(capabilityId:string){const providers=(await readProviderState()).providers.filter(item=>!item.editable);const exists=buildCapabilityRegistry(providers).some(item=>item.capability_id===capabilityId);if(!exists)throw new Error("公共 Capability Registry 中不存在该能力");return syncPlatformCapabilityIndex(providers,{force:true,capabilityId});}
export async function capabilityIndexFailures(){const db=await ensureTables();const rows=await db.prepare("SELECT event_id,event_type,capability_id,status,error_message,retry_count,created_at,completed_at FROM capability_index_events WHERE status='failed' ORDER BY created_at DESC LIMIT 100").all() as {results?:IndexEventRow[]};return {items:rows.results??[],failed_count:rows.results?.length??0};}
export async function retryCapabilityIndexFailures(){const db=await ensureTables();const failures=await capabilityIndexFailures();let completed=0,failed=0;for(const event of failures.items){await db.prepare("UPDATE capability_index_events SET status='retrying',retry_count=retry_count+1,error_message=NULL WHERE event_id=?").bind(event.event_id).run();try{if(event.capability_id)await reindexCapability(event.capability_id);else await syncPlatformCapabilityIndex(undefined,{force:true});await db.prepare("UPDATE capability_index_events SET status='completed',completed_at=? WHERE event_id=?").bind(new Date().toISOString(),event.event_id).run();completed+=1;}catch(error){await db.prepare("UPDATE capability_index_events SET status='failed',error_message=? WHERE event_id=?").bind(error instanceof Error?error.message:"重试失败",event.event_id).run();failed+=1;}}return {status:failed?"degraded":"healthy",retried:failures.items.length,completed,failed};}
