import {DATA_SOURCE_REGISTRY,MODULE_REGISTRY,TOOL_CATALOG,WORKFLOW_REGISTRY} from "./agent-registry";
import {STRATEGY_REGISTRY} from "./quant-research";
import type {AIProviderProfile} from "./ai-provider-catalog";

export type CapabilityStatus="available"|"beta"|"planned"|"disabled"|"unavailable";
export type CapabilityDocument={capability_id:string;name:string;category:"page"|"tool"|"data_source"|"workflow"|"model"|"workspace"|"quant"|"risk";description:string;status:CapabilityStatus;route:string|null;inputs:string[];outputs:string[];requirements:string[];limitations:string[];permissions:string[];requires_confirmation:boolean;supports_agent:boolean;supports_workspace:boolean;data_sources:string[];example_requests:string[];last_updated:string;version:string;source:string;knowledge_type:"platform_capabilities"};
export type CapabilityHit=Pick<CapabilityDocument,"capability_id"|"name"|"status"|"route"|"last_updated"|"source"|"knowledge_type">&{score:number;why_relevant:string;next_action:"open"|"configure"|"run"|"ask_user"};

const VERIFIED_AT="2026-07-23";
const page=(id:string,name:string,route:string,description:string,status:CapabilityStatus="available"):CapabilityDocument=>({capability_id:id,name,category:"page",description,status,route,inputs:[],outputs:["可交互页面"],requirements:[],limitations:[],permissions:["登录用户保存个人数据"],requires_confirmation:false,supports_agent:true,supports_workspace:true,data_sources:[],example_requests:[`打开${name}`,`${name}能做什么`],last_updated:VERIFIED_AT,version:"1.0",source:"route_registry",knowledge_type:"platform_capabilities"});

export function buildCapabilityRegistry(providers:AIProviderProfile[]=[]):CapabilityDocument[]{
  const pages=[page("page_home","首页","/","目标入口、当前工作台和最近状态"),page("page_agent","Agent 工作台","/agent","拆解自然语言目标、调用白名单工具并预览工作台修改"),page("page_workspace","模块化工作台","/workspace","手工、自然语言和 JSON 配置工作台"),page("page_etf","ETF 诊断","/etf-tool","搜索 ETF、穿透持仓并检查重复暴露"),page("page_trade","交易复盘","/trade-tool","导入 CSV，进行 FIFO 归因和行为复盘"),page("page_quant","低频量化研究","/quant","创建低频策略、检查数据与可信度、回测和纸面模拟","beta"),page("page_ai","AI 模型设置","/ai-settings","查看和切换已配置模型"),page("page_privacy","数据与隐私","/profile","管理个人偏好与数据边界")];
  const tools=TOOL_CATALOG.map<CapabilityDocument>(item=>({capability_id:`tool_${item.toolId}`,name:item.name,category:item.category==="quant"?"quant":item.category==="risk"?"risk":"tool",description:item.description,status:item.enabled?"available":"disabled",route:item.category==="quant"?"/quant":item.toolId.includes("etf")?"/etf-tool":item.toolId.includes("trade")?"/trade-tool":"/agent",inputs:Object.keys(item.inputSchema),outputs:Object.keys(item.outputSchema),requirements:item.dataSources,limitations:item.permissionLevel==="restricted"?["产品安全策略禁止执行"]:[],permissions:[item.permissionLevel],requires_confirmation:item.permissionLevel!=="safe",supports_agent:item.permissionLevel!=="restricted",supports_workspace:true,data_sources:item.dataSources,example_requests:item.keywords.slice(0,4),last_updated:VERIFIED_AT,version:item.version,source:"tool_registry",knowledge_type:"platform_capabilities"}));
  const modules=MODULE_REGISTRY.map<CapabilityDocument>(item=>({capability_id:`module_${item.moduleId}`,name:item.name,category:"workspace",description:`可复用的${item.name}工作台模块`,status:"available",route:"/workspace",inputs:item.requiredSources,outputs:["工作台卡片"],requirements:item.requiredSources,limitations:[],permissions:["修改前确认"],requires_confirmation:true,supports_agent:true,supports_workspace:true,data_sources:item.requiredSources,example_requests:[`把${item.name}加入工作台`],last_updated:VERIFIED_AT,version:item.version,source:"module_registry",knowledge_type:"platform_capabilities"}));
  const sources=DATA_SOURCE_REGISTRY.map<CapabilityDocument>(item=>({capability_id:`source_${item.sourceId}`,name:item.name,category:"data_source",description:item.scope,status:item.available?"available":"unavailable",route:null,inputs:[],outputs:["结构化工具数据"],requirements:[],limitations:item.available?[]:["尚未授权或接入"],permissions:item.sourceId.includes("user")?["用户主动提供"]:[],requires_confirmation:false,supports_agent:item.available,supports_workspace:item.available,data_sources:[item.sourceId],example_requests:[],last_updated:VERIFIED_AT,version:"1.0",source:"data_source_registry",knowledge_type:"platform_capabilities"}));
  const strategies=STRATEGY_REGISTRY.map<CapabilityDocument>(item=>({capability_id:`strategy_${item.id}`,name:item.name,category:"quant",description:item.description,status:item.backtestSupported?"beta":"available",route:"/quant",inputs:["标的","频率",...item.requiredData],outputs:item.backtestSupported?["历史回测","可信度检查","纸面模拟"]:["研究配置","风险解释"],requirements:item.requiredData,limitations:item.limitations,permissions:["配置确认","不支持真实交易"],requires_confirmation:true,supports_agent:true,supports_workspace:true,data_sources:item.requiredData,example_requests:[`创建${item.name}策略`],last_updated:VERIFIED_AT,version:"1.0",source:"strategy_registry",knowledge_type:"platform_capabilities"}));
  const workflows=Object.entries(WORKFLOW_REGISTRY).map<CapabilityDocument>(([id,steps])=>({capability_id:`workflow_${id}`,name:`${id} 流程`,category:"workflow",description:`可组合步骤：${steps.join(" → ")}`,status:"available",route:"/workspace",inputs:["用户目标"],outputs:["可确认工作流"],requirements:[],limitations:[],permissions:["修改前确认"],requires_confirmation:true,supports_agent:true,supports_workspace:true,data_sources:[],example_requests:[`创建${id}流程`],last_updated:VERIFIED_AT,version:"1.0",source:"workflow_registry",knowledge_type:"platform_capabilities"}));
  const models=providers.map<CapabilityDocument>(item=>({capability_id:`model_${item.providerId}`,name:item.displayName,category:"model",description:item.description,status:item.enabled&&item.connectionStatus==="available"?"available":"unavailable",route:"/ai-settings",inputs:["自然语言任务"],outputs:["规划或解释"],requirements:item.secretStatus==="missing"?["需要服务器端或个人安全配置"]:[],limitations:[item.privacyLabel],permissions:[item.mode??"external"],requires_confirmation:item.mode==="external",supports_agent:item.connectionStatus==="available",supports_workspace:false,data_sources:[],example_requests:[`使用${item.displayName}`],last_updated:VERIFIED_AT,version:item.model||"未配置",source:"provider_registry",knowledge_type:"platform_capabilities"}));
  return [...pages,...tools,...modules,...sources,...strategies,...workflows,...models];
}

function tokens(value:string){const normalized=value.toLowerCase().replace(/[^\p{L}\p{N}]+/gu," ");const words=normalized.split(/\s+/).filter(Boolean);const compact=normalized.replaceAll(" ","");const grams=Array.from({length:Math.max(0,compact.length-1)},(_,i)=>compact.slice(i,i+2));return new Set([...words,...grams]);}
export function searchCapabilities(query:string,registry:CapabilityDocument[],options:{route?:string;limit?:number;statuses?:CapabilityStatus[]}={}):CapabilityHit[]{const wanted=tokens(query);const statuses=options.statuses??["available","beta","planned","disabled","unavailable"];return registry.filter(item=>statuses.includes(item.status)).map(item=>{const hay=tokens([item.name,item.description,item.category,...item.inputs,...item.outputs,...item.example_requests].join(" "));let score=0;for(const token of wanted)if(hay.has(token))score+=token.length>2?3:1;if(options.route&&item.route===options.route)score+=2;if(/能做什么|有哪些|支持什么|平台/.test(query))score+=item.status==="available"?1:0;return {capability_id:item.capability_id,name:item.name,status:item.status,route:item.route,last_updated:item.last_updated,source:item.source,knowledge_type:item.knowledge_type,score,why_relevant:item.description,next_action:item.status==="available"||item.status==="beta"?(item.route?"open":"run"):"ask_user"} as CapabilityHit;}).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,options.limit??8);}
export function capabilityHealth(registry:CapabilityDocument[]){return {status:registry.length?"healthy":"unavailable",document_count:registry.length,available_count:registry.filter(item=>item.status==="available").length,beta_count:registry.filter(item=>item.status==="beta").length,unavailable_count:registry.filter(item=>item.status==="unavailable").length,last_verified_at:VERIFIED_AT,sources:["route_registry","tool_registry","module_registry","data_source_registry","strategy_registry","workflow_registry","provider_registry"]};}
