import {authenticatedOwnerKey,getUserDatabase,readUserSnapshot,writeUserSnapshot,type UserSnapshot} from "./user-snapshot";
import {DASHBOARD_DATA_SOURCES,DASHBOARD_MODULE_REGISTRY,applyDashboardPatch,createDashboardWorkspace,diffDashboardWorkspaces,interpretDashboardInstruction,normalizeDashboardWorkspace,validateDashboardPatch,validateDashboardWorkspace,type DashboardDataSource,type DashboardModule,type DashboardModuleTemplate,type DashboardPatch,type DashboardVersion,type DashboardWorkspace} from "./dashboard-system";
import type {Workspace} from "./personal-workbench";
import {callAIProvider,readProviderState} from "./ai-provider-catalog";

type State=UserSnapshot&{workspaces?:Workspace[];activeWorkspaceId?:string;dashboardVersions?:DashboardVersion[];dashboardRedoVersions?:DashboardVersion[];dashboardPrivacy?:DashboardPrivacy;dashboardDataSources?:DashboardDataSource[];dashboardModuleTemplates?:DashboardModuleTemplate[]};
export type DashboardPrivacy={savePortfolio:boolean;saveTrades:boolean;saveAIConversation:boolean;saveBacktests:boolean;saveSocialContent:boolean;allowExternalModels:boolean;localModelsOnly:boolean;retentionDays:0|7|30|90|365};
export const DEFAULT_DASHBOARD_PRIVACY:DashboardPrivacy={savePortfolio:false,saveTrades:false,saveAIConversation:false,saveBacktests:true,saveSocialContent:false,allowExternalModels:false,localModelsOnly:false,retentionDays:30};
async function load(){const result=await readUserSnapshot();if(result.status==="unauthorized")throw new Error("请先登录");const snapshot=(result.status==="ready"?result.snapshot:{}) as State;const workspaces=(snapshot.workspaces?.length?snapshot.workspaces:[createDashboardWorkspace()]).map(normalizeDashboardWorkspace);return {snapshot,workspaces,active:workspaces.find(item=>item.id===snapshot.activeWorkspaceId)??workspaces[0]};}
const version=(workspace:DashboardWorkspace,source:DashboardVersion["changeSource"],summary:string,diff:DashboardPatch["changes"],createdBy:DashboardVersion["createdBy"]):DashboardVersion=>({versionId:`wv-${crypto.randomUUID()}`,workspaceId:workspace.id,version:workspace.version,parentVersion:workspace.version>1?workspace.version-1:null,changeSource:source,changeSummary:summary,diff,snapshot:structuredClone(workspace),createdAt:new Date().toISOString(),createdBy});
async function persist(snapshot:State,workspaces:DashboardWorkspace[]){snapshot.workspaces=workspaces;snapshot.activeWorkspaceId=snapshot.activeWorkspaceId??workspaces[0]?.id;await writeUserSnapshot(snapshot);}
const allSources=(snapshot:State)=>[...DASHBOARD_DATA_SOURCES,...(snapshot.dashboardDataSources??[])];const sourceIds=(snapshot:State)=>allSources(snapshot).map(item=>item.sourceId);
export async function dashboardState(id?:string){const {snapshot,workspaces,active}=await load();const workspace=workspaces.find(item=>item.id===id)??active;return {workspace,workspaces,modules:DASHBOARD_MODULE_REGISTRY,dataSources:allSources(snapshot),versions:(snapshot.dashboardVersions??[]).filter(item=>item.workspaceId===workspace.id),privacy:snapshot.dashboardPrivacy??DEFAULT_DASHBOARD_PRIVACY};}
export async function createDashboard(input:{name?:string;workspace?:unknown;confirmed?:boolean}){if(input.confirmed!==true)throw new Error("创建工作台前必须明确确认");const {snapshot,workspaces}=await load();const created=input.workspace?validateDashboardWorkspace(input.workspace,sourceIds(snapshot)):{valid:true as const,workspace:createDashboardWorkspace(input.name)};if(!created.valid)throw new Error(created.errors.join("；"));created.workspace.id=`workspace-${crypto.randomUUID()}`;created.workspace.version=1;created.workspace.createdAt=new Date().toISOString();created.workspace.updatedAt=created.workspace.createdAt;snapshot.dashboardVersions=[...(snapshot.dashboardVersions??[]),version(created.workspace,"manual","创建工作台",[],"user")].slice(-200);snapshot.activeWorkspaceId=created.workspace.id;await persist(snapshot,[...workspaces,created.workspace]);return created.workspace;}
export async function saveDashboard(id:string,input:{workspace?:unknown;source?:DashboardVersion["changeSource"];summary?:string;confirmed?:boolean}){if(input.confirmed!==true)throw new Error("修改工作台前必须明确确认");const {snapshot,workspaces}=await load();const current=workspaces.find(item=>item.id===id);if(!current)throw new Error("工作台不存在");const checked=validateDashboardWorkspace(input.workspace,sourceIds(snapshot));if(!checked.valid)throw new Error(checked.errors.join("；"));if(checked.workspace.id!==id)throw new Error("配置中的 workspace id 不匹配");checked.workspace.version=current.version+1;checked.workspace.updatedAt=new Date().toISOString();const diff=diffDashboardWorkspaces(current,checked.workspace);snapshot.dashboardVersions=[...(snapshot.dashboardVersions??[]),version(current,input.source??"manual",input.summary??`保存 ${diff.length} 项工作台修改`,diff,"user")].slice(-200);snapshot.dashboardRedoVersions=[];await persist(snapshot,workspaces.map(item=>item.id===id?checked.workspace:item));return checked.workspace;}
export async function deleteDashboard(id:string,confirmed:boolean){if(!confirmed)throw new Error("删除工作台前必须明确确认");const {snapshot,workspaces}=await load();if(workspaces.length<=1)throw new Error("至少保留一个工作台");const kept=workspaces.filter(item=>item.id!==id);snapshot.activeWorkspaceId=kept[0].id;await persist(snapshot,kept);return {status:"deleted",workspaceId:id};}
export async function duplicateDashboard(id:string,name?:string){const {snapshot,workspaces}=await load();const current=workspaces.find(item=>item.id===id);if(!current)throw new Error("工作台不存在");const copy=structuredClone(current);copy.id=`workspace-${crypto.randomUUID()}`;copy.name=name?.trim()||`${current.name} 副本`;copy.version=1;copy.createdAt=new Date().toISOString();copy.updatedAt=copy.createdAt;copy.modules=copy.modules.map(item=>({...item,instanceId:`${item.type}-${crypto.randomUUID().slice(0,8)}`}));snapshot.dashboardVersions=[...(snapshot.dashboardVersions??[]),version(copy,"manual",`复制自 ${current.name}`,[],"user")].slice(-200);snapshot.activeWorkspaceId=copy.id;await persist(snapshot,[...workspaces,copy]);return copy;}
export async function setDefaultDashboard(id:string){const {snapshot,workspaces}=await load();if(!workspaces.some(item=>item.id===id))throw new Error("工作台不存在");snapshot.activeWorkspaceId=id;await persist(snapshot,workspaces);return {workspaceId:id,status:"default"};}
export async function compareDashboards(leftId:string,rightId:string){const {workspaces}=await load();const left=workspaces.find(item=>item.id===leftId),right=workspaces.find(item=>item.id===rightId);if(!left||!right)throw new Error("用于对比的工作台不存在");return {left:{id:left.id,name:left.name,version:left.version},right:{id:right.id,name:right.name,version:right.version},changes:diffDashboardWorkspaces(left,right)};}
export async function previewDashboard(id:string,instruction:string){const {snapshot,workspaces}=await load();const current=workspaces.find(item=>item.id===id);if(!current)throw new Error("工作台不存在");const fallback=interpretDashboardInstruction(current,instruction);const state=await readProviderState();const provider=state.providers.find(item=>item.isDefault&&item.enabled&&item.connectionStatus==="available"&&item.providerId!=="mock");if(!provider)return {...fallback,planner:"local_registry" as const};try{const content=await callAIProvider(provider,[{role:"system",content:`你是工作台配置规划器，只返回 JSON。只能使用给出的模块实例、模块注册表和动作白名单，不得生成金融数据或交易动作。动作：add_module(moduleId), remove_module/hide_module/show_module/duplicate_module(instanceId), move_module/resize_module(instanceId,position), set_refresh(instanceId,value), set_data_source(instanceId,value), set_parameters(instanceId,value), set_theme(value), rename_workspace(value)。输出 workspaceId,baseVersion,changes,summary。`},{role:"user",content:JSON.stringify({instruction,workspace:{id:current.id,version:current.version,theme:current.theme,modules:current.modules.map(item=>({instanceId:item.instanceId,moduleId:item.type,title:item.title,position:item.position,refreshPolicy:item.refreshPolicy,dataSourceId:item.dataSourceId}))},moduleRegistry:DASHBOARD_MODULE_REGISTRY.map(item=>({moduleId:item.moduleId,name:item.name,dataSources:item.dataSources})),dataSources:allSources(snapshot).map(item=>item.sourceId)})}],700);const match=content.match(/\{[\s\S]*\}/);if(!match)throw new Error("模型没有返回 JSON");const patch=validateDashboardPatch(JSON.parse(match[0]),current,sourceIds(snapshot));applyDashboardPatch(current,patch,sourceIds(snapshot));return {...patch,planner:"ai_provider" as const,provider:provider.displayName,model:provider.model};}catch{return {...fallback,planner:"local_fallback" as const};}}
export async function applyDashboard(id:string,patch:DashboardPatch,confirmed:boolean,source:DashboardVersion["changeSource"]="agent"){if(!confirmed)throw new Error("应用修改前必须明确确认");const {snapshot,workspaces}=await load();const current=workspaces.find(item=>item.id===id);if(!current)throw new Error("工作台不存在");const next=applyDashboardPatch(current,patch,sourceIds(snapshot));snapshot.dashboardVersions=[...(snapshot.dashboardVersions??[]),version(current,source,patch.summary,patch.changes,source==="agent"?"agent":"user")].slice(-200);snapshot.dashboardRedoVersions=[];await persist(snapshot,workspaces.map(item=>item.id===id?next:item));return next;}
export async function restoreDashboard(id:string,versionId:string,confirmed:boolean){if(!confirmed)throw new Error("恢复版本前必须明确确认");const {snapshot,workspaces}=await load();const current=workspaces.find(item=>item.id===id);const target=(snapshot.dashboardVersions??[]).find(item=>item.versionId===versionId&&item.workspaceId===id);if(!current||!target)throw new Error("未找到版本");const restored=structuredClone(target.snapshot);restored.version=current.version+1;restored.updatedAt=new Date().toISOString();snapshot.dashboardVersions=[...(snapshot.dashboardVersions??[]),version(current,"manual",`恢复版本 ${target.version}`,[],"user")].slice(-200);await persist(snapshot,workspaces.map(item=>item.id===id?restored:item));return restored;}
export async function cloneDashboardVersion(id:string,versionId:string,confirmed:boolean){if(!confirmed)throw new Error("从历史版本创建工作台前必须明确确认");const {snapshot}=await load();const target=(snapshot.dashboardVersions??[]).find(item=>item.versionId===versionId&&item.workspaceId===id);if(!target)throw new Error("未找到版本");const copy=structuredClone(target.snapshot);copy.name=`${copy.name} · v${target.version}`;return createDashboard({workspace:copy,confirmed:true});}
export async function undoDashboard(id:string){const {snapshot,workspaces}=await load();const current=workspaces.find(item=>item.id===id);const versions=snapshot.dashboardVersions??[];const index=versions.findLastIndex(item=>item.workspaceId===id);if(!current||index<0)throw new Error("没有可撤销版本");const target=versions[index];snapshot.dashboardVersions=versions.filter((_,i)=>i!==index);snapshot.dashboardRedoVersions=[...(snapshot.dashboardRedoVersions??[]),version(current,"manual","重做快照",[],"user")].slice(-100);await persist(snapshot,workspaces.map(item=>item.id===id?target.snapshot:item));return target.snapshot;}
export async function redoDashboard(id:string){const {snapshot,workspaces}=await load();const current=workspaces.find(item=>item.id===id);const versions=snapshot.dashboardRedoVersions??[];const index=versions.findLastIndex(item=>item.workspaceId===id);if(!current||index<0)throw new Error("没有可重做版本");const target=versions[index];snapshot.dashboardRedoVersions=versions.filter((_,i)=>i!==index);snapshot.dashboardVersions=[...(snapshot.dashboardVersions??[]),version(current,"manual","撤销快照",[],"user")].slice(-200);await persist(snapshot,workspaces.map(item=>item.id===id?target.snapshot:item));return target.snapshot;}
export async function privacySettings(next?:Partial<DashboardPrivacy>,confirmed=false){const {snapshot}=await load();if(!next)return snapshot.dashboardPrivacy??DEFAULT_DASHBOARD_PRIVACY;if(!confirmed)throw new Error("保存隐私策略前必须明确确认");snapshot.dashboardPrivacy={...(snapshot.dashboardPrivacy??DEFAULT_DASHBOARD_PRIVACY),...next};await writeUserSnapshot(snapshot);return snapshot.dashboardPrivacy;}
export async function listDashboardDataSources(){const {snapshot}=await load();return allSources(snapshot);}
export async function addDashboardDataSource(input:{name?:string;type?:DashboardDataSource["type"];fields?:string[];endpoint?:string;retentionPolicy?:DashboardDataSource["retentionPolicy"];confirmed?:boolean}){if(!input.confirmed)throw new Error("添加数据源前必须明确确认");if(!input.name?.trim())throw new Error("数据源名称不能为空");if(!input.type||!["api","database","file","registry"].includes(input.type))throw new Error("数据源类型无效");let endpointHost:string|undefined;if(input.endpoint){const url=new URL(input.endpoint);if(url.protocol!=="https:")throw new Error("外部数据源只接受 HTTPS 地址");endpointHost=url.host;}const {snapshot}=await load();const item:DashboardDataSource={sourceId:`custom_${crypto.randomUUID().slice(0,12)}`,name:input.name.trim(),type:input.type,fields:(input.fields??[]).filter(value=>typeof value==="string").slice(0,100),refreshOptions:["manual","1h","daily"],retentionPolicy:input.retentionPolicy??"none",permissions:["explicit_consent","approved_adapter"],available:false,statusLabel:"配置已保存；需批准适配器后才能联网读取",custom:true,endpointHost};snapshot.dashboardDataSources=[...(snapshot.dashboardDataSources??[]),item].slice(-50);await writeUserSnapshot(snapshot);return item;}
export async function deleteDashboardDataSource(id:string,confirmed:boolean){if(!confirmed)throw new Error("删除数据源前必须明确确认");const {snapshot,workspaces}=await load();const source=(snapshot.dashboardDataSources??[]).find(item=>item.sourceId===id);if(!source)throw new Error("只能删除当前用户创建的数据源");if(workspaces.some(workspace=>workspace.modules.some(module=>module.dataSourceId===id)))throw new Error("该数据源仍被模块使用，请先切换模块数据源");snapshot.dashboardDataSources=(snapshot.dashboardDataSources??[]).filter(item=>item.sourceId!==id);await writeUserSnapshot(snapshot);return {status:"deleted",sourceId:id};}

export async function listDashboardModuleTemplates(){const {snapshot}=await load();return snapshot.dashboardModuleTemplates??[];}
export async function saveDashboardModuleTemplate(input:{name?:string;module?:DashboardModule;confirmed?:boolean}){if(!input.confirmed)throw new Error("保存模块模板前必须明确确认");if(!input.name?.trim()||!input.module)throw new Error("模板名称和模块配置不能为空");if(!DASHBOARD_MODULE_REGISTRY.some(item=>item.moduleId===input.module!.type))throw new Error("模块未注册");const {snapshot}=await load();const template:DashboardModuleTemplate={templateId:`mt-${crypto.randomUUID()}`,name:input.name.trim().slice(0,40),module:{...structuredClone(input.module),instanceId:`${input.module.type}-template`},createdAt:new Date().toISOString()};snapshot.dashboardModuleTemplates=[...(snapshot.dashboardModuleTemplates??[]),template].slice(-50);await writeUserSnapshot(snapshot);return template;}
export async function deleteDashboardModuleTemplate(id:string,confirmed:boolean){if(!confirmed)throw new Error("删除模块模板前必须明确确认");const {snapshot}=await load();const before=snapshot.dashboardModuleTemplates??[];snapshot.dashboardModuleTemplates=before.filter(item=>item.templateId!==id);if(before.length===snapshot.dashboardModuleTemplates.length)throw new Error("模块模板不存在");await writeUserSnapshot(snapshot);return {status:"deleted",templateId:id};}

async function ensureShareTable(){const db=await getUserDatabase();await db.prepare(`CREATE TABLE IF NOT EXISTS dashboard_shares (
  share_token TEXT PRIMARY KEY NOT NULL,
  owner_key TEXT NOT NULL,
  workspace_payload TEXT NOT NULL,
  created_at TEXT NOT NULL,
  revoked_at TEXT
)`).run();return db;}
export async function shareDashboard(id:string,confirmed:boolean){if(!confirmed)throw new Error("创建只读分享前必须明确确认");const owner=await authenticatedOwnerKey();if(!owner)throw new Error("请先登录");const {workspaces}=await load();const workspace=workspaces.find(item=>item.id===id);if(!workspace)throw new Error("工作台不存在");const token=crypto.randomUUID().replaceAll("-","");const db=await ensureShareTable();await db.prepare("INSERT INTO dashboard_shares (share_token,owner_key,workspace_payload,created_at,revoked_at) VALUES (?,?,?,?,NULL)").bind(token,owner,JSON.stringify(workspace),new Date().toISOString()).run();return {shareToken:token,readOnly:true};}
export async function readSharedDashboard(token:string){const db=await ensureShareTable();const result=await db.prepare("SELECT workspace_payload,created_at FROM dashboard_shares WHERE share_token=? AND revoked_at IS NULL").bind(token).all() as {results?:Array<{workspace_payload:string;created_at:string}>};const row=result.results?.[0];if(!row)throw new Error("分享不存在或已失效");const checked=validateDashboardWorkspace(JSON.parse(row.workspace_payload));if(!checked.valid)throw new Error("分享配置无效");return {workspace:checked.workspace,readOnly:true,sharedAt:row.created_at};}
export async function cloneSharedDashboard(token:string,confirmed:boolean){if(!confirmed)throw new Error("复制分享工作台前必须明确确认");const shared=await readSharedDashboard(token);const copy=structuredClone(shared.workspace);copy.name=`${copy.name} 副本`;return createDashboard({workspace:copy,confirmed:true});}
export async function revokeDashboardShare(token:string,confirmed:boolean){if(!confirmed)throw new Error("撤销分享前必须明确确认");const owner=await authenticatedOwnerKey();if(!owner)throw new Error("请先登录");const db=await ensureShareTable();await db.prepare("UPDATE dashboard_shares SET revoked_at=? WHERE share_token=? AND owner_key=?").bind(new Date().toISOString(),token,owner).run();return {status:"revoked",shareToken:token};}
