/* Generated by scripts/generate-capability-manifest.mjs. Do not edit by hand. */
export const CAPABILITY_MANIFEST_GENERATED_AT="2026-07-22T21:15:22.717Z";
export const GENERATED_ROUTE_CAPABILITIES=[
  {
    "route": "/",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/page.tsx"
  },
  {
    "route": "/agent",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/agent/page.tsx"
  },
  {
    "route": "/agent/goal/parse",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/agent/goal/parse/route.ts"
  },
  {
    "route": "/agent/tasks",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/agent/tasks/route.ts"
  },
  {
    "route": "/agent/tasks/:task_id",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/agent/tasks/[task_id]/route.ts"
  },
  {
    "route": "/agent/tasks/:task_id/cancel",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/agent/tasks/[task_id]/cancel/route.ts"
  },
  {
    "route": "/agent/tasks/:task_id/confirm",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/agent/tasks/[task_id]/confirm/route.ts"
  },
  {
    "route": "/agent/tasks/:task_id/retry",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/agent/tasks/[task_id]/retry/route.ts"
  },
  {
    "route": "/agent/tasks/:task_id/tools/:tool_id/retry",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/agent/tasks/[task_id]/tools/[tool_id]/retry/route.ts"
  },
  {
    "route": "/agent/workspace/apply",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/agent/workspace/apply/route.ts"
  },
  {
    "route": "/agent/workspace/interpret-config",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/agent/workspace/interpret-config/route.ts"
  },
  {
    "route": "/agent/workspace/preview",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/agent/workspace/preview/route.ts"
  },
  {
    "route": "/agent/workspace/undo",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/agent/workspace/undo/route.ts"
  },
  {
    "route": "/ai-settings",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/ai-settings/page.tsx"
  },
  {
    "route": "/ai/local-models",
    "kind": "api",
    "methods": [],
    "source": "app/ai/local-models/route.ts"
  },
  {
    "route": "/ai/local-models/:model_name",
    "kind": "api",
    "methods": [],
    "source": "app/ai/local-models/[model_name]/route.ts"
  },
  {
    "route": "/ai/providers",
    "kind": "api",
    "methods": [],
    "source": "app/ai/providers/route.ts"
  },
  {
    "route": "/ai/providers/:provider_id",
    "kind": "api",
    "methods": [],
    "source": "app/ai/providers/[provider_id]/route.ts"
  },
  {
    "route": "/ai/providers/:provider_id/capabilities",
    "kind": "api",
    "methods": [],
    "source": "app/ai/providers/[provider_id]/capabilities/route.ts"
  },
  {
    "route": "/ai/providers/:provider_id/health",
    "kind": "api",
    "methods": [],
    "source": "app/ai/providers/[provider_id]/health/route.ts"
  },
  {
    "route": "/ai/providers/:provider_id/select",
    "kind": "api",
    "methods": [],
    "source": "app/ai/providers/[provider_id]/select/route.ts"
  },
  {
    "route": "/ai/providers/:provider_id/test",
    "kind": "api",
    "methods": [],
    "source": "app/ai/providers/[provider_id]/test/route.ts"
  },
  {
    "route": "/analysis",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/analysis/page.tsx"
  },
  {
    "route": "/api/ai/audit",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/api/ai/audit/route.ts"
  },
  {
    "route": "/api/ai/local-models",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/api/ai/local-models/route.ts"
  },
  {
    "route": "/api/ai/local-models/:model_name",
    "kind": "api",
    "methods": [
      "DELETE"
    ],
    "source": "app/api/ai/local-models/[model_name]/route.ts"
  },
  {
    "route": "/api/ai/privacy",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/api/ai/privacy/route.ts"
  },
  {
    "route": "/api/ai/providers",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/api/ai/providers/route.ts"
  },
  {
    "route": "/api/ai/providers/:provider_id",
    "kind": "api",
    "methods": [
      "DELETE",
      "GET",
      "PUT"
    ],
    "source": "app/api/ai/providers/[provider_id]/route.ts"
  },
  {
    "route": "/api/ai/providers/:provider_id/capabilities",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/api/ai/providers/[provider_id]/capabilities/route.ts"
  },
  {
    "route": "/api/ai/providers/:provider_id/health",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/api/ai/providers/[provider_id]/health/route.ts"
  },
  {
    "route": "/api/ai/providers/:provider_id/set-default",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/api/ai/providers/[provider_id]/set-default/route.ts"
  },
  {
    "route": "/api/ai/providers/:provider_id/test",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/api/ai/providers/[provider_id]/test/route.ts"
  },
  {
    "route": "/api/ai/providers/discover",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/api/ai/providers/discover/route.ts"
  },
  {
    "route": "/api/ai/providers/test",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/api/ai/providers/test/route.ts"
  },
  {
    "route": "/api/etf/diagnosis",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/api/etf/diagnosis/route.ts"
  },
  {
    "route": "/api/etf/search",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/api/etf/search/route.ts"
  },
  {
    "route": "/api/evaluation/data-sources",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/api/evaluation/data-sources/route.ts"
  },
  {
    "route": "/api/evaluation/model",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/api/evaluation/model/route.ts"
  },
  {
    "route": "/api/evaluation/pilot",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/api/evaluation/pilot/route.ts"
  },
  {
    "route": "/api/evaluation/user-study",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/api/evaluation/user-study/route.ts"
  },
  {
    "route": "/api/evidence/:code",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/api/evidence/[code]/route.ts"
  },
  {
    "route": "/api/financial/:code",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/api/financial/[code]/route.ts"
  },
  {
    "route": "/api/information/:code",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/api/information/[code]/route.ts"
  },
  {
    "route": "/api/market/benchmark",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/api/market/benchmark/route.ts"
  },
  {
    "route": "/api/market/overview",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/api/market/overview/route.ts"
  },
  {
    "route": "/api/me/snapshot",
    "kind": "api",
    "methods": [
      "DELETE",
      "GET",
      "PUT"
    ],
    "source": "app/api/me/snapshot/route.ts"
  },
  {
    "route": "/api/privacy/data",
    "kind": "api",
    "methods": [
      "DELETE",
      "GET"
    ],
    "source": "app/api/privacy/data/route.ts"
  },
  {
    "route": "/api/privacy/settings",
    "kind": "api",
    "methods": [
      "GET",
      "PUT"
    ],
    "source": "app/api/privacy/settings/route.ts"
  },
  {
    "route": "/api/quant/parse",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/api/quant/parse/route.ts"
  },
  {
    "route": "/api/quant/run",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/api/quant/run/route.ts"
  },
  {
    "route": "/api/stocks/search",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/api/stocks/search/route.ts"
  },
  {
    "route": "/api/system/health",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/api/system/health/route.ts"
  },
  {
    "route": "/api/trade/attribution",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/api/trade/attribution/route.ts"
  },
  {
    "route": "/assistant/message",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/assistant/message/route.ts"
  },
  {
    "route": "/assistant/session",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/assistant/session/route.ts"
  },
  {
    "route": "/assistant/session/reset",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/assistant/session/reset/route.ts"
  },
  {
    "route": "/capabilities",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/capabilities/route.ts"
  },
  {
    "route": "/capabilities/:id",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/capabilities/[id]/route.ts"
  },
  {
    "route": "/capabilities/health",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/capabilities/health/route.ts"
  },
  {
    "route": "/capabilities/index/failures",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/capabilities/index/failures/route.ts"
  },
  {
    "route": "/capabilities/index/failures/retry",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/capabilities/index/failures/retry/route.ts"
  },
  {
    "route": "/capabilities/index/rebuild",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/capabilities/index/rebuild/route.ts"
  },
  {
    "route": "/capabilities/index/reindex/:capability_id",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/capabilities/index/reindex/[capability_id]/route.ts"
  },
  {
    "route": "/capabilities/index/status",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/capabilities/index/status/route.ts"
  },
  {
    "route": "/capabilities/reindex",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/capabilities/reindex/route.ts"
  },
  {
    "route": "/data-sources",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/data-sources/route.ts"
  },
  {
    "route": "/data-sources/:id",
    "kind": "api",
    "methods": [
      "DELETE",
      "GET"
    ],
    "source": "app/data-sources/[id]/route.ts"
  },
  {
    "route": "/data-sources/:id/test",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/data-sources/[id]/test/route.ts"
  },
  {
    "route": "/demo",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/demo/page.tsx"
  },
  {
    "route": "/etf-tool",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/etf-tool/page.tsx"
  },
  {
    "route": "/evaluation",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/evaluation/page.tsx"
  },
  {
    "route": "/goal/interpret",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/goal/interpret/route.ts"
  },
  {
    "route": "/module-templates",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/module-templates/route.ts"
  },
  {
    "route": "/module-templates/:id",
    "kind": "api",
    "methods": [
      "DELETE"
    ],
    "source": "app/module-templates/[id]/route.ts"
  },
  {
    "route": "/modules",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/modules/route.ts"
  },
  {
    "route": "/opportunity",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/opportunity/page.tsx"
  },
  {
    "route": "/paper-trading/run",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/paper-trading/run/route.ts"
  },
  {
    "route": "/pilot",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/pilot/page.tsx"
  },
  {
    "route": "/portfolio",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/portfolio/page.tsx"
  },
  {
    "route": "/profile",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/profile/page.tsx"
  },
  {
    "route": "/quant",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/quant/page.tsx"
  },
  {
    "route": "/quant/audit",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/quant/audit/route.ts"
  },
  {
    "route": "/quant/backtest",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/backtest/route.ts"
  },
  {
    "route": "/quant/backtest/lookahead-check",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/backtest/lookahead-check/route.ts"
  },
  {
    "route": "/quant/backtest/universe-check",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/backtest/universe-check/route.ts"
  },
  {
    "route": "/quant/backtest/validate",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/backtest/validate/route.ts"
  },
  {
    "route": "/quant/data-quality/check",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/data-quality/check/route.ts"
  },
  {
    "route": "/quant/drift/:strategy_id",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/quant/drift/[strategy_id]/route.ts"
  },
  {
    "route": "/quant/engine/route",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/engine/route/route.ts"
  },
  {
    "route": "/quant/engines",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/quant/engines/route.ts"
  },
  {
    "route": "/quant/engines/:engine_id",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/quant/engines/[engine_id]/route.ts"
  },
  {
    "route": "/quant/licenses",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/quant/licenses/route.ts"
  },
  {
    "route": "/quant/licenses/check",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/licenses/check/route.ts"
  },
  {
    "route": "/quant/paper-run",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/paper-run/route.ts"
  },
  {
    "route": "/quant/paper/run",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/paper/run/route.ts"
  },
  {
    "route": "/quant/runs/:run_id",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/quant/runs/[run_id]/route.ts"
  },
  {
    "route": "/quant/runs/:run_id/logs",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/quant/runs/[run_id]/logs/route.ts"
  },
  {
    "route": "/quant/schedule",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/schedule/route.ts"
  },
  {
    "route": "/quant/schedules",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/quant/schedules/route.ts"
  },
  {
    "route": "/quant/schedules/:id",
    "kind": "api",
    "methods": [
      "DELETE",
      "PUT"
    ],
    "source": "app/quant/schedules/[id]/route.ts"
  },
  {
    "route": "/quant/schedules/:id/run-result",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/schedules/[id]/run-result/route.ts"
  },
  {
    "route": "/quant/signals",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/quant/signals/route.ts"
  },
  {
    "route": "/quant/social/analyze",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/social/analyze/route.ts"
  },
  {
    "route": "/quant/social/policy",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/quant/social/policy/route.ts"
  },
  {
    "route": "/quant/strategies",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/quant/strategies/route.ts"
  },
  {
    "route": "/quant/strategies/:id",
    "kind": "api",
    "methods": [
      "DELETE",
      "POST",
      "PUT"
    ],
    "source": "app/quant/strategies/[id]/route.ts"
  },
  {
    "route": "/quant/strategy",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/quant/strategy/route.ts"
  },
  {
    "route": "/quant/strategy/:id",
    "kind": "api",
    "methods": [
      "DELETE",
      "GET",
      "PUT"
    ],
    "source": "app/quant/strategy/[id]/route.ts"
  },
  {
    "route": "/quant/strategy/:id/backtest",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/strategy/[id]/backtest/route.ts"
  },
  {
    "route": "/quant/strategy/:id/copy",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/strategy/[id]/copy/route.ts"
  },
  {
    "route": "/quant/strategy/:id/pause",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/strategy/[id]/pause/route.ts"
  },
  {
    "route": "/quant/strategy/:id/resume",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/strategy/[id]/resume/route.ts"
  },
  {
    "route": "/quant/strategy/:id/run",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/strategy/[id]/run/route.ts"
  },
  {
    "route": "/quant/strategy/backtest",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/strategy/backtest/route.ts"
  },
  {
    "route": "/quant/strategy/compare",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/strategy/compare/route.ts"
  },
  {
    "route": "/quant/strategy/compile",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/strategy/compile/route.ts"
  },
  {
    "route": "/quant/strategy/confirm",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/strategy/confirm/route.ts"
  },
  {
    "route": "/quant/strategy/parse",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/strategy/parse/route.ts"
  },
  {
    "route": "/quant/strategy/preview",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/strategy/preview/route.ts"
  },
  {
    "route": "/quant/strategy/switch-engine",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/strategy/switch-engine/route.ts"
  },
  {
    "route": "/quant/tasks",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/quant/tasks/route.ts"
  },
  {
    "route": "/quant/tasks/:task_id",
    "kind": "api",
    "methods": [
      "GET",
      "PUT"
    ],
    "source": "app/quant/tasks/[task_id]/route.ts"
  },
  {
    "route": "/quant/tasks/:task_id/cancel",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/tasks/[task_id]/cancel/route.ts"
  },
  {
    "route": "/quant/tasks/:task_id/confirm",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/tasks/[task_id]/confirm/route.ts"
  },
  {
    "route": "/quant/tasks/:task_id/retry",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/quant/tasks/[task_id]/retry/route.ts"
  },
  {
    "route": "/shared-workspaces/:token",
    "kind": "api",
    "methods": [
      "DELETE",
      "GET"
    ],
    "source": "app/shared-workspaces/[token]/route.ts"
  },
  {
    "route": "/shared-workspaces/:token/clone",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/shared-workspaces/[token]/clone/route.ts"
  },
  {
    "route": "/shared/:token",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/shared/[token]/page.tsx"
  },
  {
    "route": "/strategy/confirm",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/strategy/confirm/route.ts"
  },
  {
    "route": "/strategy/preview",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/strategy/preview/route.ts"
  },
  {
    "route": "/tools",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/tools/route.ts"
  },
  {
    "route": "/tools/proposals",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/tools/proposals/route.ts"
  },
  {
    "route": "/trade-tool",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/trade-tool/page.tsx"
  },
  {
    "route": "/workspace",
    "kind": "page",
    "methods": [
      "GET"
    ],
    "source": "app/workspace/page.tsx"
  },
  {
    "route": "/workspace/apply",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspace/apply/route.ts"
  },
  {
    "route": "/workspace/command",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspace/command/route.ts"
  },
  {
    "route": "/workspace/command/:command_id/cancel",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspace/command/[command_id]/cancel/route.ts"
  },
  {
    "route": "/workspace/command/:command_id/confirm",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspace/command/[command_id]/confirm/route.ts"
  },
  {
    "route": "/workspace/export",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/workspace/export/route.ts"
  },
  {
    "route": "/workspace/history",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/workspace/history/route.ts"
  },
  {
    "route": "/workspace/preview",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspace/preview/route.ts"
  },
  {
    "route": "/workspace/quant-apply",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspace/quant-apply/route.ts"
  },
  {
    "route": "/workspace/quant-preview",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspace/quant-preview/route.ts"
  },
  {
    "route": "/workspace/redo",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspace/redo/route.ts"
  },
  {
    "route": "/workspace/undo",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspace/undo/route.ts"
  },
  {
    "route": "/workspaces",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/workspaces/route.ts"
  },
  {
    "route": "/workspaces/:id",
    "kind": "api",
    "methods": [
      "DELETE",
      "GET",
      "PUT"
    ],
    "source": "app/workspaces/[id]/route.ts"
  },
  {
    "route": "/workspaces/:id/duplicate",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspaces/[id]/duplicate/route.ts"
  },
  {
    "route": "/workspaces/:id/export",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/workspaces/[id]/export/route.ts"
  },
  {
    "route": "/workspaces/:id/modules",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspaces/[id]/modules/route.ts"
  },
  {
    "route": "/workspaces/:id/modules/:module_id",
    "kind": "api",
    "methods": [
      "DELETE",
      "PUT"
    ],
    "source": "app/workspaces/[id]/modules/[module_id]/route.ts"
  },
  {
    "route": "/workspaces/:id/redo",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspaces/[id]/redo/route.ts"
  },
  {
    "route": "/workspaces/:id/restore",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspaces/[id]/restore/route.ts"
  },
  {
    "route": "/workspaces/:id/set-default",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspaces/[id]/set-default/route.ts"
  },
  {
    "route": "/workspaces/:id/share",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspaces/[id]/share/route.ts"
  },
  {
    "route": "/workspaces/:id/undo",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspaces/[id]/undo/route.ts"
  },
  {
    "route": "/workspaces/:id/versions",
    "kind": "api",
    "methods": [
      "GET",
      "POST"
    ],
    "source": "app/workspaces/[id]/versions/route.ts"
  },
  {
    "route": "/workspaces/:id/versions/:version_id/clone",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspaces/[id]/versions/[version_id]/clone/route.ts"
  },
  {
    "route": "/workspaces/compare",
    "kind": "api",
    "methods": [
      "GET"
    ],
    "source": "app/workspaces/compare/route.ts"
  },
  {
    "route": "/workspaces/import",
    "kind": "api",
    "methods": [
      "POST"
    ],
    "source": "app/workspaces/import/route.ts"
  }
] as const;
