import type {PricePoint,QuantFrequency} from "./quant-research";

export const STRATEGY_INDICATORS=["moving_average_cross","rsi","macd","bollinger","volume_ratio","volatility","drawdown","pe","pb","roe","revenue_growth","profit_growth","cash_flow_quality","news_event","announcement_event","social_sentiment","industry_change","etf_holding_change","portfolio_weight"] as const;
export type StrategyIndicator=typeof STRATEGY_INDICATORS[number];
export type StrategyAction="notify"|"watch"|"paper_simulation";
export type StrategyLogic="AND"|"OR";
export type StrategyCondition={id:string;type:"indicator"|"volume"|"risk"|"valuation"|"financial"|"event"|"social"|"industry"|"etf"|"portfolio";name:StrategyIndicator;operator:">"|">="|"<"|"<="|"=="|"cross_above"|"cross_below"|"contains"|"changes";params:Record<string,number|string|boolean>;reference?:string;value?:number|string;explanation:string;required_data:string[]};
export type StrategyDSL={strategy_id:string;market:"CN_A";asset_type:"stock"|"etf"|"index"|"unknown";asset_universe:string[];frequency:QuantFrequency;logic:StrategyLogic;conditions:StrategyCondition[];action:StrategyAction;execution_mode:"manual_confirmation";version:number};
export type StrategyPreview={type:"strategy_preview";preview_id:string;name:string;original_text:string;asset:string;frequency:QuantFrequency;conditions:StrategyCondition[];logic:StrategyLogic;action:StrategyAction;parameters:Record<string,number|string|boolean>;explanation:string;warnings:string[];missing_information:string[];questions:string[];data_sources:Array<{id:string;name:string;status:"available"|"requires_authorization"|"user_input"}>;dsl:StrategyDSL;validation:StrategyValidation;requires_confirmation:true;parser:"ai_provider"|"deterministic_fallback";provider?:string;model?:string;created_at:string};
export type StrategyValidation={status:"pass"|"warning"|"blocked";errors:string[];warnings:string[];fixes:string[];affected_conditions:string[];allow_save:boolean;allow_backtest:boolean;allow_monitor:boolean};

const id=()=>`condition_${crypto.randomUUID().replaceAll("-","").slice(0,10)}`;
const condition=(value:Omit<StrategyCondition,"id">):StrategyCondition=>({id:id(),...value});
const codeFrom=(text:string)=>text.match(/(?<!\d)[036159]\d{5}(?!\d)/)?.[0]??(/沪深\s*300|CSI\s*300/i.test(text)&&!/ETF|基金/i.test(text)?"000300":"");
const pct=(text:string,pattern:RegExp)=>{const value=text.match(pattern)?.[1];return value?Number(value):null};

function frequencyFrom(text:string):QuantFrequency{return /盘中|实时|intraday|real[\s-]?time/i.test(text)?"realtime":/公告|新闻|事件|触发|disclosure|announcement|news|event[\s-]?triggered/i.test(text)?"event":/每月|月频|monthly/i.test(text)?"monthly":/每周|周频|weekly|each week/i.test(text)?"weekly":/每日|每天|日频|收盘|daily|each close|after (?:the )?close/i.test(text)?"daily_close":"manual";}
function actionFrom(text:string):StrategyAction{return /模拟|纸面|paper simulation|simulate/i.test(text)?"paper_simulation":/观察|自选|watchlist|watch/i.test(text)&&!/提醒|通知|notify|alert/i.test(text)?"watch":"notify";}
function sourceFor(condition:StrategyCondition){if(["news_event","announcement_event"].includes(condition.name))return {id:"authorized_news",name:"已授权新闻与公告",status:"requires_authorization" as const};if(condition.name==="social_sentiment")return {id:"authorized_social",name:"用户上传或授权社交样本",status:"requires_authorization" as const};if(["pe","pb","roe","revenue_growth","profit_growth","cash_flow_quality"].includes(condition.name))return {id:"financial_reports",name:"公开财报与估值",status:"available" as const};if(condition.name==="portfolio_weight")return {id:"user_portfolio",name:"用户保存的持仓",status:"user_input" as const};return {id:"daily_prices",name:"A 股日线行情",status:"available" as const};}

export function parseStrategyDeterministically(raw:string):StrategyPreview{
  const text=raw.trim().slice(0,3000);if(!text)throw new Error("请用一句话描述策略");const conditions:StrategyCondition[]=[];const missing:string[]=[];const questions:string[]=[];const warnings:string[]=[];
  const ma=text.match(/(\d+)\s*日均线[^。；，,]{0,18}(上穿|下穿|高于|低于)\s*(\d+)\s*日均线/i)??text.match(/(\d+)[-\s]*day moving average[^.;,]{0,30}(cross(?:es)? above|cross(?:es)? below|above|below)\s*(?:its\s*)?(\d+)[-\s]*day moving average/i);if(ma){const above=/上穿|高于|above/i.test(ma[2]);conditions.push(condition({type:"indicator",name:"moving_average_cross",operator:above?"cross_above":"cross_below",params:{short_period:Number(ma[1]),long_period:Number(ma[3]),direction:above?"above":"below",confirmation:/盘中|intraday/i.test(text)?"intraday":"close"},explanation:/[一-龥]/.test(ma[2])?`${ma[1]} 日均线${ma[2]}${ma[3]} 日均线`:`${ma[1]}-day moving average ${above?"crosses above":"crosses below"} ${ma[3]}-day moving average`,required_data:["daily_prices"]}));}
  const rsi=text.match(/RSI[^\d]{0,12}(\d+(?:\.\d+)?)/i);if(/RSI/i.test(text)){const below=/低于|小于|超卖|below|under|less than/i.test(text);conditions.push(condition({type:"indicator",name:"rsi",operator:below?"<":">",params:{period:Number(text.match(/(\d+)\s*(?:日|day)\s*RSI/i)?.[1]??14)},value:rsi?Number(rsi[1]):30,explanation:`RSI ${/[一-龥]/.test(text)?(below?"低于":"高于"):(below?"below":"above")} ${rsi?.[1]??30}`,required_data:["daily_prices"]}));}
  if(/MACD/i.test(text))conditions.push(condition({type:"indicator",name:"macd",operator:/死叉|下穿/.test(text)?"cross_below":"cross_above",params:{fast:12,slow:26,signal:9},explanation:`MACD ${/死叉|下穿/.test(text)?"死叉":"金叉"}`,required_data:["daily_prices"]}));
  if(/布林|BOLL/i.test(text))conditions.push(condition({type:"indicator",name:"bollinger",operator:/下轨|低于/.test(text)?"<":">",params:{period:20,stddev:2,band:/下轨/.test(text)?"lower":/中轨/.test(text)?"middle":"upper"},explanation:"价格与布林带位置满足描述条件",required_data:["daily_prices"]}));
  if(/成交量|放量|缩量|volume/i.test(text)){const ratio=pct(text,/放大\s*(\d+(?:\.\d+)?)\s*%/)??pct(text,/(\d+(?:\.\d+)?)\s*倍/)??pct(text,/volume[^.;,]{0,24}?(\d+(?:\.\d+)?)\s*%\s*(?:above|higher|increase)/i)??pct(text,/(\d+(?:\.\d+)?)\s*%\s*(?:above|higher than)\s*(?:the\s*)?(?:previous|prior) day/i);const normalized=ratio===null?null:ratio>10?1+ratio/100:ratio;let reference=/前一日|昨日|previous day|prior day/i.test(text)?"previous_day":/20\s*(?:日|day)/i.test(text)?"ma_20":"";if(!reference){missing.push(/[一-龥]/.test(text)?"成交量比较基准":"volume comparison baseline");questions.push(/[一-龥]/.test(text)?"“成交量放大”是相对前一日，还是 20 日平均成交量？":"Should volume be compared with the previous day or the 20-day average?");reference="unconfirmed";}const shrinking=/缩量|lower volume|volume decline/i.test(text);conditions.push(condition({type:"volume",name:"volume_ratio",operator:shrinking?"<":">=",params:{window:reference==="ma_20"?20:1},reference,value:normalized??1.5,explanation:/[一-龥]/.test(text)?`成交量相对${reference==="previous_day"?"前一日":reference==="ma_20"?"20 日均量":"待确认基准"}${shrinking?"下降":"放大"}${normalized?`至 ${normalized} 倍`:""}`:`Volume ${shrinking?"falls below":"rises to"} ${normalized??1.5}× ${reference==="previous_day"?"the previous day":reference==="ma_20"?"the 20-day average":"an unconfirmed baseline"}`,required_data:["daily_prices","volume"]}));}
  if(/波动率|volatility/i.test(text)){const value=pct(text,/(?:波动率|volatility)[^\d]{0,12}(\d+(?:\.\d+)?)\s*%/i)??pct(text,/(\d+(?:\.\d+)?)\s*%[^.;,]{0,12}volatility/i);const below=/低于|不超过|较小|below|under|no more than/i.test(text);conditions.push(condition({type:"risk",name:"volatility",operator:below?"<=":">=",params:{window:Number(text.match(/(\d+)\s*(?:日|day)\s*(?:波动率|volatility)/i)?.[1]??20)},value:value===null?0.25:value/100,explanation:/[一-龥]/.test(text)?"历史波动率达到指定阈值":`Historical volatility is ${below?"below":"above"} the specified threshold`,required_data:["daily_prices"]}));if(value===null){missing.push(/[一-龥]/.test(text)?"波动率阈值":"volatility threshold");questions.push(/[一-龥]/.test(text)?"波动率阈值是多少，例如 20 日年化波动率低于 25%？":"What volatility threshold should be used, for example 20-day annualized volatility below 25%?");}}
  if(/回撤|drawdown/i.test(text)){const value=pct(text,/(?:回撤|drawdown)[^\d]{0,12}(\d+(?:\.\d+)?)\s*%/i)??pct(text,/(\d+(?:\.\d+)?)\s*%[^.;,]{0,12}drawdown/i);const below=/低于|不超过|below|under|no more than/i.test(text);conditions.push(condition({type:"risk",name:"drawdown",operator:below?"<=":">=",params:{window:Number(text.match(/(?:近|past|over)\s*(\d+)\s*(?:日|day)/i)?.[1]??60)},value:value===null?0.1:value/100,explanation:/[一-龥]/.test(text)?"区间回撤达到指定阈值":`Period drawdown reaches the specified threshold`,required_data:["daily_prices"]}));if(value===null){missing.push(/[一-龥]/.test(text)?"回撤阈值":"drawdown threshold");questions.push(/[一-龥]/.test(text)?"回撤达到多少时触发？":"What drawdown should trigger the rule?");}}
  for(const [pattern,name,label] of [[/市盈率|\bPE\b/i,"pe","市盈率"],[/市净率|\bPB\b/i,"pb","市净率"],[/\bROE\b|净资产收益率/i,"roe","ROE"],[/营收增长/,"revenue_growth","营收增长"],[/净利润增长/,"profit_growth","净利润增长"],[/现金流.*利润|盈利质量/,"cash_flow_quality","现金流质量"]] as Array<[RegExp,StrategyIndicator,string]>){if(pattern.test(text)){const value=Number(text.match(new RegExp(`${label}[^\\d]{0,12}(\\d+(?:\\.\\d+)?)`))?.[1]??NaN);conditions.push(condition({type:["pe","pb"].includes(name)?"valuation":"financial",name,operator:/低于|不超过/.test(text)?"<=":">=",params:{period:"latest_disclosed"},value:Number.isFinite(value)?value:"unconfirmed",explanation:`${label}满足用户设定条件`,required_data:["financial_reports"]}));if(!Number.isFinite(value)){missing.push(`${label}阈值`);questions.push(`${label}需要达到什么数值才算满足？`);}}}
  if(/新闻/.test(text))conditions.push(condition({type:"event",name:"news_event",operator:"contains",params:{keywords:text.match(/[“「](.*?)[”」]/)?.[1]??"待确认"},explanation:"授权新闻出现指定事件",required_data:["authorized_news"]}));
  if(/公告|减持|回购|立案|处罚|重大合同|并购|业绩预告|disclosure|announcement|share reduction|buyback|investigation|penalty|contract|merger|earnings guidance/i.test(text))conditions.push(condition({type:"event",name:"announcement_event",operator:"contains",params:{keywords:["减持","回购","立案","处罚","重大合同","并购","业绩预告","share reduction","buyback","investigation","penalty","major contract","merger","earnings guidance"].filter(item=>text.toLowerCase().includes(item.toLowerCase())).join("|")||"unconfirmed"},explanation:/[一-龥]/.test(text)?"公开公告出现指定事件":"A public disclosure contains a specified event",required_data:["announcements"]}));
  if(/社交|小红书|雪球|情绪|热度/.test(text))conditions.push(condition({type:"social",name:"social_sentiment",operator:/上升|升温/.test(text)?"changes":">=",params:{sample_scope:"authorized_only",direction:/负面/.test(text)?"negative":/正面/.test(text)?"positive":"mixed"},explanation:"授权社交样本的情绪或热度变化",required_data:["authorized_social"]}));
  if(/行业.*涨|板块.*涨|行业.*跌/.test(text))conditions.push(condition({type:"industry",name:"industry_change",operator:/跌/.test(text)?"<=":">=",params:{industry:"待确认"},value:(pct(text,/(\d+(?:\.\d+)?)\s*%/)??1)/100,explanation:"指定行业涨跌幅达到阈值",required_data:["industry_prices"]}));
  if(/ETF.*重仓|重仓.*变化/.test(text))conditions.push(condition({type:"etf",name:"etf_holding_change",operator:"changes",params:{disclosure_period:"latest"},explanation:"ETF 最新披露重仓较上一期变化",required_data:["fund_disclosure"]}));
  if(/持仓|仓位|组合/.test(text)){const value=pct(text,/(?:持仓|仓位|占比)[^\d]{0,12}(\d+(?:\.\d+)?)\s*%/);conditions.push(condition({type:"portfolio",name:"portfolio_weight",operator:/低于|不超过/.test(text)?"<=":">=",params:{scope:"user_portfolio"},value:value===null?"unconfirmed":value/100,explanation:"用户持仓占比达到指定阈值",required_data:["user_portfolio"]}));if(value===null){missing.push("持仓占比阈值");questions.push("持仓占比达到多少时触发？");}}
  const english=!/[一-龥]/.test(text);
  if(!conditions.length){missing.push(english?"at least one computable condition":"至少一个可计算条件");questions.push(english?"Add a computable condition such as moving-average periods, an RSI threshold, a volume baseline or disclosure keywords.":"请补充一个可计算条件，例如均线周期、RSI 阈值、成交量比较基准或公告关键词。");}
  if(/均线|突破|moving average|cross/i.test(text)&&!/收盘|盘中|close|intraday/i.test(text)){missing.push(english?"signal confirmation time":"信号确认时点");questions.push(english?"Should the crossover be confirmed at the daily close or intraday?":"均线突破按每日收盘确认，还是盘中确认？");}
  const frequency=frequencyFrom(text);if(frequency==="manual"&&!/手动|manual/i.test(text)){missing.push(english?"run frequency":"运行频率");questions.push(english?"Should the strategy run after each close, weekly, monthly or manually only?":"策略按每日收盘后、每周、每月，还是只手动运行？");}
  const action=actionFrom(text);if(!/(提醒|通知|观察|自选|模拟|纸面|notify|alert|watch|simulate|paper)/i.test(text)){missing.push(english?"trigger action":"触发动作");questions.push(english?"When conditions are met, should the app notify you, add to a watchlist or run a paper simulation?":"条件满足后只提醒、加入观察，还是进行纸面模拟？");}
  if(frequency==="realtime")warnings.push("盘中监控需要已授权分钟行情；当前只有日线时必须降级为每日收盘后。");
  const asset=codeFrom(text);if(!asset){missing.push(english?"asset or universe":"标的或资产范围");questions.push(english?"Add a six-digit stock/ETF code or define the asset universe.":"请补充 6 位股票/ETF 代码或明确资产范围。");}
  const logic:StrategyLogic=/\bOR\b|或者|任一|满足其一/i.test(text)?"OR":"AND";const dsl:StrategyDSL={strategy_id:`strategy_${crypto.randomUUID().replaceAll("-","").slice(0,12)}`,market:"CN_A",asset_type:/ETF|基金/i.test(text)?"etf":asset==="000300"?"index":asset?"stock":"unknown",asset_universe:asset?[asset]:[],frequency,logic,conditions,action,execution_mode:"manual_confirmation",version:1};const validation=validateStrategyDSL(dsl,{missingInformation:missing});
  const dataSources=[...new Map(conditions.map(item=>sourceFor(item)).map(item=>[item.id,item])).values()];return {type:"strategy_preview",preview_id:`preview_${crypto.randomUUID().replaceAll("-","").slice(0,12)}`,name:`${asset||(english?"Asset to confirm":"待选标的")} · ${conditions[0]?.explanation||(english?"Custom strategy":"自定义策略")}`.slice(0,72),original_text:text,asset,frequency,conditions,logic,action,parameters:Object.assign({},...conditions.map(item=>item.params)),explanation:english?`When ${conditions.map(item=>item.explanation).join(logic==="AND"?", and ":", or ")}, ${action==="notify"?"create a notification":action==="watch"?"add it to the watchlist":"create a paper simulation awaiting confirmation"}.`:`当${conditions.map(item=>item.explanation).join(logic==="AND"?"，并且":"，或者")}时，${action==="notify"?"生成提醒":action==="watch"?"加入观察":"生成待确认纸面模拟"}。`,warnings:[...warnings,...validation.warnings],missing_information:[...new Set(missing)],questions:[...new Set(questions)].slice(0,5),data_sources:dataSources.map(item=>english?{...item,name:item.id==="daily_prices"?"A-share daily prices":item.id==="authorized_news"?"Authorized news and disclosures":item.id==="authorized_social"?"User-uploaded or authorized social samples":item.id==="financial_reports"?"Public financial reports and valuation data":item.id==="user_portfolio"?"Saved user portfolio":item.name}:item),dsl,validation,requires_confirmation:true,parser:"deterministic_fallback",created_at:new Date().toISOString()};
}

export function validateStrategyDSL(dsl:StrategyDSL,options:{missingInformation?:string[]}={}):StrategyValidation{const errors:string[]=[];const warnings:string[]=[];const fixes:string[]=[];const affected:string[]=[];if(dsl.market!=="CN_A")errors.push("当前版本仅支持 A 股市场");if(dsl.execution_mode!=="manual_confirmation")errors.push("执行模式必须是人工确认");if(!["notify","watch","paper_simulation"].includes(dsl.action))errors.push("触发动作不在白名单");if(!dsl.conditions.length)errors.push("至少需要一个条件");for(const item of dsl.conditions){if(!STRATEGY_INDICATORS.includes(item.name)){errors.push(`未知指标：${item.name}`);affected.push(item.id);}if(Object.values(item.params).some(value=>typeof value==="string"&&/(python|shell|eval|exec|import|__)/i.test(value))){errors.push("参数包含禁止执行的代码或函数");affected.push(item.id);}if(Object.values(item.params).includes("待确认")||item.value==="unconfirmed"){warnings.push(`${item.explanation}仍缺少明确参数`);affected.push(item.id);}}
  if(dsl.frequency==="realtime")warnings.push("盘中策略只有在分钟数据源已授权时才能启用，否则必须降级为日频");if(options.missingInformation?.length)warnings.push(`仍需确认：${options.missingInformation.join("、")}`);if(dsl.conditions.length>8)warnings.push("条件较多，存在过度拟合风险；建议逐项检查样本外稳定性");if(errors.length)fixes.push("删除未知字段或改用白名单指标");if(warnings.some(item=>item.includes("参数")))fixes.push("补齐阈值、比较基准和确认时点");const status=errors.length?"blocked":warnings.length?"warning":"pass";return {status,errors,warnings:[...new Set(warnings)],fixes,affected_conditions:[...new Set(affected)],allow_save:!errors.length&&!options.missingInformation?.length,allow_backtest:!errors.length&&dsl.conditions.every(item=>["moving_average_cross","rsi","macd","bollinger","volume_ratio","volatility","drawdown"].includes(item.name)),allow_monitor:!errors.length&&dsl.frequency!=="realtime"};}

const mean=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0;
const std=(values:number[])=>{const m=mean(values);return values.length<2?0:Math.sqrt(values.reduce((sum,value)=>sum+(value-m)**2,0)/(values.length-1));};
function rsi(values:number[],period:number){const changes=values.slice(-period-1).slice(1).map((value,index)=>value-values.slice(-period-1)[index]);const gain=mean(changes.map(value=>Math.max(0,value))),loss=mean(changes.map(value=>Math.max(0,-value)));return loss===0?100:100-100/(1+gain/loss);}
function evaluateCondition(item:StrategyCondition,points:PricePoint[]){const latest=points.at(-1),previous=points.at(-2);if(!latest||!previous)return {condition_id:item.id,met:false,actual_value:null,expected:item.explanation,status:"missing"};const close=points.map(row=>row.close);let actual:number|string|null=null,met=false;
  if(item.name==="moving_average_cross"){const short=Number(item.params.short_period),long=Number(item.params.long_period);if(points.length<long+1)return {condition_id:item.id,met:false,actual_value:null,expected:item.explanation,status:"missing"};const nowShort=mean(close.slice(-short)),nowLong=mean(close.slice(-long)),prevShort=mean(close.slice(-short-1,-1)),prevLong=mean(close.slice(-long-1,-1));actual=+(nowShort-nowLong).toFixed(4);met=item.operator==="cross_above"?prevShort<=prevLong&&nowShort>nowLong:prevShort>=prevLong&&nowShort<nowLong;}
  else if(item.name==="volume_ratio"){const reference=item.reference==="previous_day"?Number(previous.volume??0):mean(points.slice(-Number(item.params.window??20)-1,-1).map(row=>Number(row.volume??0)));actual=reference?Number(latest.volume??0)/reference:0;met=item.operator==="<"?actual<Number(item.value):actual>=Number(item.value);}
  else if(item.name==="rsi"){actual=rsi(close,Number(item.params.period??14));met=item.operator==="<"?actual<Number(item.value):actual>Number(item.value);}
  else if(item.name==="volatility"){const window=Number(item.params.window??20),returns=close.slice(-window-1).slice(1).map((value,index)=>value/close.slice(-window-1)[index]-1);actual=std(returns)*Math.sqrt(252);met=item.operator==="<="?actual<=Number(item.value):actual>=Number(item.value);}
  else if(item.name==="drawdown"){const window=Number(item.params.window??60),values=close.slice(-window),peak=Math.max(...values);actual=peak?latest.close/peak-1:0;met=item.operator==="<="?Math.abs(Number(actual))<=Number(item.value):Math.abs(Number(actual))>=Number(item.value);}
  else return {condition_id:item.id,met:false,actual_value:null,expected:item.explanation,status:"requires_external_data"};return {condition_id:item.id,met,actual_value:typeof actual==="number"?+actual.toFixed(4):actual,expected:item.explanation,status:"evaluated"};}

export function evaluateStrategy(dsl:StrategyDSL,points:PricePoint[]){const results=dsl.conditions.map(item=>evaluateCondition(item,points));const evaluated=results.filter(item=>item.status==="evaluated");const triggered=evaluated.length===results.length&&(dsl.logic==="AND"?evaluated.every(item=>item.met):evaluated.some(item=>item.met));return {triggered,conditions:results,actual_values:results.map(item=>({condition_id:item.condition_id,value:item.actual_value,status:item.status})),missing_conditions:results.filter(item=>item.status!=="evaluated").map(item=>item.condition_id)};}
