import {callAIProviderWithFallback,readProviderState} from "./ai-provider-catalog";
import {reliability,type ReliabilityState} from "./failure-control";
import {parseStrategyDeterministically,validateStrategyDSL,evaluateStrategy,type StrategyDSL,type StrategyPreview} from "./natural-language-strategy";
import {DEFAULT_BACKTEST_CONFIG,runBacktest,type BacktestConfig,type BacktestResult,type PricePoint} from "./quant-research";
import {readUserSnapshot,writeUserSnapshot,type UserSnapshot} from "./user-snapshot";

export type StrategySchedule={frequency:"manual"|"daily_close"|"weekly"|"monthly"|"event"|"realtime";run_at:string|null;timezone:"Asia/Shanghai";trigger_type:"schedule"|"event"|"manual";enabled:boolean;runner_status:"configured"|"unavailable"};
export type SavedNaturalStrategy={id:string;name:string;original_text:string;dsl:StrategyDSL;status:"active"|"paused";version:number;schedule:StrategySchedule;created_at:string;updated_at:string;last_run_at:string|null;last_success_at:string|null;failure_count:number;last_result:StrategyRun|null;reliability:ReliabilityState;versions:Array<{version:number;dsl:StrategyDSL;original_text:string;created_at:string}>;connected_to_broker:false;allow_order_submit:false};
export type StrategyRun={run_id:string;strategy_id:string;strategy_version:number;run_at:string;data_timestamp:string|null;conditions:ReturnType<typeof evaluateStrategy>["conditions"];actual_values:ReturnType<typeof evaluateStrategy>["actual_values"];triggered:boolean;action:string;warnings:string[];sources:Array<{name:string;timestamp:string|null;cached:boolean}>;current_portfolio_impact:{status:"not_calculated";message:string};requires_human_confirmation:true;status:"completed"|"failed";reliability:ReliabilityState};
export type StrategyNotification={notification_id:string;strategy_id:string;strategy_name:string;triggered_at:string;asset:string;conditions:string[];actual_values:StrategyRun["actual_values"];data_timestamp:string|null;sources:StrategyRun["sources"];portfolio_impact:StrategyRun["current_portfolio_impact"];risk_tags:string[];requires_human_confirmation:true;message:string;disclaimer:string};
type StrategyAudit={id:string;action:string;strategy_id:string|null;status:string;created_at:string;details?:Record<string,unknown>};
type StrategySnapshot=UserSnapshot&{strategyDrafts?:StrategyPreview[];naturalLanguageStrategies?:SavedNaturalStrategy[];strategyRuns?:StrategyRun[];strategyNotifications?:StrategyNotification[];strategyBacktestHistory?:Array<{id:string;strategy_id:string;created_at:string;result:BacktestResult}>;strategyAudit?:StrategyAudit[]};

const now=()=>new Date().toISOString();
const arrays=(snapshot:UserSnapshot)=>{const row=snapshot as StrategySnapshot;return {...snapshot,strategyDrafts:Array.isArray(row.strategyDrafts)?row.strategyDrafts:[],naturalLanguageStrategies:Array.isArray(row.naturalLanguageStrategies)?row.naturalLanguageStrategies:[],strategyRuns:Array.isArray(row.strategyRuns)?row.strategyRuns:[],strategyNotifications:Array.isArray(row.strategyNotifications)?row.strategyNotifications:[],strategyBacktestHistory:Array.isArray(row.strategyBacktestHistory)?row.strategyBacktestHistory:[],strategyAudit:Array.isArray(row.strategyAudit)?row.strategyAudit:[]} as StrategySnapshot;};
async function state(){const result=await readUserSnapshot();if(result.status==="unauthorized")throw new Error("请先登录");return arrays(result.status==="ready"?result.snapshot:{});}
const audit=(snapshot:StrategySnapshot,action:string,strategyId:string|null,status:string,details?:Record<string,unknown>)=>{snapshot.strategyAudit=[{id:`sa_${crypto.randomUUID()}`,action,strategy_id:strategyId,status,created_at:now(),details},...(snapshot.strategyAudit??[])].slice(0,500);};
function scheduleFor(dsl:StrategyDSL):StrategySchedule{const frequency=dsl.frequency==="daily_close"?"daily_close":dsl.frequency==="weekly"?"weekly":dsl.frequency==="monthly"?"monthly":dsl.frequency==="event"?"event":dsl.frequency==="realtime"?"realtime":"manual";return {frequency,run_at:frequency==="daily_close"?"18:00":null,timezone:"Asia/Shanghai",trigger_type:frequency==="event"?"event":frequency==="manual"?"manual":"schedule",enabled:frequency!=="manual",runner_status:"unavailable"};}

async function parseWithProvider(text:string){const base=parseStrategyDeterministically(text);try{const providerState=await readProviderState();const primary=providerState.providers.find(item=>item.isDefault&&item.enabled&&item.connectionStatus==="available"&&item.providerId!=="mock"&&item.capabilities.quantRule);if(!primary)return base;const candidates=[primary,...providerState.providers.filter(item=>item.providerId!==primary.providerId&&item.providerId!=="mock"&&item.enabled&&item.connectionStatus==="available"&&item.capabilities.quantRule)];const response=await callAIProviderWithFallback(candidates,[{role:"system",content:"你是 A 股策略语言规范化助手。只返回 JSON：{\"normalized_strategy\":\"...\"}。保留用户所有不确定性，不得补写阈值、标的、频率、确认时点、数据或收益。不得输出代码、公式或买卖建议。"},{role:"user",content:text.slice(0,3000)}],500);const normalized=JSON.parse(response.content.match(/\{[\s\S]*\}/)?.[0]??"{}")?.normalized_strategy;if(typeof normalized!=="string"||!normalized.trim())return base;const parsed=parseStrategyDeterministically(normalized);return {...parsed,original_text:text,parser:"ai_provider" as const,provider:response.provider,model:response.model,warnings:[...new Set([...parsed.warnings,...response.reliability.warnings])]};}catch{return base;}}

export async function previewNaturalStrategy(text:string,persist=true){const preview=await parseWithProvider(text);if(!persist)return preview;const snapshot=await state();snapshot.strategyDrafts=[preview,...(snapshot.strategyDrafts??[]).filter(item=>item.preview_id!==preview.preview_id)].slice(0,30);audit(snapshot,"preview_strategy",null,preview.validation.status,{preview_id:preview.preview_id,parser:preview.parser,missing:preview.missing_information});await writeUserSnapshot(snapshot);return preview;}
export async function listNaturalStrategies(){const snapshot=await state();return {strategies:snapshot.naturalLanguageStrategies,runs:snapshot.strategyRuns,notifications:snapshot.strategyNotifications,backtests:snapshot.strategyBacktestHistory,audit:snapshot.strategyAudit};}
export async function confirmNaturalStrategy(previewId:string,confirmed:boolean){if(!confirmed)throw new Error("保存策略前必须明确确认");const snapshot=await state();const preview=snapshot.strategyDrafts?.find(item=>item.preview_id===previewId);if(!preview)throw new Error("策略预览不存在或已经过期");if(!preview.validation.allow_save)throw new Error(`策略仍不能保存：${[...preview.validation.errors,...preview.missing_information].join("；")}`);const created=now();const schedule=scheduleFor(preview.dsl);const saved:SavedNaturalStrategy={id:preview.dsl.strategy_id,name:preview.name,original_text:preview.original_text,dsl:preview.dsl,status:"active",version:1,schedule,created_at:created,updated_at:created,last_run_at:null,last_success_at:null,failure_count:0,last_result:null,reliability:reliability({status:schedule.enabled&&schedule.runner_status==="unavailable"?"unavailable":"healthy",message:schedule.enabled&&schedule.runner_status==="unavailable"?"策略已保存；托管定时运行器尚未接入，可手动运行。":"策略已保存，可手动运行。",error_code:schedule.enabled&&schedule.runner_status==="unavailable"?"SCHEDULER_NOT_CONFIGURED":null,allow_signal:false}),versions:[{version:1,dsl:preview.dsl,original_text:preview.original_text,created_at:created}],connected_to_broker:false,allow_order_submit:false};snapshot.naturalLanguageStrategies=[saved,...(snapshot.naturalLanguageStrategies??[])];snapshot.strategyDrafts=(snapshot.strategyDrafts??[]).filter(item=>item.preview_id!==previewId);audit(snapshot,"confirm_strategy",saved.id,"saved",{version:1,schedule});await writeUserSnapshot(snapshot);return saved;}
export async function getNaturalStrategy(id:string){const snapshot=await state();const strategy=snapshot.naturalLanguageStrategies?.find(item=>item.id===id);if(!strategy)throw new Error("策略不存在");return {strategy,runs:(snapshot.strategyRuns??[]).filter(item=>item.strategy_id===id),notifications:(snapshot.strategyNotifications??[]).filter(item=>item.strategy_id===id),backtests:(snapshot.strategyBacktestHistory??[]).filter(item=>item.strategy_id===id),audit:(snapshot.strategyAudit??[]).filter(item=>item.strategy_id===id)};}

export async function updateNaturalStrategy(id:string,input:{name?:string;natural_language?:string;dsl?:StrategyDSL;confirmed?:boolean}){if(input.confirmed!==true)throw new Error("修改策略前必须明确确认");const snapshot=await state();const found=snapshot.naturalLanguageStrategies?.find(item=>item.id===id);if(!found)throw new Error("策略不存在");let dsl=found.dsl,original=found.original_text;if(input.natural_language?.trim()){const preview=await parseWithProvider(input.natural_language);if(!preview.validation.allow_save)throw new Error(`修改仍有未确认内容：${preview.missing_information.join("；")}`);dsl={...preview.dsl,strategy_id:found.id,version:found.version+1};original=input.natural_language;}else if(input.dsl){const validation=validateStrategyDSL(input.dsl);if(!validation.allow_save)throw new Error(`DSL 校验失败：${validation.errors.join("；")}`);dsl={...structuredClone(input.dsl),strategy_id:found.id,version:found.version+1};}
  found.name=input.name?.trim().slice(0,60)||found.name;found.original_text=original;found.dsl=dsl;found.version+=1;found.schedule=scheduleFor(dsl);found.updated_at=now();found.versions=[...found.versions,{version:found.version,dsl:structuredClone(dsl),original_text:original,created_at:found.updated_at}].slice(-30);found.reliability=reliability({status:found.schedule.enabled&&found.schedule.runner_status==="unavailable"?"unavailable":"healthy",message:"策略已更新；下次运行使用新版本。",allow_signal:false});audit(snapshot,"update_strategy",id,"saved",{version:found.version});await writeUserSnapshot(snapshot);return found;}
export async function deleteNaturalStrategy(id:string,confirmed:boolean){if(!confirmed)throw new Error("删除策略前必须明确确认");const snapshot=await state();const before=snapshot.naturalLanguageStrategies?.length??0;snapshot.naturalLanguageStrategies=(snapshot.naturalLanguageStrategies??[]).filter(item=>item.id!==id);if(snapshot.naturalLanguageStrategies.length===before)throw new Error("策略不存在");audit(snapshot,"delete_strategy",id,"deleted");await writeUserSnapshot(snapshot);return {status:"deleted",strategy_id:id};}
export async function copyNaturalStrategy(id:string,confirmed:boolean){if(!confirmed)throw new Error("复制策略前必须明确确认");const snapshot=await state();const source=snapshot.naturalLanguageStrategies?.find(item=>item.id===id);if(!source)throw new Error("策略不存在");const created=now(),newId=`strategy_${crypto.randomUUID().replaceAll("-","").slice(0,12)}`;const copy:SavedNaturalStrategy={...structuredClone(source),id:newId,name:`${source.name} 副本`,dsl:{...structuredClone(source.dsl),strategy_id:newId,version:1},version:1,created_at:created,updated_at:created,last_run_at:null,last_success_at:null,last_result:null,failure_count:0,versions:[{version:1,dsl:{...structuredClone(source.dsl),strategy_id:newId,version:1},original_text:source.original_text,created_at:created}]};snapshot.naturalLanguageStrategies=[copy,...(snapshot.naturalLanguageStrategies??[])];audit(snapshot,"copy_strategy",copy.id,"saved",{source_id:id});await writeUserSnapshot(snapshot);return copy;}
export async function changeNaturalStrategyStatus(id:string,status:"paused"|"active"){const snapshot=await state();const found=snapshot.naturalLanguageStrategies?.find(item=>item.id===id);if(!found)throw new Error("策略不存在");found.status=status;found.schedule.enabled=status==="active"&&found.schedule.frequency!=="manual";found.updated_at=now();found.reliability=reliability({status:status==="paused"?"blocked":found.schedule.runner_status==="unavailable"&&found.schedule.enabled?"unavailable":"healthy",message:status==="paused"?"策略已暂停，不会生成新提醒。":found.schedule.runner_status==="unavailable"&&found.schedule.enabled?"策略已恢复；定时运行器未接入，仍需手动运行。":"策略已恢复。",allow_signal:false});audit(snapshot,status==="paused"?"pause_strategy":"resume_strategy",id,status);await writeUserSnapshot(snapshot);return found;}

function backtestConfig(strategy:SavedNaturalStrategy,input?:Partial<BacktestConfig>):Partial<BacktestConfig>{return {...DEFAULT_BACKTEST_CONFIG,symbol:strategy.dsl.asset_universe[0]??"",strategyId:"dsl_strategy",dataFrequency:strategy.dsl.frequency==="weekly"?"weekly":strategy.dsl.frequency==="monthly"?"monthly":"daily_close",parameters:{dsl_json:JSON.stringify(strategy.dsl)},...input};}
export async function backtestNaturalStrategy(id:string,input:{prices?:PricePoint[];config?:Partial<BacktestConfig>;dataReliability?:ReliabilityState}){const snapshot=await state();const strategy=snapshot.naturalLanguageStrategies?.find(item=>item.id===id);if(!strategy)throw new Error("策略不存在");const validation=validateStrategyDSL(strategy.dsl);if(!validation.allow_backtest)throw new Error("该策略依赖财报、事件或社交历史数据，当前不能用价格序列伪造回测");const result=runBacktest(input.prices??[],backtestConfig(strategy,input.config),input.dataReliability);const idValue=`strategy_backtest_${crypto.randomUUID()}`;snapshot.strategyBacktestHistory=[{id:idValue,strategy_id:id,created_at:now(),result},...(snapshot.strategyBacktestHistory??[])].slice(0,100);audit(snapshot,"backtest_strategy",id,result.reliability.status,{backtest_id:idValue,credibility:result.credibility.score,allow_signal:result.reliability.allow_signal});await writeUserSnapshot(snapshot);return {backtest_id:idValue,strategy_id:id,trigger_count:result.trades.filter(item=>item.action==="enter"&&item.execution_status!=="skipped").length,average_return_pct:result.metrics&&result.metrics.tradeCount?+(result.metrics.totalReturnPct/Math.max(1,result.metrics.tradeCount/2)).toFixed(2):null,result,data_quality_report:result.credibility.data_quality,risk_warnings:result.warnings};}

export async function runNaturalStrategy(id:string,input:{prices?:PricePoint[];source?:string;data_timestamp?:string|null;cached?:boolean}){const snapshot=await state();const strategy=snapshot.naturalLanguageStrategies?.find(item=>item.id===id);if(!strategy)throw new Error("策略不存在");if(strategy.status==="paused")throw new Error("策略已暂停");const prices=Array.isArray(input.prices)?input.prices:[];const evaluated=evaluateStrategy(strategy.dsl,prices);const runAt=now(),dataTimestamp=input.data_timestamp??prices.at(-1)?.date??null;const incomplete=evaluated.missing_conditions.length>0;const run:StrategyRun={run_id:`strategy_run_${crypto.randomUUID()}`,strategy_id:id,strategy_version:strategy.version,run_at:runAt,data_timestamp:dataTimestamp,conditions:evaluated.conditions,actual_values:evaluated.actual_values,triggered:evaluated.triggered&&!incomplete,action:strategy.dsl.action,warnings:incomplete?["部分条件缺少已授权历史数据；未生成新提醒"]:[],sources:[{name:input.source??"用户提供或已授权行情",timestamp:dataTimestamp,cached:Boolean(input.cached)}],current_portfolio_impact:{status:"not_calculated",message:"本次未提供可匹配的当前持仓，未计算组合影响。"},requires_human_confirmation:true,status:incomplete?"failed":"completed",reliability:reliability({status:incomplete?"failed":input.cached?"stale":"healthy",last_success_at:incomplete?strategy.last_success_at:runAt,data_timestamp:dataTimestamp,error_code:incomplete?"STRATEGY_DATA_MISSING":input.cached?"CACHED_DATA_USED":null,message:incomplete?"策略运行不完整，已阻断新提醒。":input.cached?"使用缓存数据完成核验；不称为实时结果。":"策略运行完成。",warnings:incomplete?["不会使用缺失数据推断条件"]:[],retryable:incomplete,allow_signal:!incomplete&&!input.cached})};snapshot.strategyRuns=[run,...(snapshot.strategyRuns??[])].slice(0,500);strategy.last_run_at=runAt;strategy.last_result=run;if(incomplete){strategy.failure_count+=1;if(strategy.failure_count>=3){strategy.status="paused";strategy.schedule.enabled=false;run.warnings.push("连续失败 3 次，策略已自动暂停");}}else{strategy.failure_count=0;strategy.last_success_at=runAt;}strategy.reliability=run.reliability;
  if(input.cached){run.triggered=false;run.warnings.push("当前使用缓存数据，不生成新的策略提醒");}
  let notification:StrategyNotification|null=null;if(run.triggered&&run.reliability.allow_signal){notification={notification_id:`notification_${crypto.randomUUID()}`,strategy_id:id,strategy_name:strategy.name,triggered_at:runAt,asset:strategy.dsl.asset_universe.join("、")||"未指定",conditions:strategy.dsl.conditions.filter((_,index)=>run.conditions[index]?.met).map(item=>item.explanation),actual_values:run.actual_values,data_timestamp:dataTimestamp,sources:run.sources,portfolio_impact:run.current_portfolio_impact,risk_tags:[strategy.dsl.action==="paper_simulation"?"仅纸面模拟":"仅提醒"],requires_human_confirmation:true,message:`你的“${strategy.name}”策略条件已满足。该结果只表示规则条件满足，需要你查看数据和风险后手动确认。`,disclaimer:"策略触发不构成投资建议、收益承诺或买卖依据。"};snapshot.strategyNotifications=[notification,...(snapshot.strategyNotifications??[])].slice(0,300);}audit(snapshot,"run_strategy",id,run.status,{run_id:run.run_id,triggered:run.triggered,notification_id:notification?.notification_id??null});await writeUserSnapshot(snapshot);return {run,notification,strategy_status:strategy.status};}
