import {readUserSnapshot,writeUserSnapshot,type UserSnapshot} from "./user-snapshot";
import {callAIProviderWithFallback,readProviderState} from "./ai-provider-catalog";
import {reliability,type ReliabilityState} from "./failure-control";
import {applyDashboard,dashboardState} from "./dashboard-server";
import type {DashboardPatchChange} from "./dashboard-system";
import {QUANT_MODULES,QUANT_TO_DASHBOARD_MODULE,STRATEGY_REGISTRY,createQuantTask,extractQuantGoal,nextRun,runBacktest,signalFromBacktest,validateFrequency,type BacktestConfig,type PaperPortfolio,type PaperPosition,type PricePoint,type QuantAuditEntry,type QuantFrequency,type QuantGoalExtraction,type QuantSchedule,type QuantSignal,type QuantTask,type QuantRule} from "./quant-research";

export type SavedQuantStrategy={id:string;name:string;definitionId:string;parameters:Record<string,unknown>;rules:QuantRule[];frequency:QuantFrequency;version:number;confirmedAt:string;createdAt:string;updatedAt:string};
type QuantSnapshot=UserSnapshot&{quantTasks?:QuantTask[];quantStrategies?:SavedQuantStrategy[];quantSchedules?:QuantSchedule[];quantSignals?:QuantSignal[];quantAudit?:QuantAuditEntry[];quantPaperPortfolios?:PaperPortfolio[];quantBacktests?:Array<{taskId:string;result:ReturnType<typeof runBacktest>;createdAt:string}>};
const arrays=(snapshot:UserSnapshot):QuantSnapshot=>({...snapshot,quantTasks:Array.isArray(snapshot.quantTasks)?snapshot.quantTasks as QuantTask[]:[],quantStrategies:Array.isArray(snapshot.quantStrategies)?snapshot.quantStrategies as SavedQuantStrategy[]:[],quantSchedules:Array.isArray(snapshot.quantSchedules)?(snapshot.quantSchedules as QuantSchedule[]).map(item=>({...item,failureCount:item.failureCount??0,lastSuccessAt:item.lastSuccessAt??null,lastFailureAt:item.lastFailureAt??null,failureReason:item.failureReason??null,reliability:item.reliability??reliability({status:item.runnerStatus==="configured"?"degraded":"unavailable",message:item.runnerStatus==="configured"?"等待下一次运行":"定时运行器尚未接入",error_code:item.runnerStatus==="configured"?null:"SCHEDULER_NOT_CONFIGURED",allow_signal:false})})):[],quantSignals:Array.isArray(snapshot.quantSignals)?snapshot.quantSignals as QuantSignal[]:[],quantAudit:Array.isArray(snapshot.quantAudit)?snapshot.quantAudit as QuantAuditEntry[]:[],quantPaperPortfolios:Array.isArray(snapshot.quantPaperPortfolios)?snapshot.quantPaperPortfolios as PaperPortfolio[]:[],quantBacktests:Array.isArray(snapshot.quantBacktests)?snapshot.quantBacktests as QuantSnapshot["quantBacktests"]:[]});
async function state(){const saved=await readUserSnapshot();if(saved.status==="unauthorized")throw new Error("请先登录");return arrays(saved.status==="ready"?saved.snapshot:{});}
const audit=(action:string,targetId:string,status:string,details?:Record<string,unknown>,model?:string):QuantAuditEntry=>({id:`qa-${crypto.randomUUID()}`,action,targetId,status,source:"anxin_quant_workspace",model,createdAt:new Date().toISOString(),details});
const pushAudit=(snapshot:QuantSnapshot,item:QuantAuditEntry)=>{snapshot.quantAudit=[item,...(snapshot.quantAudit??[])].slice(0,500);};

function safeAIExtraction(raw:unknown,base:QuantGoalExtraction):Partial<QuantGoalExtraction>{
  if(!raw||typeof raw!=="object")return {};const value=raw as Record<string,unknown>;const strategyIds=Array.isArray(value.strategyIds)?value.strategyIds.filter((id):id is string=>typeof id==="string"&&STRATEGY_REGISTRY.some(item=>item.id===id)).slice(0,6):base.strategyIds;
  const assets=Array.isArray(value.assets)?value.assets.filter((item):item is string=>typeof item==="string").map(item=>item.slice(0,40)).slice(0,20):base.assets;
  const allowedFrequency=new Set<QuantFrequency>(["realtime","5m","15m","30m","hourly","daily_close","weekly","monthly","event","manual"]);const requested=allowedFrequency.has(value.frequency as QuantFrequency)?value.frequency as QuantFrequency:base.frequency;
  const modules=Array.isArray(value.modules)?value.modules.filter((item):item is QuantGoalExtraction["modules"][number]=>typeof item==="string"&&(QUANT_MODULES as readonly string[]).includes(item)).slice(0,15):base.modules;
  return {assets,strategyIds,modules,missingInformation:Array.isArray(value.missingInformation)?value.missingInformation.filter((item):item is string=>typeof item==="string").slice(0,5):base.missingInformation,warnings:base.warnings,frequency:requested};
}

async function planGoal(goal:string){
  const base=extractQuantGoal(goal);let model:string|undefined,providerName:string|undefined;
  try{const providerState=await readProviderState();const primary=providerState.providers.find(item=>item.isDefault&&item.enabled&&item.connectionStatus==="available"&&item.providerId!=="mock"&&item.capabilities.quantRule);if(!primary)return base;const candidates=[primary,...providerState.providers.filter(item=>item.providerId!==primary.providerId&&item.enabled&&item.connectionStatus==="available"&&item.providerId!=="mock"&&item.capabilities.quantRule)];
    const ai=await callAIProviderWithFallback(candidates,[{role:"system",content:"你是量化研究配置规划器，只返回 JSON。不得生成行情、收益、社媒热度或买卖指令。只能从给出的策略和模块 ID 中选择。字段：assets,frequency,strategyIds,modules,missingInformation。信息不足时列出缺失项，不得自行假设。"},{role:"user",content:JSON.stringify({goal,allowedStrategies:STRATEGY_REGISTRY.map(item=>({id:item.id,name:item.name,frequencies:item.supportedFrequencies,requiredData:item.requiredData})),allowedModules:QUANT_MODULES})}],650);const content=ai.content;
    const json=content.match(/\{[\s\S]*\}/)?.[0];if(!json)throw new Error("模型未返回结构化配置");const patch=safeAIExtraction(JSON.parse(json),base);model=ai.model;providerName=ai.provider;
    const merged={...base,...patch,planner:"ai_provider" as const,provider:providerName,model};const selected=merged.strategyIds.map(id=>STRATEGY_REGISTRY.find(item=>item.id===id)).filter(Boolean);merged.dataRequirements=[...new Set(selected.flatMap(item=>item?.requiredData??[]))];merged.strategyCandidates=selected.map(item=>({id:item!.id,name:item!.name,logic:item!.logic,risk:item!.riskLevel,frequency:item!.defaultFrequency,limitations:item!.limitations}));return merged;
  }catch{return {...base,planner:"local_fallback" as const,provider:providerName,model};}
}

export async function listQuantState(){const snapshot=await state();let provider={name:"本地规则模式",model:"rules-v1",status:"available"};try{const result=await readProviderState();const selected=result.providers.find(item=>item.isDefault);if(selected)provider={name:selected.displayName,model:selected.model,status:selected.connectionStatus};}catch{}return {tasks:snapshot.quantTasks,strategies:snapshot.quantStrategies,schedules:snapshot.quantSchedules,signals:snapshot.quantSignals,paperPortfolios:snapshot.quantPaperPortfolios,backtests:snapshot.quantBacktests,audit:snapshot.quantAudit,registry:STRATEGY_REGISTRY,provider,data_status:"用户配置已从云端个人空间读取"};}
export async function saveNewQuantTask(goal:string){const snapshot=await state();const extraction=await planGoal(goal);const task=createQuantTask(goal,extraction);snapshot.quantTasks=[task,...(snapshot.quantTasks??[])].slice(0,100);pushAudit(snapshot,audit("create_task",task.id,"awaiting_confirmation",{goal,planner:task.extraction.planner,dataRequirements:task.extraction.dataRequirements},task.extraction.model));await writeUserSnapshot(snapshot);return task;}
export async function getQuantTask(id:string){const snapshot=await state();const task=snapshot.quantTasks?.find(item=>item.id===id);if(!task)throw new Error("未找到量化任务");return task;}
export async function reviseQuantTask(id:string,input:{strategyId?:string;frequency?:QuantFrequency;assets?:string[];maxDrawdownPct?:number}){const snapshot=await state();const task=snapshot.quantTasks?.find(item=>item.id===id);if(!task)throw new Error("未找到量化任务");if(task.confirmedAt)throw new Error("配置已确认；请复制任务后再修改");if(input.strategyId){const definition=STRATEGY_REGISTRY.find(item=>item.id===input.strategyId);if(!definition)throw new Error("策略不存在");task.extraction.strategyIds=[definition.id];task.extraction.strategyCandidates=[{id:definition.id,name:definition.name,logic:definition.logic,risk:definition.riskLevel,frequency:definition.defaultFrequency,limitations:definition.limitations}];task.extraction.dataRequirements=definition.requiredData;}
  if(input.frequency){const checked=validateFrequency(input.frequency,task.extraction.market,"daily");task.extraction.frequency=checked.effective;task.extraction.frequencyConfig={...task.extraction.frequencyConfig,frequency:checked.effective,runAt:checked.effective==="daily_close"?"18:00":null,triggerType:checked.effective==="manual"?"manual":checked.effective==="event"?"event":"schedule"};task.extraction.warnings=[...new Set([...task.extraction.warnings,...checked.warnings])];}
  if(Array.isArray(input.assets))task.extraction.assets=input.assets.filter(item=>typeof item==="string"&&item.trim()).map(item=>item.trim().slice(0,40)).slice(0,20);if(Number.isFinite(input.maxDrawdownPct))task.extraction.riskConstraints=[`最大回撤提醒 ${Math.max(1,Math.min(80,Number(input.maxDrawdownPct)))}%`];task.updatedAt=new Date().toISOString();pushAudit(snapshot,audit("revise_task",task.id,"preview_updated",{strategyId:task.extraction.strategyIds[0],frequency:task.extraction.frequency}));await writeUserSnapshot(snapshot);return task;}
export async function updateQuantTask(id:string,action:"confirm"|"cancel"|"retry"){const snapshot=await state();const task=snapshot.quantTasks?.find(item=>item.id===id);if(!task)throw new Error("未找到量化任务");if(action==="confirm"){task.status="ready";task.confirmedAt=new Date().toISOString();task.reliability=reliability({status:"healthy",message:"配置已确认，等待读取数据。",allow_signal:false});}if(action==="cancel"){task.status="cancelled";task.reliability=reliability({status:"cancelled",message:"任务已由用户取消。",allow_signal:false});}if(action==="retry"){task.status="ready";delete task.error;task.reliability=reliability({status:"retrying",message:"仅重试失败步骤；已完成步骤不会重复执行。",retryable:true,allow_signal:false});}task.updatedAt=new Date().toISOString();pushAudit(snapshot,audit(action,task.id,task.status,{confirmedAt:task.confirmedAt,reliability:task.reliability}));await writeUserSnapshot(snapshot);return task;}

export async function saveStrategy(input:{name?:string;definitionId?:string;parameters?:Record<string,unknown>;rules?:QuantRule[];frequency?:QuantFrequency;confirmed?:boolean}){if(input.confirmed!==true)throw new Error("保存策略前必须明确确认");const snapshot=await state();const definition=STRATEGY_REGISTRY.find(item=>item.id===input.definitionId);if(!definition)throw new Error("策略定义不存在");const now=new Date().toISOString();const saved:SavedQuantStrategy={id:`qs-${crypto.randomUUID()}`,name:input.name?.trim()||definition.name,definitionId:definition.id,parameters:{...definition.parameters,...input.parameters},rules:Array.isArray(input.rules)?input.rules.slice(0,20):[],frequency:input.frequency??definition.defaultFrequency,version:1,confirmedAt:now,createdAt:now,updatedAt:now};snapshot.quantStrategies=[saved,...(snapshot.quantStrategies??[])].slice(0,100);pushAudit(snapshot,audit("save_strategy",saved.id,"saved",{definitionId:saved.definitionId,version:1}));await writeUserSnapshot(snapshot);return saved;}
export async function updateStrategy(id:string,input:{name?:string;parameters?:Record<string,unknown>;rules?:QuantRule[];frequency?:QuantFrequency;confirmed?:boolean}){if(input.confirmed!==true)throw new Error("修改策略前必须明确确认");const snapshot=await state();const found=snapshot.quantStrategies?.find(item=>item.id===id);if(!found)throw new Error("未找到策略");if(input.name?.trim())found.name=input.name.trim();if(input.parameters)found.parameters={...found.parameters,...input.parameters};if(Array.isArray(input.rules))found.rules=input.rules.slice(0,20);if(input.frequency)found.frequency=input.frequency;found.version+=1;found.updatedAt=new Date().toISOString();pushAudit(snapshot,audit("update_strategy",id,"saved",{version:found.version}));await writeUserSnapshot(snapshot);return found;}
export async function copyStrategy(id:string,confirmed:boolean){if(!confirmed)throw new Error("复制策略前必须明确确认");const snapshot=await state();const found=snapshot.quantStrategies?.find(item=>item.id===id);if(!found)throw new Error("未找到策略");const now=new Date().toISOString();const copy={...structuredClone(found),id:`qs-${crypto.randomUUID()}`,name:`${found.name} 副本`,version:1,confirmedAt:now,createdAt:now,updatedAt:now};snapshot.quantStrategies=[copy,...(snapshot.quantStrategies??[])];pushAudit(snapshot,audit("copy_strategy",copy.id,"saved",{sourceId:id}));await writeUserSnapshot(snapshot);return copy;}
export async function deleteStrategy(id:string,confirmed:boolean){if(!confirmed)throw new Error("删除策略前必须明确确认");const snapshot=await state();const before=snapshot.quantStrategies?.length??0;snapshot.quantStrategies=(snapshot.quantStrategies??[]).filter(item=>item.id!==id);if(snapshot.quantStrategies.length===before)throw new Error("未找到策略");pushAudit(snapshot,audit("delete_strategy",id,"deleted"));await writeUserSnapshot(snapshot);return {status:"deleted",id};}

export async function backtestTask(input:{taskId?:string;prices?:PricePoint[];config?:Partial<BacktestConfig>;costBps?:number;dataReliability?:ReliabilityState}){const snapshot=await state();const task=snapshot.quantTasks?.find(item=>item.id===input.taskId);if(input.taskId&&!task)throw new Error("未找到量化任务");if(task&&!task.confirmedAt)throw new Error("运行历史模拟前必须确认任务配置");const definitionId=input.config?.strategyId??task?.extraction.strategyIds[0]??"ma_trend";const definition=STRATEGY_REGISTRY.find(item=>item.id===definitionId);const legacyCost=input.costBps??13;const config={symbol:task?.extraction.assets[0]??"",strategyId:definitionId,dataFrequency:task?.extraction.frequency??"daily_close",commissionBps:Math.max(0,legacyCost-10),stampTaxBps:5,slippageBps:5,parameters:definition?.parameters??{},...input.config};const result=runBacktest(input.prices??[],config,input.dataReliability);pushAudit(snapshot,audit("run_backtest",input.taskId??"ad_hoc",result.reliability.status,{dataStatus:result.dataStatus,points:input.prices?.length??0,config:result.config,engineVersion:result.audit.engineVersion,reliability:result.reliability}));
  if(result.status==="ready"&&task){const signal=signalFromBacktest(task,result);if(signal)snapshot.quantSignals=[signal,...(snapshot.quantSignals??[])].slice(0,300);snapshot.quantBacktests=[{taskId:task.id,result,createdAt:new Date().toISOString()},...(snapshot.quantBacktests??[])].slice(0,50);}
  if(task){task.status=result.status==="ready"?"completed":"failed";task.reliability=result.reliability;task.error=result.status!=="ready"?result.dataStatus:undefined;task.updatedAt=new Date().toISOString();task.plan=task.plan.map(item=>item.tool==="run_quant_backtest"?{...item,status:result.status==="ready"?"completed":"failed"}:item);}await writeUserSnapshot(snapshot);return result;}

export async function savePaperRun(input:{taskId?:string;name?:string;initialCapital?:number;cash?:number;positions?:PaperPosition[];maxSingleWeightPct?:number;maxSectorWeightPct?:number;maxDrawdownPausePct?:number;confirmed?:boolean}){if(input.confirmed!==true)throw new Error("创建模拟组合前必须明确确认");const snapshot=await state();const capital=Math.max(1000,Number(input.initialCapital??100000));const positions=(Array.isArray(input.positions)?input.positions:[]).filter(item=>item&&typeof item.symbol==="string"&&Number(item.quantity)>=0&&Number(item.price)>=0).slice(0,100);const now=new Date().toISOString();const paper:PaperPortfolio={id:`paper-${crypto.randomUUID()}`,taskId:input.taskId??null,name:input.name?.trim()||"模拟组合",initialCapital:capital,cash:Math.max(0,Number(input.cash??capital)),positions,maxSingleWeightPct:Math.min(100,Math.max(1,Number(input.maxSingleWeightPct??30))),maxSectorWeightPct:Math.min(100,Math.max(1,Number(input.maxSectorWeightPct??50))),maxDrawdownPausePct:Math.min(100,Math.max(1,Number(input.maxDrawdownPausePct??20))),accountType:"paper",connectedToBroker:false,confirmedAt:now,createdAt:now};snapshot.quantPaperPortfolios=[paper,...(snapshot.quantPaperPortfolios??[])].slice(0,50);pushAudit(snapshot,audit("create_paper_portfolio",paper.id,"saved",{accountType:"paper",connectedToBroker:false}));await writeUserSnapshot(snapshot);return paper;}

export async function createSchedule(input:{taskId?:string;name?:string;frequency?:QuantFrequency;dataSchedules?:Record<string,QuantFrequency>;runAt?:string|null;confirmed?:boolean}){if(input.confirmed!==true)throw new Error("创建计划前必须明确确认");const snapshot=await state();const task=snapshot.quantTasks?.find(item=>item.id===input.taskId);if(!task)throw new Error("未找到量化任务");const frequency=input.frequency??task.extraction.frequency;const schedule:QuantSchedule={id:`schedule-${crypto.randomUUID()}`,taskId:task.id,name:input.name?.trim()||`${task.goal.slice(0,24)} · 定期研究`,frequency,dataSchedules:input.dataSchedules??task.extraction.dataFrequencies,timezone:"Asia/Shanghai",runAt:input.runAt??task.extraction.frequencyConfig.runAt,status:"active",nextRunAt:nextRun(frequency),runnerStatus:"unavailable",failureCount:0,lastSuccessAt:null,lastFailureAt:null,failureReason:null,reliability:reliability({status:"unavailable",message:"定时运行器尚未接入；计划已保存但不会假装执行。",error_code:"SCHEDULER_NOT_CONFIGURED",allow_signal:false}),createdAt:new Date().toISOString()};snapshot.quantSchedules=[schedule,...(snapshot.quantSchedules??[])].slice(0,100);pushAudit(snapshot,audit("create_schedule",schedule.id,"unavailable",{runnerStatus:schedule.runnerStatus,dataSchedules:schedule.dataSchedules,reliability:schedule.reliability}));await writeUserSnapshot(snapshot);return schedule;}
export async function changeSchedule(id:string,action:"pause"|"resume"|"delete"){const snapshot=await state();const found=snapshot.quantSchedules?.find(item=>item.id===id);if(!found)throw new Error("未找到计划");if(action==="delete")snapshot.quantSchedules=(snapshot.quantSchedules??[]).filter(item=>item.id!==id);else{found.status=action==="pause"?"paused":"active";found.nextRunAt=found.status==="active"?nextRun(found.frequency):null;found.reliability=reliability({status:action==="pause"?"blocked":found.runnerStatus==="configured"?"healthy":"unavailable",message:action==="pause"?"计划已暂停。":found.runnerStatus==="configured"?"计划已恢复。":"计划已恢复，但运行器仍未接入。",error_code:found.runnerStatus==="configured"?null:"SCHEDULER_NOT_CONFIGURED",allow_signal:false});}pushAudit(snapshot,audit(`${action}_schedule`,id,action,{reliability:action==="delete"?null:found.reliability}));await writeUserSnapshot(snapshot);return action==="delete"?{status:"deleted",id}:found;}

export async function recordScheduleRun(id:string,input:{success:boolean;errorCode?:string;message?:string}){const snapshot=await state();const found=snapshot.quantSchedules?.find(item=>item.id===id);if(!found)throw new Error("未找到计划");const now=new Date().toISOString();if(input.success){found.failureCount=0;found.lastSuccessAt=now;found.failureReason=null;found.nextRunAt=nextRun(found.frequency);found.reliability=reliability({status:"healthy",message:"最近一次计划运行成功。",last_success_at:now,data_timestamp:now,allow_signal:true});}else{found.failureCount=(found.failureCount??0)+1;found.lastFailureAt=now;found.failureReason=input.message??"计划运行失败";const paused=found.failureCount>=3;if(paused){found.status="paused";found.nextRunAt=null;}found.reliability=reliability({status:paused?"blocked":"failed",message:paused?"计划连续失败 3 次，已自动暂停。":found.failureReason,error_code:input.errorCode??"SCHEDULE_RUN_FAILED",retryable:!paused,allow_signal:false,warnings:["保留上次成功结果，但不会生成新的研究信号"]});}pushAudit(snapshot,audit("schedule_run",id,found.reliability.status,{failureCount:found.failureCount,lastSuccessAt:found.lastSuccessAt,lastFailureAt:found.lastFailureAt,paused:found.status==="paused"}));await writeUserSnapshot(snapshot);return found;}

export async function previewQuantWorkspace(taskId:string){const snapshot=await state();const task=snapshot.quantTasks?.find(item=>item.id===taskId);if(!task)throw new Error("未找到量化任务");const dashboard=await dashboardState();const existing=new Set(dashboard.workspace.modules.map(item=>item.type));const changes:DashboardPatchChange[]=task.extraction.modules.map(item=>QUANT_TO_DASHBOARD_MODULE[item]).filter((item):item is keyof typeof import("./personal-workbench").MODULE_LABELS=>!existing.has(item as never)).map((moduleId,index)=>({action:"add_module",moduleId,position:{x:index%2?6:0,y:dashboard.workspace.modules.length*3+Math.floor(index/2)*3,w:index<2?12:6,h:3}}));return {task,patch:{workspaceId:dashboard.workspace.id,baseVersion:dashboard.workspace.version,changes,summary:`把 ${changes.length} 个量化研究模块加入“${dashboard.workspace.name}”`,requiresConfirmation:true as const}};}
export async function applyQuantWorkspace(taskId:string,confirmed:boolean){if(!confirmed)throw new Error("应用工作台修改前必须明确确认");const {task,patch}=await previewQuantWorkspace(taskId);const workspace=await applyDashboard(patch.workspaceId,patch,true,"agent");const snapshot=await state();pushAudit(snapshot,audit("apply_quant_workspace",task.id,"applied",{workspaceId:workspace.id,moduleCount:patch.changes.length,workspaceVersion:workspace.version}));await writeUserSnapshot(snapshot);return {workspace,patch,canUndo:true};}
