"use client";

import { useEffect, useState } from "react";
import { Bot, Check, CircleAlert, Clock3, Database, Download, ListChecks, LoaderCircle, Play, RefreshCw, RotateCcw, ShieldCheck, Sparkles, Square, Wrench } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { pick, useI18n } from "@/app/i18n";

type Reliability={status:string;message:string;error_code?:string|null;warnings:string[];retryable:boolean;allow_signal:boolean;allow_trade:boolean;fallback_used?:string|null};
type InputField={id:string;label:string;question:string;type:"choice"|"text";options?:string[];required:true};
type MiniWorkspace={name:string;modules:Array<{type:string;visible:boolean;order:number;width:"full"|"half"|"third"}>;workflow:string[]};
type Task={task_id:string;goal:string;status:string;created_at:string;provider:string;model:string;planner_mode:string;reliability?:Reliability;extraction:{user_stage:string;data_requirements:string[];analysis_requirements:string[];ui_requirements:string[];workflow_requirements:string[];missing_information:string[];risk_level:string};steps:Array<{id:string;title:string;tool:string|null;status:string;requires_confirmation:boolean}>;tool_calls:Array<{tool_id:string;status:string;error?:string;output?:unknown;reliability?:Reliability;sources:Array<{name:string;collected_at:string;sample_scope:string;status:string}>}>;workspace_before?:MiniWorkspace;workspace_patch?:{summary:string;changes:string[];questions:string[];warnings:string[];affectedModules:string[];preview?:MiniWorkspace}|null;theme_schema?:{name:string;mode:string;density:string;motion:string;colors:Record<string,string>;accessibility:{high_contrast:boolean;reduced_motion:boolean}};input_request?:{title:string;description:string;fields:InputField[]};input_answers?:Record<string,string>;continuation_count?:number;result:unknown;warnings:string[];sources:Array<{source_id:string;name:string;collected_at:string;sample_scope:string;status:string}>;tool_proposal?:{name:string;purpose:string;inputs:string[];outputs:string[];risks:string[]};requires_confirmation:boolean};
type Provider={providerId:string;displayName:string;model?:string;enabled:boolean;connectionStatus?:string;secretStatus?:string};
const providerDisplay=(value:Provider,isEnglish:boolean)=>{
  if(!isEnglish)return value.displayName;
  const known:Record<string,string>={mock:"Local rules mode",platform_open_source:"Built-in model",ollama:"Ollama local model",vllm:"vLLM inference service",llamacpp:"llama.cpp local model",custom:"Custom compatible endpoint"};
  return known[value.providerId]??(value.displayName.startsWith("我的 ")?`My ${value.displayName.slice(3)}`:value.displayName);
};

const examplesZh=["分析我的 ETF 持仓，找出重复暴露，并把风险模块放到首页。","我是新手，帮我建立一个学习和模拟投资工作台。","我经常被社交平台影响，增加一个内容风险分析流程。","把当前页面改成科技感浅色主题，并减少红绿颜色。"];
const examplesEn=["Analyze my ETF holdings, find overlapping exposure, and add the risk module to my home workspace.","I am a beginner. Build me a learning and paper-investing workspace.","Social posts often influence me. Add a content-risk review workflow.","Use a light technology-style theme and reduce red/green color dependence."];
const statusLabelZh:Record<string,string>={planning:"规划中",awaiting_input:"等待补充",awaiting_confirmation:"待确认",completed:"已完成",failed:"执行失败",cancelled:"已取消",pending:"等待",running:"执行中"};
const statusLabelEn:Record<string,string>={planning:"Planning",awaiting_input:"More information needed",awaiting_confirmation:"Awaiting confirmation",completed:"Completed",failed:"Failed",cancelled:"Cancelled",pending:"Pending",running:"Running"};
const moduleNamesZh:Record<string,string>={portfolio_risk:"持仓风险",etf_overlap:"ETF 重复暴露",social_risk:"社交内容风险",social_topics:"社交热点主题",social_heat:"热度变化",social_sentiment:"情绪分布",fundamental_verification:"基本面核验",valuation_verification:"估值核验",volume_verification:"资金与成交量核验",portfolio_overlap:"与持仓重合度",financial_quality:"财报体检",simulation_portfolio:"模拟持仓",term_explainer:"术语解释",pretrade_checklist:"交易前检查",weekly_digest:"每周摘要"};
const moduleNamesEn:Record<string,string>={portfolio_risk:"Portfolio risk",etf_overlap:"ETF overlap",social_risk:"Social-content risk",social_topics:"Social topics",social_heat:"Topic momentum",social_sentiment:"Sentiment distribution",fundamental_verification:"Fundamental checks",valuation_verification:"Valuation checks",volume_verification:"Volume and liquidity checks",portfolio_overlap:"Portfolio overlap",financial_quality:"Financial health",simulation_portfolio:"Paper portfolio",term_explainer:"Term explainer",pretrade_checklist:"Pre-trade checklist",weekly_digest:"Weekly digest"};
const toolNamesEn:Record<string,string>={get_market_data:"Read market data",search_stock:"Find security",get_financial_report:"Read financial statements",detect_financial_anomaly:"Check financial anomalies",get_announcement:"Search public filings",get_portfolio:"Read saved portfolio",calculate_portfolio_risk:"Calculate portfolio risk",run_pretrade_check:"Run pre-trade check",run_trade_attribution:"Review trade history",search_etf:"Search ETFs",get_etf_holdings:"Read ETF holdings",diagnose_etf_overlap:"Check ETF overlap",analyze_social_content:"Review social content",parse_natural_strategy:"Parse strategy",validate_strategy_dsl:"Validate strategy rules",route_quant_engine:"Select research engine",workspace_orchestrator:"Preview workspace changes"};
const sourceNamesEn:Record<string,string>={public_market_data:"Public market data",public_financial_data:"Public financial statements",exchange_announcement:"Public filings",user_portfolio:"User-saved portfolio",user_input:"Current user input",fund_disclosure:"Fund disclosures",strategy_registry:"Strategy registry",capability_registry:"Capability registry",xiaohongshu_live:"Authorized social sample"};
const sourceScopesEn:Record<string,string>={public_market_data:"As returned by the live source",public_financial_data:"As of the reported period",exchange_announcement:"Publicly available filings",user_portfolio:"Current signed-in user",user_input:"This task only"};

export function AgentWorkspace(){
  const {isEnglish,locale}=useI18n();
  const examples=isEnglish?examplesEn:examplesZh;
  const statusLabel=isEnglish?statusLabelEn:statusLabelZh;
  const moduleNames=isEnglish?moduleNamesEn:moduleNamesZh;
  const [goal,setGoal]=useState("");const [task,setTask]=useState<Task|null>(null);const [history,setHistory]=useState<Task[]>([]);const [providers,setProviders]=useState<Provider[]>([]);const [provider,setProvider]=useState("mock");const [themeId,setThemeId]=useState("light_quiet");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [answers,setAnswers]=useState<Record<string,string>>({});
  const loadHistory=()=>fetch("/agent/tasks",{cache:"no-store"}).then((r)=>r.json() as Promise<{tasks?:Task[]}>).then((p)=>setHistory(p.tasks??[])).catch(()=>undefined);
  const loadActiveTheme=()=>fetch("/api/me/snapshot",{cache:"no-store"}).then((r)=>r.json() as Promise<{snapshot?:{activeWorkspaceId?:string;workspaces?:Array<{id:string;theme?:{themeId?:string}}>}}>).then((p)=>{const rows=p.snapshot?.workspaces??[];const active=rows.find((item)=>item.id===p.snapshot?.activeWorkspaceId)??rows[0];setThemeId(active?.theme?.themeId??"light_quiet")}).catch(()=>undefined);
  useEffect(()=>{void loadHistory();void loadActiveTheme();fetch("/assistant/session",{cache:"no-store"}).then((r)=>r.json() as Promise<{providers?:Provider[];default_provider_id?:string}>).then((p)=>{setProviders(p.providers??[]);setProvider(p.default_provider_id??"mock")}).catch(()=>undefined)},[]);
  const run=async()=>{if(!goal.trim()||busy)return;setBusy(true);setError("");try{const response=await fetch("/agent/tasks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({goal,route:"/agent",selected_provider:provider,locale})});const payload=await response.json() as Task&{message?:string};if(!response.ok)throw new Error(payload.message||pick(isEnglish,"任务无法创建","Could not create the task"));setTask(payload);void loadHistory();}catch(e){setError(e instanceof Error?e.message:pick(isEnglish,"任务无法创建","Could not create the task"))}finally{setBusy(false)}};
  const continueTask=async()=>{if(!task?.input_request||busy)return;setBusy(true);setError("");try{const response=await fetch(`/agent/tasks/${task.task_id}/continue`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({answers})});const payload=await response.json() as Task&{message?:string};if(!response.ok)throw new Error(payload.message||pick(isEnglish,"任务无法继续","Could not continue the task"));setTask(payload);setAnswers({});void loadHistory();}catch(e){setError(e instanceof Error?e.message:pick(isEnglish,"任务无法继续","Could not continue the task"))}finally{setBusy(false)}};
  const action=async(kind:"confirm"|"cancel"|"retry")=>{if(!task)return;setBusy(true);setError("");try{const response=await fetch(`/agent/tasks/${task.task_id}/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:kind==="confirm"?JSON.stringify({confirmed:true}):undefined});const payload=await response.json() as Task&{message?:string};if(!response.ok)throw new Error(payload.message||pick(isEnglish,"操作失败","Action failed"));setTask(payload);if(kind==="confirm"&&task.theme_schema)setThemeId(task.theme_schema.mode==="dark"?"dark_focus":task.theme_schema.accessibility.high_contrast?"high_contrast":"clear_blue");window.dispatchEvent(new CustomEvent("anxin:snapshot-updated"));void loadHistory();}catch(e){setError(e instanceof Error?e.message:pick(isEnglish,"操作失败","Action failed"))}finally{setBusy(false)}};
  const retryTool=async(toolId:string)=>{if(!task||busy)return;setBusy(true);setError("");try{const response=await fetch(`/agent/tasks/${task.task_id}/tools/${toolId}/retry`,{method:"POST"});const payload=await response.json() as Task&{message?:string};if(!response.ok)throw new Error(payload.message||"工具重试失败");setTask(payload);void loadHistory();}catch(e){setError(e instanceof Error?e.message:"工具重试失败")}finally{setBusy(false)}};
  const undo=async()=>{setBusy(true);try{const response=await fetch("/workspace/undo",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true})});if(!response.ok)throw new Error("没有可撤销的修改");await loadActiveTheme();window.dispatchEvent(new CustomEvent("anxin:snapshot-updated"));}catch(e){setError(e instanceof Error?e.message:"撤销失败")}finally{setBusy(false)}};
  const exportTask=()=>{if(!task)return;const blob=new Blob([JSON.stringify(task,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`anxin-agent-${task.task_id}.json`;link.click();URL.revokeObjectURL(url)};
  const currentProvider=providers.find((item)=>item.providerId===provider);
  return <div className="agent-os" data-agent-theme={themeId}>
    <header className="agent-os-header"><div><span className="agent-kicker"><Bot/>{pick(isEnglish,"任务工作台","Task workspace")}</span><h1>{pick(isEnglish,"告诉我你想完成什么","What would you like to accomplish?")}</h1><p>{pick(isEnglish,"系统会列出步骤、调用已授权工具，并把保存或界面修改停在确认之前。","The system shows each step, calls only authorized tools, and pauses before saving or changing your workspace.")}</p></div><label><span>{pick(isEnglish,"当前处理方式","Current planning method")}</span><select value={provider} onChange={(e)=>setProvider(e.target.value)}>{providers.filter((p)=>p.enabled).map((p)=><option key={p.providerId} value={p.providerId}>{providerDisplay(p,isEnglish)} · {p.model||pick(isEnglish,"规则模式","Rules mode")}</option>)}</select><small>{provider==="mock"?pick(isEnglish,"使用能力目录和确定性工具，不生成模型回答","Uses the capability catalog and deterministic tools; no model-generated response"):currentProvider?.connectionStatus==="available"?pick(isEnglish,"模型已连接","Model connected"):pick(isEnglish,"需要配置","Configuration required")}</small></label></header>
    <section className="agent-command"><Textarea value={goal} onChange={(e)=>setGoal(e.target.value)} placeholder={pick(isEnglish,"告诉我你想完成什么，我来帮你搭建和执行。","Describe your goal. I will build a transparent plan and carry it out.")} rows={4}/><div className="agent-example-row">{examples.map((item)=><button key={item} onClick={()=>setGoal(item)}>{item}</button>)}</div><footer><span>{pick(isEnglish,"查询和计算可直接执行；工作台、规则、提醒和模拟必须确认。","Queries and calculations can run directly. Workspace, rule, reminder, and simulation changes require confirmation.")}</span><Button onClick={()=>void run()} disabled={!goal.trim()||busy}>{busy?<LoaderCircle className="spin"/>:<Play/>}{pick(isEnglish,"生成执行计划","Generate plan")}</Button></footer></section>
    {error&&<div className="agent-error"><CircleAlert/>{error}</div>}
    {!task?<AgentEmpty isEnglish={isEnglish}/>:<div className="agent-task-grid">
      <section className="agent-intent"><header><Bot/><span><strong>{pick(isEnglish,"目标结构","Goal structure")}</strong><small>{task.planner_mode==="provider"?pick(isEnglish,"由当前模型规划","Planned by the current model"):pick(isEnglish,"由本地 Registry 安全匹配","Safely matched by the local registry")}</small></span></header><div className="agent-intent-grid"><article><small>{pick(isEnglish,"用户阶段","User stage")}</small><strong>{stageLabel(task.extraction.user_stage,isEnglish)}</strong></article><article><small>{pick(isEnglish,"风险等级","Risk level")}</small><strong>{riskLabel(task.extraction.risk_level,isEnglish)}</strong></article><article><small>{pick(isEnglish,"需要数据","Data needed")}</small><strong>{task.extraction.data_requirements.length} {pick(isEnglish,"项","items")}</strong></article><article><small>{pick(isEnglish,"需要分析","Analysis needed")}</small><strong>{task.extraction.analysis_requirements.length} {pick(isEnglish,"项","items")}</strong></article></div>{task.extraction.missing_information.length>0&&task.status!=="awaiting_input"&&<div className="agent-missing"><strong>{pick(isEnglish,"可选补充","Optional details")}</strong>{task.extraction.missing_information.slice(0,3).map((item)=><p key={item}><CircleAlert/>{item}</p>)}</div>}</section>
      {task.status==="awaiting_input"&&task.input_request&&<section className="agent-input-request">
        <header><CircleAlert/><span><strong>{task.input_request.title}</strong><small>{task.input_request.description}</small></span><Badge variant="outline">步骤 {Math.max(2,task.steps.findIndex((step)=>step.status==="awaiting_input")+1)}</Badge></header>
        <div className="agent-input-fields">{task.input_request.fields.map((field)=><fieldset key={field.id}><legend>{field.label}</legend><p>{field.question}</p>{field.type==="choice"?<div className="agent-choice-grid">{field.options?.map((option)=><button key={option} type="button" data-selected={answers[field.id]===option} onClick={()=>setAnswers((current)=>({...current,[field.id]:option}))}>{option}</button>)}</div>:<Input value={answers[field.id]??""} onChange={(event)=>setAnswers((current)=>({...current,[field.id]:event.target.value}))} placeholder="输入代码、名称或必要说明"/>}</fieldset>)}</div>
        <footer><span>{pick(isEnglish,"已完成","Completed")} {task.input_request.fields.filter((field)=>String(answers[field.id]??"").trim()).length}/{task.input_request.fields.length}</span><Button onClick={()=>void continueTask()} disabled={busy||task.input_request.fields.some((field)=>!String(answers[field.id]??"").trim())}>{busy?<LoaderCircle className="spin"/>:<Play/>}{pick(isEnglish,"继续这项任务","Continue task")}</Button></footer>
      </section>}
      <section className="agent-plan"><header><div><ListChecks/><span><small>{pick(isEnglish,"任务","Task")} {task.task_id.slice(-6)}</small><strong>{task.goal}</strong></span></div><Badge variant={task.status==="completed"?"secondary":"outline"}>{statusLabel[task.status]??task.status}</Badge></header><div className="agent-steps">{task.steps.map((step,index)=><article key={step.id} data-status={step.status}><i>{step.status==="completed"?<Check/>:step.status==="failed"?<CircleAlert/>:index+1}</i><span><strong>{isEnglish?(step.tool?toolNamesEn[step.tool]??step.title:index===0?"Understand the goal and context":step.title):step.title}</strong><small>{step.tool||pick(isEnglish,"任务规划","Task planning")}{step.requires_confirmation?pick(isEnglish," · 需要确认"," · confirmation required"):""}</small></span><em>{statusLabel[step.status]??step.status}</em></article>)}</div>{task.warnings.length>0&&<aside className="agent-warnings">{task.warnings.map((w)=><p key={w}><ShieldCheck/>{warningMessage(w,isEnglish)}</p>)}</aside>}</section>
      <section className="agent-tools"><header><Wrench/><span><strong>{pick(isEnglish,"工具调用","Tool calls")}</strong><small>{task.tool_calls.length} {pick(isEnglish,"项白名单能力","allowlisted capabilities")}</small></span></header>{task.tool_calls.length?task.tool_calls.map((call)=><article key={call.tool_id}><div><strong>{call.tool_id}</strong><Badge variant="outline">{statusLabel[call.status]??call.status}</Badge>{call.status==="failed"&&call.reliability?.retryable&&<Button size="sm" variant="ghost" onClick={()=>void retryTool(call.tool_id)} disabled={busy}><RefreshCw/>{pick(isEnglish,"单步重试","Retry step")}</Button>}</div><p>{summarizeOutput(call.output,call.error,isEnglish)}</p>{call.reliability&&<small>{reliabilityMessage(call.reliability,isEnglish)} · {pick(isEnglish,"信号","Signals")} {call.reliability.allow_signal?pick(isEnglish,"允许","allowed"):pick(isEnglish,"阻断","blocked")} · {pick(isEnglish,"交易禁止","trading disabled")}</small>}</article>):<p className="agent-muted">{pick(isEnglish,"本任务不需要调用金融数据工具。","This task does not require a financial-data tool.")}</p>}</section>
      <section className="agent-sources"><header><Database/><span><strong>{pick(isEnglish,"数据来源","Data sources")}</strong><small>{pick(isEnglish,"来源、时间和样本边界","Source, timestamp, and sample scope")}</small></span></header>{task.sources.length?task.sources.map((item,index)=><article key={`${item.source_id}-${index}`}><div><strong>{isEnglish?sourceNamesEn[item.source_id]??item.name:item.name}</strong><Badge variant="outline">{item.status==="available"?pick(isEnglish,"可用","Available"):item.status==="missing"?pick(isEnglish,"缺少输入","Input missing"):pick(isEnglish,"不可用","Unavailable")}</Badge></div><p>{isEnglish?sourceScopesEn[item.source_id]??item.sample_scope:item.sample_scope}</p><time>{new Date(item.collected_at).toLocaleString(locale)}</time></article>):<p className="agent-muted">{pick(isEnglish,"当前任务没有使用外部金融数据。","No external financial data was used for this task.")}</p>}</section>
      <section className="agent-result"><header><Check/><span><strong>{pick(isEnglish,"结果预览","Result preview")}</strong><small>{pick(isEnglish,"仅展示工具真实返回或明确缺失状态","Shows only real tool output or an explicit missing-data state")}</small></span></header>{task.tool_calls.length?<><AgentKeyFindings calls={task.tool_calls} isEnglish={isEnglish}/>{task.tool_calls.map((call)=><AgentResult key={`result-${call.tool_id}`} toolId={call.tool_id} output={call.output} error={call.error} isEnglish={isEnglish}/>)}</>:<p className="agent-muted">{pick(isEnglish,"当前目标只涉及工作台配置，没有读取金融数据。","This goal only changes workspace configuration; no financial data was read.")}</p>}</section>
      {task.workspace_patch&&task.status!=="awaiting_input"&&<section className="agent-patch"><header><Sparkles/><span><strong>{pick(isEnglish,"工作台修改预览","Workspace change preview")}</strong><small>{pick(isEnglish,"确认前不会改变页面","Nothing changes before confirmation")}</small></span></header><h2>{task.workspace_patch.summary}</h2>{task.workspace_before&&task.workspace_patch.preview&&<WorkspaceVisualDiff before={task.workspace_before} after={task.workspace_patch.preview} isEnglish={isEnglish} moduleNames={moduleNames}/>}<div className="agent-patch-modules">{task.workspace_patch.affectedModules.map((m)=><span key={m}>{moduleNames[m]??m}</span>)}</div>{task.theme_schema&&<div className="agent-theme-preview"><span style={{background:task.theme_schema.colors.accent}}/><div><small>{pick(isEnglish,"主题预览","Theme preview")}</small><strong>{task.theme_schema.name} · {task.theme_schema.mode==="dark"?pick(isEnglish,"深色","Dark"):pick(isEnglish,"浅色","Light")}</strong><p>{task.theme_schema.density} {pick(isEnglish,"密度","density")} · {task.theme_schema.motion} {pick(isEnglish,"动效","motion")}{task.theme_schema.accessibility.reduced_motion?pick(isEnglish," · 减少动态"," · reduced motion"):""}</p></div></div>}<ul>{task.workspace_patch.changes.map((c)=><li key={c}><Check/>{c}</li>)}</ul>{task.workspace_patch.questions.map((q)=><p key={q}><CircleAlert/>{q}</p>)}</section>}
      {task.tool_proposal&&<section className="agent-proposal"><header><Wrench/><span><strong>当前能力缺口</strong><small>不会生成或执行未知代码</small></span></header><h2>{task.tool_proposal.name}</h2><p>{task.tool_proposal.purpose}</p><div><b>需要审核</b>{task.tool_proposal.risks.join(" · ")}</div></section>}
      <section className="agent-actions"><div><strong>{task.status==="awaiting_input"?pick(isEnglish,"等待你补充 1—3 项信息","Waiting for 1–3 details"):task.requires_confirmation?pick(isEnglish,"修改已预览，等待确认","Changes previewed; awaiting confirmation"):task.status==="completed"?pick(isEnglish,"任务已完成","Task completed"):pick(isEnglish,"任务已停在安全边界内","Task paused at a safe boundary")}</strong><span>{task.reliability?reliabilityMessage(task.reliability,isEnglish):pick(isEnglish,"系统不会执行真实交易。","The system never executes real trades.")} · {pick(isEnglish,"信号","Signals")} {task.reliability?.allow_signal?pick(isEnglish,"允许","allowed"):pick(isEnglish,"阻断","blocked")} · {pick(isEnglish,"交易禁止","trading disabled")}</span></div><div>{task.requires_confirmation&&task.status!=="awaiting_input"&&<Button onClick={()=>void action("confirm")} disabled={busy}><Check/>{pick(isEnglish,"确认并应用","Confirm and apply")}</Button>}{task.status!=="cancelled"&&task.status!=="completed"&&<Button variant="outline" onClick={()=>void action("cancel")} disabled={busy}><Square/>{pick(isEnglish,"取消任务","Cancel task")}</Button>}{task.status==="failed"&&<Button variant="outline" onClick={()=>void action("retry")} disabled={busy}><RefreshCw/>{pick(isEnglish,"仅重试失败步骤","Retry failed steps")}</Button>}<Button variant="outline" onClick={exportTask}><Download/>{pick(isEnglish,"导出执行记录","Export run log")}</Button><Button variant="ghost" onClick={()=>void undo()} disabled={busy}><RotateCcw/>{pick(isEnglish,"撤销工作台修改","Undo workspace change")}</Button></div></section>
    </div>}
    <section className="agent-history"><header><Clock3/><span><strong>{pick(isEnglish,"任务历史","Task history")}</strong><small>{pick(isEnglish,"保留目标、计划、工具状态和确认结果","Keeps goals, plans, tool states, and confirmation results")}</small></span></header>{history.length?history.slice(0,8).map((item)=><button key={item.task_id} onClick={()=>setTask(item)}><span><strong>{item.goal}</strong><small>{new Date(item.created_at).toLocaleString(locale)} · {item.provider}/{item.model}</small></span><Badge variant="outline">{statusLabel[item.status]??item.status}</Badge></button>):<p className="agent-muted">{pick(isEnglish,"还没有任务记录。","No task history yet.")}</p>}</section>
    <footer className="agent-disclaimer">{pick(isEnglish,"本工具仅用于信息整理、模拟分析和风险提示，不构成投资建议、收益承诺或买卖指令。","This tool is for information organization, simulated analysis, and risk alerts only. It does not provide investment advice, return guarantees, or trading instructions.")}</footer>
  </div>
}

function WorkspaceVisualDiff({before,after,isEnglish,moduleNames}:{before:MiniWorkspace;after:MiniWorkspace;isEnglish:boolean;moduleNames:Record<string,string>}){
  const beforeTypes=new Set(before.modules.filter((item)=>item.visible).map((item)=>item.type));
  const afterTypes=new Set(after.modules.filter((item)=>item.visible).map((item)=>item.type));
  const render=(workspace:MiniWorkspace,side:"before"|"after")=><div className="agent-workspace-mini" data-side={side}>
    <header><span>{side==="before"?pick(isEnglish,"当前","Current"):pick(isEnglish,"修改后","After")}</span><strong>{workspace.name}</strong></header>
    <div className="agent-workspace-mini-grid">{workspace.modules.filter((item)=>item.visible).sort((a,b)=>a.order-b.order).map((item)=>{
      const changed=side==="after"?!beforeTypes.has(item.type):!afterTypes.has(item.type);
      return <article key={`${side}-${item.type}`} data-change={changed?(side==="after"?"added":"removed"):"kept"} data-width={item.width}><span>{moduleNames[item.type]??item.type}</span>{changed&&<small>{side==="after"?pick(isEnglish,"新增","Added"):pick(isEnglish,"将隐藏","Hidden")}</small>}</article>;
    })}</div>
    <div className="agent-workflow-mini">{workspace.workflow.map((step,index)=><span key={`${side}-${step}`}>{index>0&&<i>→</i>}{workflowLabel(step)}</span>)}</div>
  </div>;
  return <div className="agent-workspace-diff">{render(before,"before")}<div className="agent-diff-arrow">→</div>{render(after,"after")}</div>;
}
function workflowLabel(value:string){return({learn:"学习",simulate:"模拟",research:"研究",check_social_claim:"核验内容",review_risk:"检查风险",pretrade_check:"交易前检查",confirm_next_step:"自行确认",review_trade:"复盘",generate_report:"生成报告",weekly_review:"定期复核",check_etf_overlap:"检查重合"} as Record<string,string>)[value]??value}

function AgentEmpty({isEnglish}:{isEnglish:boolean}){return <section className="agent-empty"><Sparkles/><h2>{pick(isEnglish,"一个目标，可以组合多个能力","One goal can combine multiple capabilities")}</h2><p>{pick(isEnglish,"例如先读取持仓，再检查 ETF 重复暴露，最后预览一个新的风险工作台。没有工具时，我会明确提出能力草案。","For example: read your holdings, check ETF overlap, then preview a new risk workspace. If no suitable tool exists, the system clearly proposes a capability instead of pretending.")}</p><div><span>{pick(isEnglish,"计划可见","Visible plan")}</span><span>{pick(isEnglish,"来源可查","Traceable sources")}</span><span>{pick(isEnglish,"修改需确认","Changes require confirmation")}</span><span>{pick(isEnglish,"全程可撤销","Fully undoable")}</span></div></section>}
function stageLabel(value:string,isEnglish:boolean){const zh={beginner:"投资新手",learner:"学习阶段",experienced:"有经验",professional:"专业用户",unknown:"待确认"} as Record<string,string>;const en={beginner:"Beginner",learner:"Learning",experienced:"Experienced",professional:"Professional",unknown:"To confirm"} as Record<string,string>;return (isEnglish?en:zh)[value]??value}
function riskLabel(value:string,isEnglish:boolean){const zh={low:"低风险",medium:"需确认",high:"高风险",restricted:"禁止执行"} as Record<string,string>;const en={low:"Low risk",medium:"Confirmation needed",high:"High risk",restricted:"Blocked"} as Record<string,string>;return (isEnglish?en:zh)[value]??value}
function formatMoney(value:unknown){return new Intl.NumberFormat("zh-CN",{style:"currency",currency:"CNY",maximumFractionDigits:0}).format(Number(value??0))}
function formatPct(value:unknown){return `${(Number(value??0)*100).toFixed(1)}%`}
function formatPctPoints(value:unknown){const number=Number(value);return Number.isFinite(number)?`${number>0?"+":""}${number.toFixed(2)}%`:"暂无"}
function formatTime(value:unknown){if(!value)return"时间待核对";const date=new Date(String(value));return Number.isNaN(date.getTime())?String(value):date.toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false})}
function reliabilityMessage(value:Reliability,isEnglish:boolean){
  if(!isEnglish)return value.message;
  if(value.status==="healthy")return"Tool completed with traceable output";
  if(value.status==="degraded")return"Partial result; missing inputs are shown";
  if(value.status==="failed")return"Tool failed; no result was fabricated";
  if(value.status==="blocked")return"Paused at the safety boundary";
  return value.message;
}
function warningMessage(value:string,isEnglish:boolean){
  if(!isEnglish)return value;
  if(value.includes("当前没有可用的真实 AI Provider"))return"The selected model did not complete this planning attempt; deterministic tools continued without fabricating a model answer.";
  return value;
}
function summarizeOutput(output:unknown,error?:string,isEnglish=false){
  if(error)return error;if(!output)return pick(isEnglish,"暂无输出","No output");const row=output as Record<string,unknown>;
  if(row.data_status==="missing")return String(row.message??pick(isEnglish,"暂无数据","No data"));
  if(row.type==="portfolio_risk"){
    const largest=row.largest_position as {name?:string;weight?:number}|null;
    const sector=row.largest_sector as {industry?:string;weight?:number}|null;
    return `${largest?.name??"暂无持仓"} ${formatPct(largest?.weight)} · 最大行业 ${sector?.industry??"待核对"} ${formatPct(sector?.weight)}`;
  }
  if(row.type==="market_snapshot")return isEnglish?`${row.code} ${row.current_price??"N/A"} · daily ${formatPctPoints(row.day_change_pct)} · ${row.period_days}-day ${formatPctPoints(row.period_change_pct)}`:`${row.code} ${row.current_price??"暂无"} · 当日 ${formatPctPoints(row.day_change_pct)} · ${row.period_days}日 ${formatPctPoints(row.period_change_pct)}`;
  if(row.type==="financial_snapshot"||row.type==="financial_anomaly"){const checks=(row.checks??[]) as unknown[];return isEnglish?`${row.code} · period ${row.report_date??"N/A"} · ${checks.length} checks`:`${row.code} · 报告期 ${row.report_date??"暂无"} · ${checks.length} 项核对结果`;}
  if(row.type==="announcement_snapshot"){const items=(row.items??[]) as unknown[];return isEnglish?`${row.code} · ${items.length} recent filings · claim not found in current filings`:`${row.code} · ${items.length} 条近期公告 · ${String((row.assessment as {status?:string}|undefined)?.status??"待核对")}`;}
  if(row.amount!==undefined&&row.reasonType!==undefined)return isEnglish?`Planned amount ${formatMoney(row.amount)} · ${(row.violations as unknown[]|undefined)?.length??0} rule issue(s) · ${((row.checks??[]) as unknown[]).length} checks`:`计划金额 ${formatMoney(row.amount)} · ${(row.violations as unknown[]|undefined)?.length??0} 项规则问题 · ${((row.checks??[]) as unknown[]).length} 项核对`;
  if(row.message)return String(row.message);
  if(row.portfolio_value!==undefined)return isEnglish?`Portfolio ${formatMoney(row.portfolio_value)} · ${row.position_count} position(s)`:`组合 ${formatMoney(row.portfolio_value)} · ${row.position_count} 项持仓`;
  if(row.type==="social_trend_analysis")return pick(isEnglish,"当前没有足够样本，未生成平台热度","There is not enough data to calculate platform-level trends.");
  return pick(isEnglish,"工具已返回结构化结果，可在任务记录中追溯。","The tool returned structured output that can be traced in the task log.");
}
function financialCheckCopy(item:{id?:string;title?:string;finding?:string;evidence?:string;why_it_matters?:string},isEnglish:boolean){
  if(!isEnglish)return item;
  const labels:Record<string,string>={profit_cash_quality:"Cash conversion",cash_conversion:"Cash conversion",receivables:"Receivables",inventory:"Inventory",leverage:"Balance-sheet pressure",debt_pressure:"Balance-sheet pressure"};
  const title=labels[item.id??""]??({"利润含金量":"Cash conversion","回款压力":"Receivables","存货变化":"Inventory","财务压力":"Balance-sheet pressure"} as Record<string,string>)[item.title??""]??item.title??"Financial check";
  const evidence=String(item.evidence??"").replace("经营现金流 / 净利润","Operating cash flow / net profit").replace("应收同比","Receivables YoY").replace("收入同比","Revenue YoY").replace("存货同比","Inventory YoY").replace("资产负债率","Debt-to-assets");
  const finding=item.id?.includes("cash")?"Operating cash flow is materially below reported net profit":item.id?.includes("receiv")?"Receivables growth is below revenue growth":item.id?.includes("invent")?"Inventory growth is below revenue growth":item.id?.includes("debt")||item.id?.includes("lever")?"Debt-to-assets is below the preset review threshold":item.finding??"Review the reported change";
  return {...item,title,finding,evidence,why_it_matters:"This rule is a screening check, not a complete financial conclusion."};
}
function pretradeCheckEnglish(item:{title?:string;fact?:string}){
  const title=({"持有期限":"Holding period","退出条件":"Exit condition","单一持仓":"Position concentration","行业集中":"Sector concentration","近期涨幅":"Recent price move","重复暴露":"Overlapping exposure","社交内容触发":"Social-content trigger"} as Record<string,string>)[item.title??""]??item.title??"Review item";
  const fact=String(item.fact??"").replace("没有填写预计持有期限","No expected holding period was provided").replace("没有填写判断失效条件","No invalidation or exit condition was provided").replace("计划后","After the plan: ").replace("个人上限","personal limit ");
  return `${title}: ${fact}`;
}
function portfolioReviewEnglish(value:string){
  const position=value.match(/^(.+?)占组合([\d.]+)%，(超过|未超过)个人单一持仓上限([\d.]+)%/);
  if(position)return `${position[1]} is ${position[2]}% of the portfolio and ${position[3]==="超过"?"exceeds":"is within"} the ${position[4]}% personal position limit.`;
  const missing=value.match(/^(\d+)项持仓缺少行业标签/);
  if(missing)return `${missing[1]} position(s) lack sector labels, so sector concentration is only a partial result.`;
  return value;
}
function AgentResult({toolId,output,error,isEnglish}:{toolId:string;output:unknown;error?:string;isEnglish:boolean}){
  const row=(output??{}) as Record<string,unknown>;
  if(row.type==="market_snapshot")return <article className="agent-research-result"><div className="agent-result-title"><strong>{pick(isEnglish,"价格与成交","Price and volume")}</strong><span>{isEnglish?"Public market data":String(row.source??"公开行情")} · {formatTime(row.data_timestamp)}</span></div><div className="agent-risk-metrics"><div><small>{pick(isEnglish,"最新收盘","Latest close")}</small><b>{String(row.current_price??pick(isEnglish,"暂无","N/A"))}</b><span>{String(row.code)}</span></div><div><small>{pick(isEnglish,"当日变化","Daily change")}</small><b>{formatPctPoints(row.day_change_pct)}</b><span>{pick(isEnglish,"相对上一交易日","Versus previous trading day")}</span></div><div><small>{String(row.period_days)}{pick(isEnglish,"日变化","-day change")}</small><b>{formatPctPoints(row.period_change_pct)}</b><span>{pick(isEnglish,"历史区间，不代表未来","Historical period; not a forecast")}</span></div></div></article>;
  if(row.type==="financial_snapshot"||row.type==="financial_anomaly"){
    const checks=(row.checks??[]) as Array<{id?:string;title?:string;state?:string;finding?:string;evidence?:string;why_it_matters?:string}>;
    return <article className="agent-research-result"><div className="agent-result-title"><strong>{row.type==="financial_anomaly"?pick(isEnglish,"财务异常核对","Financial anomaly check"):pick(isEnglish,"财务变化","Financial changes")}</strong><span>{pick(isEnglish,"报告期","Report period")} {String(row.report_date??pick(isEnglish,"暂无","N/A"))} · {isEnglish?"Public financial statements":String(row.source??"公开财务报表")}</span></div>{checks.length?<ul className="agent-check-list">{checks.map((raw,index)=>{const item=financialCheckCopy(raw,isEnglish);return <li key={`${item.id}-${index}`}><b data-state={item.state}>{item.title??pick(isEnglish,"核对项","Check")}</b><span>{item.finding??pick(isEnglish,"暂无结论","No conclusion")} · {item.evidence??pick(isEnglish,"暂无证据","No evidence")}</span><small>{item.why_it_matters}</small></li>})}</ul>:<p>{pick(isEnglish,"当前规则没有发现需要单独列出的异常；这不等于财务没有风险。","Current rules found no anomaly to list separately; this does not mean the financials are risk-free.")}</p>}<small className="agent-result-note">{isEnglish?"Financial checks organize reported facts and do not forecast earnings or recommend a trade.":String(row.disclaimer??"")}</small></article>;
  }
  if(row.type==="announcement_snapshot"){
    const items=(row.items??[]) as Array<{title?:string;published_at?:string;source?:string;url?:string;relation?:string}>;
    return <article className="agent-research-result"><div className="agent-result-title"><strong>{pick(isEnglish,"近期公告","Recent filings")}</strong><span>{String((row.assessment as {status?:string}|undefined)?.status??pick(isEnglish,"待核对","To verify"))} · {formatTime(row.data_timestamp)}</span></div>{items.length?<ul className="agent-announcement-list">{items.map((item,index)=><li key={`${item.url}-${index}`}><span><b>{item.title??pick(isEnglish,"公司公告","Company filing")}</b><small>{String(item.published_at??"").slice(0,10)} · {item.source??row.source}</small></span>{item.url?<a href={item.url} target="_blank" rel="noreferrer">{pick(isEnglish,"打开原文","Open source")}</a>:null}</li>)}</ul>:<p>{pick(isEnglish,"当前来源没有返回近期公告，不能据此推断没有事件。","No recent filing was returned. This does not prove that no event occurred.")}</p>}<small className="agent-result-note">{String(row.disclaimer??"")}</small></article>;
  }
  if(toolId==="run_pretrade_check")return <article className="agent-research-result"><div className="agent-result-title"><strong>{pick(isEnglish,"交易前检查","Pre-trade check")}</strong><span>{pick(isEnglish,"个人规则与仓位影响","Personal rules and position impact")}</span></div><div className="agent-risk-metrics"><div><small>{pick(isEnglish,"计划金额","Planned amount")}</small><b>{formatMoney(row.amount)}</b><span>{String(row.code??"600183")}</span></div><div><small>{pick(isEnglish,"计划后仓位","Position after plan")}</small><b>{formatPct(row.afterSingleWeight)}</b><span>{pick(isEnglish,"对照个人单股上限","Compared with the personal limit")}</span></div><div><small>{pick(isEnglish,"规则问题","Rule issues")}</small><b>{((row.violations??[]) as unknown[]).length}</b><span>{pick(isEnglish,"最终决定由用户完成","Final decision remains with the user")}</span></div></div><ul>{((row.checks??[]) as Array<{title?:string;fact?:string}>).slice(0,4).map((item,index)=><li key={`${item.title}-${index}`}>{isEnglish?pretradeCheckEnglish(item):`${item.title}：${item.fact}`}</li>)}</ul></article>;
  if(row.type!=="portfolio_risk")return <article><strong>{toolId}</strong><p>{summarizeOutput(output,error,isEnglish)}</p></article>;
  const largest=row.largest_position as {name?:string;code?:string;value?:number;weight?:number}|null;
  const sector=row.largest_sector as {industry?:string;weight?:number}|null;
  const checks=(row.rule_checks??[]) as Array<{id:string;label:string;actual:number;limit:number;status:string}>;
  const items=(row.review_items??[]) as string[];
  return <article className="agent-risk-result"><div className="agent-result-title"><strong>{pick(isEnglish,"组合风险核对","Portfolio risk check")}</strong><span>{pick(isEnglish,`${row.position_count} 项持仓`,`${row.position_count} positions`)} · {formatMoney(row.portfolio_value)}</span></div><div className="agent-risk-metrics"><div><small>{pick(isEnglish,"最大持仓","Largest position")}</small><b>{largest?.name??pick(isEnglish,"暂无","N/A")}</b><span>{formatPct(largest?.weight)} · {formatMoney(largest?.value)}</span></div><div><small>{pick(isEnglish,"最大行业","Largest sector")}</small><b>{sector?.industry??pick(isEnglish,"暂无可计算标签","No calculable label")}</b><span>{sector?formatPct(sector.weight):pick(isEnglish,"请先补充行业","Add sector labels")}</span></div><div><small>{pick(isEnglish,"规则状态","Rule status")}</small><b>{pick(isEnglish,`${checks.filter((item)=>item.status==="exceeded").length} 项超限`,`${checks.filter((item)=>item.status==="exceeded").length} limit breach(es)`)}</b><span>{row.missing_industry_count?pick(isEnglish,`${row.missing_industry_count} 项行业待补充`,`${row.missing_industry_count} sector label(s) missing`):pick(isEnglish,"行业标签完整","Sector labels complete")}</span></div></div><ul>{items.map((item)=><li key={item}>{isEnglish?portfolioReviewEnglish(item):item}</li>)}</ul><small className="agent-result-note">{isEnglish?"Checks use only the user-saved portfolio and personal rules; they are not trading advice.":String(row.disclaimer??"")}</small></article>;
}
function AgentKeyFindings({calls,isEnglish}:{calls:Task["tool_calls"];isEnglish:boolean}){
  const findings:string[]=[];
  for(const call of calls){
    const row=(call.output??{}) as Record<string,unknown>;
    if(row.type==="market_snapshot")findings.push(isEnglish?`Price changed ${formatPctPoints(row.period_change_pct)} over ${row.period_days} trading days; price movement alone does not explain why.`:`近${row.period_days}个交易日价格变化 ${formatPctPoints(row.period_change_pct)}；价格变化本身不能解释原因。`);
    if(row.type==="financial_snapshot"||row.type==="financial_anomaly"){
      const checks=(row.checks??[]) as Array<{state?:string;title?:string;finding?:string;evidence?:string}>;
      for(const raw of checks.filter((check)=>check.state==="attention"||check.state==="watch").slice(0,2)){const item=financialCheckCopy(raw,isEnglish);findings.push(isEnglish?`${item.title}: ${item.finding} (${item.evidence}).`:`${item.title}：${item.finding}（${item.evidence}）。`);}
    }
    if(row.type==="announcement_snapshot"){
      const items=(row.items??[]) as Array<{title?:string}>;
      if(items[0])findings.push(isEnglish?`The current filing list does not directly verify the “major order” claim; open the original filings before treating it as fact.`:`最近公告包括“${items[0].title}”；需要打开原文核对披露范围，而不是只读标题。`);
    }
    if(row.type==="portfolio_risk")findings.push(...((row.review_items??[]) as string[]).slice(0,3).map((item)=>isEnglish?portfolioReviewEnglish(item):item));
  }
  if(!findings.length)return null;
  return <aside className="agent-key-findings"><span>{pick(isEnglish,`先看这 ${Math.min(findings.length,4)} 项`,`Start with these ${Math.min(findings.length,4)} findings`)}</span><ol>{findings.slice(0,4).map((item)=><li key={item}>{item}</li>)}</ol></aside>;
}
