"use client";

import Link from "next/link";
import { ArrowRight, BookOpenCheck, Bot, CheckCircle2, Clock3, Database, ExternalLink, FileQuestion, GitBranch, LoaderCircle, Search, ShieldCheck, Sparkles, TriangleAlert } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { pick, useI18n } from "../i18n";

type Status = "available" | "beta" | "planned" | "disabled" | "unavailable";
type Capability = { capability_id:string; name:string; category:string; description:string; status:Status; route:string|null; outputs:string[]; limitations:string[]; last_updated:string; version:string };
type IndexState = { status?:string; indexed_count?:number; available_count?:number; beta_count?:number; unavailable_count?:number; last_success_at?:string };
type Answer = { answer:string; sources:Array<Pick<Capability,"capability_id"|"name"|"category"|"status"|"route"|"version"|"last_updated"> & {why_relevant:string}>; note:string };

const STATUS_ZH:Record<Status,string>={available:"已上线",beta:"测试中",planned:"计划中",disabled:"已停用",unavailable:"当前不可用"};
const STATUS_EN:Record<Status,string>={available:"Available",beta:"Beta",planned:"Planned",disabled:"Disabled",unavailable:"Unavailable"};
const CATEGORY_ZH:Record<string,string>={page:"页面",tool:"工具",module:"模块",workflow:"流程",provider:"模型",data_source:"数据源",engine:"研究引擎"};
const CATEGORY_EN:Record<string,string>={page:"Page",tool:"Tool",module:"Module",workflow:"Workflow",provider:"Model",data_source:"Data source",engine:"Research engine"};
const QUESTIONS_ZH=["目前已经完成了哪些核心功能？","没有 API Key 时还能使用什么？","为什么它不只是 ChatGPT 加股票数据？","哪些能力仍在测试中？"];
const QUESTIONS_EN=["Which core capabilities are available now?","What works without an API key?","Why is this more than ChatGPT with stock data?","Which capabilities are still in beta?"];
const FEATURED=["workflow_decision_layer","tool_analyze_social_content","tool_run_pretrade_check","tool_get_portfolio_risk","page_etf","page_trade","page_quant","workflow_no_key_fallback","workflow_pitch_demo"];
const FEATURED_EN:Record<string,[string,string]>={
  workflow_decision_layer:["Research-to-decision workflow","Connect public information, your thesis, portfolio impact, personal rules and follow-up review."],
  tool_analyze_social_content:["Social-content risk analysis","Review user-provided social claims for evidence gaps, urgency and herding signals."],
  tool_run_pretrade_check:["Pre-trade check","Check planned exposure, stated reasons and exit conditions before a decision."],
  tool_get_portfolio_risk:["Portfolio risk check","Calculate concentration, loss scenarios and overlapping exposure."],
  page_etf:["ETF diagnosis","Search ETFs, inspect underlying holdings and identify overlap."],
  page_trade:["Trade review","Import a CSV for FIFO attribution and behavior review."],
  page_quant:["Low-frequency quant research","Turn a plain-language idea into confirmable rules, backtests and paper simulation."],
  workflow_no_key_fallback:["No-key fallback","Keep deterministic market, overlap, attribution and review workflows available without an external model."],
  workflow_pitch_demo:["90-second product demo","Walk through a repeatable pre-trade review without relying on live data or an external model."],
};

const fmt=(value:string|undefined,locale:string)=>value?new Intl.DateTimeFormat(locale,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):(locale==="en"?"N/A":"暂无");

export function CapabilityGuide(){
  const {isEnglish,locale}=useI18n();const questions=isEnglish?QUESTIONS_EN:QUESTIONS_ZH;const status=isEnglish?STATUS_EN:STATUS_ZH;const category=isEnglish?CATEGORY_EN:CATEGORY_ZH;
  const [items,setItems]=useState<Capability[]>([]);const [index,setIndex]=useState<IndexState>({});const [loading,setLoading]=useState(true);const [query,setQuery]=useState(questions[0]);const [asking,setAsking]=useState(false);const [answer,setAnswer]=useState<Answer|null>(null);const [error,setError]=useState("");
  useEffect(()=>{setQuery(current=>QUESTIONS_ZH.includes(current)||QUESTIONS_EN.includes(current)?questions[0]:current)},[isEnglish]);
  useEffect(()=>{fetch("/capabilities").then(async response=>{if(!response.ok)throw new Error(pick(isEnglish,"能力清单读取失败","Could not load the capability registry"));return response.json()}).then(data=>{setItems(data.items??[]);setIndex(data.index??{})}).catch(reason=>setError(reason instanceof Error?reason.message:pick(isEnglish,"能力清单读取失败","Could not load the capability registry"))).finally(()=>setLoading(false));},[isEnglish]);
  const featured=useMemo(()=>FEATURED.map(id=>items.find(item=>item.capability_id===id)).filter((item):item is Capability=>Boolean(item)),[items]);
  const visible=featured.length?featured:items.filter(item=>item.category!=="api").slice(0,9);
  async function ask(event?:FormEvent){event?.preventDefault();if(!query.trim())return;setAsking(true);setError("");try{const response=await fetch("/product-guide/ask",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query,locale})});const data=await response.json();if(!response.ok)throw new Error(data.error??pick(isEnglish,"暂时无法查询","Search is temporarily unavailable"));setAnswer(data);}catch(reason){setError(reason instanceof Error?reason.message:pick(isEnglish,"暂时无法查询","Search is temporarily unavailable"));}finally{setAsking(false)}}
  return <div className="capability-guide">
    <section className="capability-overview" data-guide="capability-overview">
      <div className="capability-positioning"><span>{pick(isEnglish,"产品定位","Product focus")}</span><h2>{pick(isEnglish,"把“看见信息”变成“知道下一步该核对什么”","Turn market information into a clear next check")}</h2><p>{pick(isEnglish,"安心看股不替用户选股票。它把行情、公告与社交说法放进同一条可追溯流程，再结合个人持仓和规则，帮助用户在行动前发现遗漏。","Market Clarity does not pick stocks for you. It connects market data, disclosures and social claims with your positions and rules, so omissions become visible before you act.")}</p><div><Link href="/demo">{pick(isEnglish,"90 秒演示","90-second demo")}<ArrowRight /></Link><Link href="/opportunity" className="secondary">{pick(isEnglish,"检查一条消息","Check a claim")}</Link></div></div>
      <div className="capability-live"><header><span><i />{pick(isEnglish,"能力索引","Capability index")}</span><strong>{index.status==="healthy"?pick(isEnglish,"同步正常","Synced"):pick(isEnglish,"正在核对","Checking")}</strong></header><div><article><strong>{index.indexed_count??"—"}</strong><span>{pick(isEnglish,"已注册能力","Registered")}</span></article><article><strong>{items.filter(item=>item.status==="available").length||"—"}</strong><span>{pick(isEnglish,"当前可用","Available")}</span></article><article><strong>{items.filter(item=>item.status==="beta").length||"—"}</strong><span>{pick(isEnglish,"测试中","In beta")}</span></article></div><footer><Database />{pick(isEnglish,"最近同步","Last synced")} {fmt(index.last_success_at,locale)}</footer></div>
    </section>

    <section className="capability-flow" id="capability-flow"><header><span>{pick(isEnglish,"核心闭环","Core workflow")}</span><strong>Information → Decision</strong></header>{[
      [Database,pick(isEnglish,"读取公开信息","Read public information"),pick(isEnglish,"行情、公告、财务与用户提供内容","Market data, disclosures, financials and user-provided content")],[Search,pick(isEnglish,"拆分证据","Separate evidence"),pick(isEnglish,"区分事实、推断和未核实说法","Distinguish facts, inferences and unverified claims")],[ShieldCheck,pick(isEnglish,"计算个人影响","Calculate personal impact"),pick(isEnglish,"持仓集中度、损失情景和规则冲突","Concentration, loss scenarios and rule conflicts")],[GitBranch,pick(isEnglish,"保留决定","Record the decision"),pick(isEnglish,"用户确认、修改或稍后复核","Confirm, revise or review later")]
    ].map(([Icon,title,detail],i)=><article key={String(title)}><span>{i+1}</span><Icon /><div><strong>{title as string}</strong><small>{detail as string}</small></div></article>)}</section>

    <section className="capability-section" id="capability-matrix" data-guide="capability-matrix"><header><div><span>{pick(isEnglish,"当前交付","Current delivery")}</span><h3>{pick(isEnglish,"能力不是一张静态路线图","A live registry, not a static roadmap")}</h3><p>{pick(isEnglish,"下列状态来自平台注册中心。新增、变更或停用能力后，知识索引会随版本更新。","Statuses come from the platform registry and update as capabilities are added, changed or disabled.")}</p></div><Link href="/workspace">{pick(isEnglish,"查看模块化工作台","Open modular workspace")}<ExternalLink /></Link></header>
      {loading?<div className="capability-loading"><LoaderCircle />{pick(isEnglish,"正在读取能力注册中心…","Loading capability registry…")}</div>:<div className="capability-grid">{visible.map(item=>{const english=FEATURED_EN[item.capability_id];return <article key={item.capability_id}><header><span className={`capability-status ${item.status}`}>{status[item.status]}</span><small>{category[item.category]??item.category}</small></header><h4>{isEnglish&&english?english[0]:item.name}</h4><p>{isEnglish&&english?english[1]:item.description}</p><footer><span>v{item.version}</span>{item.route?<Link href={item.route}>{pick(isEnglish,"打开","Open")}<ArrowRight /></Link>:<span>{fmt(item.last_updated,locale)}</span>}</footer></article>})}</div>}
    </section>

    <section className="capability-rag" id="capability-ask" data-guide="capability-ask"><div className="capability-rag-copy"><span><Sparkles />{pick(isEnglish,"能力知识库","Capability knowledge base")}</span><h3>{pick(isEnglish,"查询平台能做什么","Ask what the platform can do")}</h3><p>{pick(isEnglish,"回答会附上功能状态、使用入口、版本和更新时间。即使未连接外部模型，也可以查询平台注册的真实能力。","Answers include status, entry point, version and update time. The registry remains searchable without an external model.")}</p><div>{questions.map(item=><button key={item} onClick={()=>setQuery(item)}>{item}</button>)}</div></div><div className="capability-rag-console"><form onSubmit={ask}><label htmlFor="capability-question">{pick(isEnglish,"问一个关于产品的问题","Ask about the product")}</label><div><input id="capability-question" value={query} onChange={event=>setQuery(event.target.value)} placeholder={pick(isEnglish,"例如：没有 API Key 时可以使用哪些功能？","For example: What works without an API key?")}/><button disabled={asking}>{asking?<LoaderCircle />:<Bot />}{asking?pick(isEnglish,"检索中","Searching"):pick(isEnglish,"查询","Search")}</button></div></form>{answer?<div className="capability-answer"><header><BookOpenCheck /><strong>{pick(isEnglish,"基于当前能力索引","Based on the current capability index")}</strong></header><p>{answer.answer}</p><div className="capability-sources">{answer.sources.slice(0,5).map(source=><article key={source.capability_id}><span className={`capability-status ${source.status}`}>{status[source.status]}</span><div><strong>{source.name}</strong><small>{category[source.category]??source.category} · v{source.version} · {fmt(source.last_updated,locale)}</small></div>{source.route&&<Link href={source.route} aria-label={pick(isEnglish,`打开${source.name}`,`Open ${source.name}`)}><ExternalLink /></Link>}</article>)}</div><footer>{answer.note}</footer></div>:<div className="capability-answer-empty"><FileQuestion /><span>{pick(isEnglish,"查询后，这里会显示回答与可点击来源。","Answers and clickable sources will appear here.")}</span></div>}</div></section>

    <section className="capability-pitch"><article><span><CheckCircle2 />{pick(isEnglish,"当前可靠能力","Reliable now")}</span><ul>{(isEnglish?["Research, personal positions and pre-action checks form one workflow","Risk amounts and attribution come from rules, not model invention","Core rules-based workflows remain available without an external API key","Workspace changes are previewed, confirmed and versioned"]:["研究、个人持仓和行动前检查可以连成一条流程","风险金额与交易归因由规则计算，不由模型编造","没有外部 API Key 时仍保留规则版核心路径","所有工作台修改先预览、确认并保留版本"]).map(item=><li key={item}>{item}</li>)}</ul></article><article><span><Clock3 />{pick(isEnglish,"持续完善范围","Still improving")}</span><ul>{(isEnglish?["Broader and more resilient live-data coverage","Better recurring reviews, reminders and long-term records","Validation of which reminders matter at different usage frequencies","Consistent English and cross-page interactions"]:["扩大真实数据源的稳定性与覆盖范围","完善持续复核、提醒与长期记录体验","验证不同使用频率下最有价值的提醒方式","继续统一英文体验与跨页面交互细节"]).map(item=><li key={item}>{item}</li>)}</ul></article><aside><TriangleAlert /><div><strong>{pick(isEnglish,"能力状态不等于投资结论","Capability status is not an investment conclusion")}</strong><p>{pick(isEnglish,"“已上线”只表示功能可以使用，不代表相关数据能够预测收益，也不构成买卖建议。","“Available” only means the feature can be used. It does not imply predictive power or constitute trading advice.")}</p></div></aside></section>
    {error&&<p className="capability-error">{error}</p>}
  </div>
}
