"use client";

import {useEffect,useState} from "react";
import {ArrowRight,Check,ChevronDown,Database,FlaskConical,Gauge,RefreshCw,ShieldCheck,SlidersHorizontal,TriangleAlert,X} from "lucide-react";
import type {EngineRoute,GoalParse,UnifiedStrategyDSL} from "@/app/lib/quant-engine-router";
import {pick,useI18n} from "@/app/i18n";

type GoalResponse={goal:GoalParse;route:EngineRoute;allow_live_order:false};
type SwitchPreview={target_display_name:string;route:EngineRoute;changes:string[];requires_confirmation:true};
const examplesZh=["帮我建立一个低频 ETF 策略，每周检查一次，先模拟。","我想比较价值、动量和低波动方法，看看哪个回撤更小。","我想根据估值、波动率和成交量筛选 ETF。","我想让系统自己从数据里找规律，但只做实验。"];
const examplesEn=["Build a low-frequency ETF strategy, check it weekly, and simulate first.","Compare value, momentum and low-volatility methods to see which has the smaller drawdown.","Screen ETFs using valuation, volatility and volume.","Let the system look for patterns in the data, but keep it experimental."];
const taskZh:Record<string,string>={etf_strategy:"ETF 低频研究",stock_screening:"股票筛选",factor_research:"方法与因子比较",classic_backtest:"经典规则回测",machine_learning_research:"实验性机器学习研究",reinforcement_learning_experiment:"强化学习实验",paper_trading:"纸面模拟",portfolio_allocation:"组合配置",risk_analysis:"风险分析",social_sentiment_strategy:"社交情绪研究",event_driven_strategy:"事件研究",education_simulation:"学习模拟"};
const taskEn:Record<string,string>={etf_strategy:"Low-frequency ETF research",stock_screening:"Stock screening",factor_research:"Method and factor comparison",classic_backtest:"Classic rule backtest",machine_learning_research:"Experimental machine-learning research",reinforcement_learning_experiment:"Reinforcement-learning experiment",paper_trading:"Paper simulation",portfolio_allocation:"Portfolio allocation",risk_analysis:"Risk analysis",social_sentiment_strategy:"Social-sentiment research",event_driven_strategy:"Event research",education_simulation:"Learning simulation"};
const frequencyZh:Record<string,string>={manual:"单次运行",daily_close:"每日收盘后",weekly:"每周",monthly:"每月",event:"事件触发"};
const frequencyEn:Record<string,string>={manual:"One-time run",daily_close:"After each close",weekly:"Weekly",monthly:"Monthly",event:"Event-triggered"};
const modeZh:Record<string,string>={candidate:"先生成候选方案",backtest:"历史回测",paper:"纸面模拟",education:"学习模拟"};
const modeEn:Record<string,string>={candidate:"Generate candidates first",backtest:"Historical backtest",paper:"Paper simulation",education:"Learning simulation"};
const engineEn:Record<string,string>={native_asia_share:"Transparent A-share rules engine",backtrader:"Classic strategy engine",qlib:"Factor research engine",finrl:"Experimental learning engine",veighna:"Event simulation engine"};

export function QuantGoalRouter(){
  const {isEnglish}=useI18n();
  const examples=isEnglish?examplesEn:examplesZh,taskLabels=isEnglish?taskEn:taskZh,frequencyLabels=isEnglish?frequencyEn:frequencyZh,modeLabels=isEnglish?modeEn:modeZh;
  const [text,setText]=useState(examples[0]);const [result,setResult]=useState<GoalResponse|null>(null);const [dsl,setDsl]=useState<UnifiedStrategyDSL|null>(null);const [technical,setTechnical]=useState(false);const [switchText,setSwitchText]=useState("");const [switchPreview,setSwitchPreview]=useState<SwitchPreview|null>(null);const [busy,setBusy]=useState("");const [message,setMessage]=useState("");
  useEffect(()=>setText(current=>examplesZh.includes(current)||examplesEn.includes(current)?examples[0]:current),[isEnglish]); // eslint-disable-line react-hooks/exhaustive-deps
  const post=async(url:string,payload:Record<string,unknown>,action:string)=>{setBusy(action);setMessage("");try{const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,locale:isEnglish?"en":"zh-CN"})});const body=await response.json() as Record<string,unknown>;if(!response.ok)throw new Error(String(body.message??pick(isEnglish,"操作未完成","Action could not be completed")));return body;}catch(error){setMessage(error instanceof Error?error.message:pick(isEnglish,"操作未完成","Action could not be completed"));return null;}finally{setBusy("");}};
  const interpret=async()=>{setDsl(null);setSwitchPreview(null);const body=await post("/quant/engine/route",{goal:text},"route");if(body?.goal&&body.route)setResult(body as unknown as GoalResponse);};
  const compile=async()=>{if(!result)return;const body=await post("/quant/strategy/compile",{goal:result.goal.goal,engine:result.route.selected_engine},"compile");if(body?.strategy)setDsl(body.strategy as UnifiedStrategyDSL);};
  const previewSwitch=async()=>{if(!result||!switchText.trim())return;const body=await post("/quant/strategy/switch-engine",{goal:result.goal.goal,current_engine:result.route.selected_engine,instruction:switchText},"switch");if(body)setSwitchPreview(body as unknown as SwitchPreview);};
  const applySwitch=async()=>{if(!result||!switchPreview)return;const body=await post("/quant/strategy/switch-engine",{goal:result.goal.goal,current_engine:result.route.selected_engine,instruction:switchText,confirmed:true},"apply-switch");if(body?.applied){setResult({...result,route:body.route as EngineRoute});setSwitchPreview(null);setDsl(null);setMessage(pick(isEnglish,"研究方式已切换；请重新生成研究方案和回测。","Research method changed. Generate the plan and backtest again."));}};
  const confirmPlan=async()=>{if(!result||!dsl)return;const body=await post("/quant/tasks",{goal:result.goal.goal},"confirm-plan");if(body?.task){setMessage(pick(isEnglish,"研究任务已创建，正在打开确认与回测步骤。","Research task created. Opening confirmation and backtest steps."));window.setTimeout(()=>window.location.reload(),450);}};
  const engineName=(route:EngineRoute)=>isEnglish?(engineEn[route.selected_engine]??route.selected_engine):route.engine_display_name;
  return <section className="goal-router">
    <header className="goal-router-heading"><div><h2>{pick(isEnglish,"你想完成什么研究？","What do you want to research?")}</h2><p>{pick(isEnglish,"说清目标、资产和频率即可。平台选择研究方式，并把数据、风险和限制摆在结果旁边。","Describe the goal, asset and frequency. The platform selects a research method and keeps data, risk and limits beside the result.")}</p></div><span><ShieldCheck/>{pick(isEnglish,"回测与模拟，不连接真实账户","Backtests and simulations; no brokerage connection")}</span></header>
    <div className="goal-router-input"><textarea value={text} onChange={event=>setText(event.target.value)} maxLength={4000} aria-label={pick(isEnglish,"个人量化研究目标","Personal quant research goal")}/><button onClick={()=>void interpret()} disabled={!text.trim()||busy==="route"}>{busy==="route"?pick(isEnglish,"正在整理…","Planning…"):pick(isEnglish,"生成研究方案","Create research plan")}<ArrowRight/></button></div>
    <div className="goal-router-examples">{examples.map(item=><button key={item} onClick={()=>setText(item)}>{item}</button>)}</div>
    {message&&<div className="goal-router-message"><TriangleAlert/><span>{message}</span><button onClick={()=>setMessage("")} aria-label={pick(isEnglish,"关闭","Close")}><X/></button></div>}
    {result&&<div className="goal-router-result">
      <section className="goal-brief"><header><div><span>{pick(isEnglish,"研究方案","Research plan")}</span><h3>{taskLabels[result.goal.task_type]}</h3></div><em data-status={result.route.execution_status}>{result.route.execution_status==="ready"?pick(isEnglish,"可以继续","Ready"):result.route.execution_status==="degraded"?pick(isEnglish,"已降级","Degraded"):pick(isEnglish,"等待能力接入","Capability unavailable")}</em></header>
        <dl><div><dt>{pick(isEnglish,"研究资产","Assets")}</dt><dd>{result.goal.assets.length?result.goal.assets.join(isEnglish?", ":"、"):result.goal.asset_type==="unknown"?pick(isEnglish,"待确认","To confirm"):result.goal.asset_type.toUpperCase()}</dd></div><div><dt>{pick(isEnglish,"运行频率","Frequency")}</dt><dd>{frequencyLabels[result.goal.frequency]??result.goal.frequency}</dd></div><div><dt>{pick(isEnglish,"当前模式","Mode")}</dt><dd>{modeLabels[result.goal.mode]}</dd></div><div><dt>{pick(isEnglish,"风险边界","Risk limit")}</dt><dd>{result.goal.max_drawdown!==null?pick(isEnglish,`最大回撤 ${Math.round(result.goal.max_drawdown*100)}%`,`Max drawdown ${Math.round(result.goal.max_drawdown*100)}%`):pick(isEnglish,"待确认","To confirm")}</dd></div></dl>
        <div className="goal-plan-columns"><div><b><Database/>{pick(isEnglish,"需要的数据","Data needed")}</b>{result.goal.data_requirements.map(item=><span key={item}>{isEnglish?item.replaceAll("_"," "):item}</span>)}</div><div><b><Gauge/>{pick(isEnglish,"将进行的检查","Checks to run")}</b>{result.goal.analysis_requirements.map(item=><span key={item}>{isEnglish?item.replaceAll("_"," "):item}</span>)}</div></div>
        {result.goal.questions.length>0&&<aside className="goal-router-questions"><strong>{pick(isEnglish,"继续前只需要回答这些","Only these details are needed")}</strong>{result.goal.questions.map(item=><p key={item}>{item}</p>)}</aside>}
      </section>
      <aside className="engine-choice"><header><span>{pick(isEnglish,"系统选择","System selection")}</span><b>{engineName(result.route)}</b></header><p>{isEnglish?"The platform selected the simplest transparent engine that can satisfy this task.":result.route.selection_reason}</p>{result.route.fallback_used&&<div className="engine-fallback"><RefreshCw/><span><b>{pick(isEnglish,"已使用兼容方案","Compatible fallback used")}</b><small>{pick(isEnglish,"原计划能力不可用，只保留透明、可完整核对的规则部分。","The original capability is unavailable, so only transparent and auditable rules are retained.")}</small></span></div>}{result.route.warnings.map(item=><small className="engine-warning" key={item}>{item}</small>)}
        <button className="technical-toggle" onClick={()=>setTechnical(value=>!value)}>{pick(isEnglish,"技术详情","Technical details")}<ChevronDown className={technical?"open":undefined}/></button>
        {technical&&<div className="engine-technical"><div><span>{pick(isEnglish,"实际引擎","Engine")}</span><code>{result.route.selected_engine}</code></div><div><span>{pick(isEnglish,"复杂度","Complexity")}</span><code>{result.route.complexity}</code></div><div><span>{pick(isEnglish,"执行状态","Execution status")}</span><code>{result.route.execution_status}</code></div><div><span>{pick(isEnglish,"真实交易","Live trading")}</span><code>disabled</code></div><label><span>{pick(isEnglish,"用自然语言切换研究方式","Change research method in plain language")}</span><div><input value={switchText} onChange={event=>setSwitchText(event.target.value)} placeholder={pick(isEnglish,"例如：用传统规则，不要机器学习","For example: use transparent rules, not machine learning")}/><button onClick={()=>void previewSwitch()} disabled={!switchText.trim()||busy==="switch"}><SlidersHorizontal/>{pick(isEnglish,"预览","Preview")}</button></div></label></div>}
        <button className="goal-primary" onClick={()=>void compile()} disabled={busy==="compile"||result.goal.missing_information.length>0}><FlaskConical/>{pick(isEnglish,"生成可确认规则","Create confirmable rules")}</button>
      </aside>
      {dsl&&<section className="compiled-research"><header><div><span>{pick(isEnglish,"确认前预览","Preview before confirmation")}</span><h3>{dsl.name}</h3></div><em>{pick(isEnglish,"尚未执行","Not run")}</em></header><div><span>{pick(isEnglish,"任务","Task")}</span><b>{taskLabels[dsl.task_type]}</b></div><div><span>{pick(isEnglish,"频率","Frequency")}</span><b>{frequencyLabels[dsl.frequency]??dsl.frequency}</b></div><div><span>{pick(isEnglish,"数据","Data")}</span><b>{dsl.data_requirements.join(isEnglish?", ":"、")}</b></div><div><span>{pick(isEnglish,"成本","Costs")}</span><b>{pick(isEnglish,"佣金、印花税、过户费与滑点已预设","Commission, stamp duty, transfer fees and slippage are included")}</b></div><footer><ShieldCheck/><span>{pick(isEnglish,"确认后才可进入回测或纸面模拟；真实下单始终关闭。","Confirmation is required before backtesting or paper simulation. Live orders remain disabled.")}</span><button onClick={()=>void confirmPlan()} disabled={busy==="confirm-plan"}><Check/>{busy==="confirm-plan"?pick(isEnglish,"正在创建…","Creating…"):pick(isEnglish,"确认研究方案","Confirm plan")}</button></footer></section>}
      {switchPreview&&<section className="engine-switch-preview"><header><b>{pick(isEnglish,"研究方式切换预览","Research-method preview")}</b><em>{pick(isEnglish,"需要确认","Confirmation required")}</em></header><p>{pick(isEnglish,"拟切换为：","Switch to: ")}{engineName(switchPreview.route)}</p>{switchPreview.changes.map(item=><span key={item}>{item}</span>)}<footer><button onClick={()=>setSwitchPreview(null)}>{pick(isEnglish,"取消","Cancel")}</button><button onClick={()=>void applySwitch()} disabled={switchPreview.route.execution_status==="blocked"}>{switchPreview.route.execution_status==="blocked"?pick(isEnglish,"当前不可用","Unavailable"):pick(isEnglish,"确认切换","Confirm switch")}</button></footer></section>}
    </div>}
  </section>;
}
