import type { DataAudit, ResearchInterpretation, ResearchGoal, StrategyEvaluation } from "./types";

export function interpretResearch(evaluations:StrategyEvaluation[],goal:ResearchGoal,audit:DataAudit):ResearchInterpretation{
  const ai=evaluations.filter(item=>item.strategy.source==="constrained_ai");const survivors=ai.filter(item=>item.status==="limited_candidate");const lockedFailed=ai.filter(item=>item.status==="locked_failed");const costEroded=ai.filter(item=>(item.validation.cost_impact_pct??0)>Math.max(1,Math.abs(item.validation.net_return_pct??0)));
  const best=survivors[0];let status:ResearchInterpretation["status"]="limited_historical_improvement";
  if(audit.coverage_pct<80)status="insufficient_data";else if(!survivors.length&&lockedFailed.length)status="failed_locked_test";else if(!survivors.length)status="no_candidate_survived";else if(costEroded.includes(best))status="eroded_by_costs";else if(goal==="lower_drawdown"&&(best.locked_test?.net_return_pct??0)<=0)status="improved_drawdown_only";else if((best.locked_test?.positive_period_ratio??0)<.5)status="unstable_across_periods";
  const headline=status==="insufficient_data"?"数据覆盖不足，本次不生成正面历史结论。":status==="failed_locked_test"?"验证区曾优于传统对照的候选，在锁定测试中未延续。":status==="no_candidate_survived"?"没有候选在验证区按本次目标优于传统对照，锁定历史未打开。":status==="eroded_by_costs"?"候选的历史差异大部分被假设交易成本侵蚀。":status==="improved_drawdown_only"?"候选降低了部分历史回撤，但成本后表现没有同步改善。":status==="unstable_across_periods"?"候选在不同历史阶段的结果不够一致。":`有 ${survivors.length} 个候选先在验证区按目标优于传统对照，并在锁定历史测试中仍延续；结论仅限本次样本。`;
  const reference=best??lockedFailed[0]??ai[0];const locked=reference?.locked_test;
  return {status,headline,evidence:[`系统共提出 ${ai.length} 个受控改动，${ai.filter(item=>item.status==="validation_rejected"||item.status==="research_rejected"||item.status==="precheck_rejected").length} 个在锁定测试前被淘汰。`,locked?`锁定测试包含 ${locked.periods} 个非重叠观察期，成本后历史表现 ${locked.net_return_pct===null?"数据不足":`${locked.net_return_pct}%`}，最大回撤 ${locked.max_drawdown_pct===null?"数据不足":`${locked.max_drawdown_pct}%`}。`:`没有候选形成可解释的锁定测试结果。`,`本次加载 ${audit.loaded_symbols}/${audit.requested_symbols} 只股票，覆盖率 ${audit.coverage_pct}%，数据状态为 ${audit.status}。`],improvement:best?goal==="lower_drawdown"?"主要观察到的改善是历史回撤约束。":goal==="lower_turnover"?"主要观察到的改善是换手和成本控制。":"候选在部分历史阶段更符合预先确认的研究目标。":"没有候选同时超过最低门槛和目标相关的传统对照。",tradeoff:reference?`平均约 ${reference.validation.turnover_pct??"—"}% 的持仓会在每次调整时更换；扣除模拟交易费用后，历史结果减少约 ${reference.validation.cost_impact_pct??"—"} 个百分点。`:"当前无法比较调整频率和费用影响。",limitation:audit.limitations[0]??"历史样本不能代表未来。",next_step:survivors.length?"可保存方法，待获得更新且合规的数据后重新检验；不要据此生成当前股票名单。":"可以更换预设样本或候选预算后创建新版本，但不要持续生成直到出现成功结果。",cannot_conclude:["不能说明未来表现会延续。","不能据此选择当前应买入或卖出的股票。","不能把固定样本结果推广为全 A 股结论。"]};
}
