import { deriveResearchSplit, evaluateSensitivity, evaluateStrategy } from "./backtest-engine";
import { loadCustomResearchHistory, loadFixedResearchSnapshot } from "./data-provider";
import { interpretResearch } from "./interpretation";
import { candidateFingerprint, generateCandidates } from "./planner";
import { traditionalBenchmarks } from "./catalog";
import { confirmationHash, symbolsFor, validateResearchSettings, validateStrategyDSL } from "./strategy-dsl";
import type { DataAudit, ResearchGoal, ResearchInterpretation, ResearchRun, StrategyEvaluation, StrategyPlan } from "./types";

function objectiveValue(item:StrategyEvaluation,goal:ResearchGoal,segment:"validation"|"locked_test"="validation"){const m=segment==="locked_test"?item.locked_test:item.validation;if(!m)return -999;if(goal==="lower_drawdown")return m.max_drawdown_pct??-999;if(goal==="higher_stability")return m.stability_pct??-999;if(goal==="lower_turnover")return -(m.turnover_pct??999);if(goal==="higher_net_return")return m.net_return_pct??-999;return (m.net_return_pct??-999)+(m.max_drawdown_pct??-999)*.6;}
function metricLabel(goal:ResearchGoal){return goal==="lower_drawdown"?"最大回撤":goal==="higher_stability"?"阶段稳定性":goal==="lower_turnover"?"换手率":goal==="higher_net_return"?"成本后表现":"收益与回撤平衡";}
function relativeGate(candidate:StrategyEvaluation,reference:StrategyEvaluation,goal:ResearchGoal,segment:"validation"|"locked_test"="validation"){
  const metrics=segment==="locked_test"?candidate.locked_test:candidate.validation;const candidateValue=objectiveValue(candidate,goal,segment),referenceValue=objectiveValue(reference,goal,segment);const area=segment==="validation"?"验证区":"锁定测试区";
  const guards=[{pass:(metrics?.positive_period_ratio??0)>=.4,reason:"正向时期比例不足 40%"},{pass:(metrics?.concentration_pct??100)<=75,reason:"结果过度集中在少数时期"},{pass:(metrics?.turnover_pct??999)<=80,reason:"平均每次换手超过 80%，执行负担过高"},{pass:(metrics?.cost_impact_pct??999)<=8,reason:"交易成本影响过大"},{pass:segment==="locked_test"||candidate.sensitivity_passed,reason:"相邻参数敏感性检查未通过"}];
  const failed=guards.find(item=>!item.pass);const pass=candidateValue>referenceValue&&!failed;return {pass,reason:pass?`${area}的${metricLabel(goal)}优于固定参照“${reference.strategy.name}”，且成本、集中度、换手和敏感性护栏均通过。`:failed?`${area}${failed.reason}，因此不标记为通过。`:`${area}的${metricLabel(goal)}没有优于固定参照“${reference.strategy.name}”${segment==="validation"?"，因此不打开锁定测试":"，因此不标记为通过"}。`};
}

function interpretFixedRecheck(original:StrategyEvaluation,reference:StrategyEvaluation,goal:ResearchGoal,audit:DataAudit):ResearchInterpretation{
  const locked=original.locked_test;const passed=original.status==="limited_candidate";const insufficient=audit.coverage_pct<80||["precheck_rejected","research_rejected"].includes(original.status)||original.research.periods===0||original.validation.periods===0||!locked||locked.periods===0;const status:ResearchInterpretation["status"]=insufficient?"insufficient_data":passed?"fixed_recheck_passed":"fixed_recheck_not_passed";
  const headline=insufficient?"已尝试按原规则重算，但股票覆盖或历史长度不足，不能把“没有结果”写成“方法未通过”。":passed?`已按原规则重算三段历史；验证区和锁定检查都达到相对“${reference.strategy.name}”的预设标准。`:`已按原规则重算三段历史；该方法没有同时通过验证区和锁定检查的预设标准。`;
  return {status,headline,evidence:["本次只重新检验已保存规则及服务端固定传统对照，没有生成或挑选新的 AI 候选。",`相对传统对照的判定：${original.reason}`,locked?.periods?`锁定检查已实际运行 ${locked.periods} 个观察期；成本后历史结果 ${locked.net_return_pct===null?"数据不足":`${locked.net_return_pct}%`}，最大回撤 ${locked.max_drawdown_pct===null?"数据不足":`${locked.max_drawdown_pct}%`}。`:"历史长度不足，锁定检查没有形成可计算观察期；这不能说明方法已失效。",`本次加载 ${audit.loaded_symbols}/${audit.requested_symbols} 只股票，覆盖率 ${audit.coverage_pct}%，数据状态为 ${audit.status}。`],improvement:insufficient?"本次证据不足，不能判断原方法是否仍有优势。":passed?`在本次固定历史样本与预设“${metricLabel(goal)}”标准下，原方法相对传统对照的方向仍延续。`:"本次重检没有证明原方法相对传统对照仍有稳定优势。",tradeoff:`本次保持原股票样本、规则、调仓和成本假设不变；没有为适配新数据而修改参数。`,limitation:audit.limitations[0]??"历史样本不能代表未来。",next_step:insufficient?"补足历史与样本覆盖后按同一规则重检，不要把本次空结果当作证伪。":passed?"可保留为研究证据，并在数据更新后继续按同一规则重检。":"保留本次未通过记录；如需修改规则，应复制为新版本后重新确认，而不是覆盖原版本。",cannot_conclude:["不能说明未来表现会延续。","不能据此选择当前应买入或卖出的股票。","不能把固定样本结果推广为全 A 股结论。"]};
}

export async function runResearch(input:{plan:StrategyPlan;confirmation_hash:string;confirmed:boolean;attempts_total?:number;partialSymbols?:string[];stale?:boolean;data_mode?:"demo"|"live";excluded_candidate_fingerprints?:string[];candidate_offset?:number;loaded_data?:Awaited<ReturnType<typeof loadCustomResearchHistory>>;fixed_only?:boolean}):Promise<ResearchRun>{
  if(!input.confirmed)throw new Error("运行策略研究前必须确认当前草案");
  const checked=validateStrategyDSL(input.plan.dsl);if(!checked.valid)throw new Error(checked.errors.join("；"));
  const settingsChecked=validateResearchSettings(input.plan.research_settings);if(!settingsChecked.valid)throw new Error(settingsChecked.errors.join("；"));
  if(input.fixed_only?input.plan.dsl.source==="traditional":!["user","template"].includes(input.plan.dsl.source))throw new Error("主研究对象来源无效；系统候选和传统对照只能由服务端生成");
  const expected=await confirmationHash(input.plan.dsl,input.plan.dsl.research_goal,input.plan.research_settings);if(expected!==input.confirmation_hash||expected!==input.plan.confirmation_hash)throw new Error("策略内容已变化，旧确认已失效，请重新确认");
  const symbols=[...symbolsFor(input.plan.dsl)];const {series,audit}=input.loaded_data??(input.data_mode==="live"&&input.plan.dsl.universe.mode==="custom"?await loadCustomResearchHistory(symbols):loadFixedResearchSnapshot({partialSymbols:input.partialSymbols,stale:input.stale,symbols,universeId:input.plan.dsl.universe.id}));const split=deriveResearchSplit(series);const excluded=new Set(input.excluded_candidate_fingerprints??[]);const offset=Math.max(0,Math.floor(input.candidate_offset??0));const requested=input.plan.research_settings.candidate_budget;const candidatePool=generateCandidates(input.plan,5000);const skippedCandidates=candidatePool.filter(item=>excluded.has(candidateFingerprint(item)));const availableCandidates=input.fixed_only?[]:offset?candidatePool.slice(offset):candidatePool.filter(item=>!excluded.has(candidateFingerprint(item)));const ai=availableCandidates.slice(0,requested);
  const serverBenchmarks=traditionalBenchmarks(input.plan.dsl.research_goal,{universe:input.plan.dsl.universe,portfolio:input.plan.dsl.portfolio,rebalance:input.plan.dsl.rebalance,costs:input.plan.dsl.costs});if(!serverBenchmarks.length)throw new Error("无法建立有效的传统对照");for(const benchmark of serverBenchmarks){const valid=validateStrategyDSL(benchmark);if(!valid.valid)throw new Error(`传统对照无效：${valid.errors.join("；")}`);}const base=[input.plan.dsl,...serverBenchmarks];let fixedEvaluations=base.map(strategy=>evaluateStrategy(strategy,series,input.fixed_only===true,split));
  const goal=input.plan.dsl.research_goal;const traditional=fixedEvaluations.filter(item=>item.strategy.source==="traditional").sort((a,b)=>objectiveValue(b,goal)-objectiveValue(a,goal));const equalWeight=traditional.find(item=>item.strategy.id==="benchmark-equal");const reference=input.plan.research_settings.comparison_gate==="goal_relative_equal_weight"?(equalWeight??traditional[0]??fixedEvaluations[0]):(traditional[0]??fixedEvaluations[0]);
  if(input.fixed_only){const original=fixedEvaluations[0];if(original.status==="limited_candidate"){const sensitive={...original,sensitivity_passed:evaluateSensitivity(original.strategy,series,split)};const validationGate=relativeGate(sensitive,reference,goal);let checkedOriginal:StrategyEvaluation=validationGate.pass?sensitive:{...sensitive,status:"validation_rejected",reason:validationGate.reason};if(validationGate.pass){const lockedGate=relativeGate(sensitive,reference,goal,"locked_test");checkedOriginal=lockedGate.pass?{...sensitive,status:"limited_candidate",reason:`按原规则重检后，验证区和锁定区的${metricLabel(goal)}都优于同条件传统对照。`}:{...sensitive,status:"locked_failed",reason:lockedGate.reason};}fixedEvaluations=[checkedOriginal,...fixedEvaluations.slice(1)];}}
  const rounds:ResearchRun["rounds"]=[];const relativeEvaluations:StrategyEvaluation[]=[];const attemptedCandidates:typeof ai=[];let rejected=0;let validationWinners:StrategyEvaluation[]=[];let selected:StrategyEvaluation[]=[];const batchSize=50;const target=input.plan.research_settings.target_candidates;const exhaustBudget=input.plan.research_settings.search_mode==="exhaust_budget";const totalBatches=Math.ceil(ai.length/batchSize);
  for(let round=1;round<=totalBatches;round++){
    const batch=ai.slice((round-1)*batchSize,round*batchSize);if(!batch.length)break;attemptedCandidates.push(...batch);const validBatch=batch.filter(item=>validateStrategyDSL(item).valid);rejected+=batch.length-validBatch.length;
    const evaluated=validBatch.map(strategy=>evaluateStrategy(strategy,series,false,split)).map(item=>{if(item.status!=="limited_candidate")return item;const sensitive=evaluateSensitivity(item.strategy,series,split);const checkedItem={...item,sensitivity_passed:sensitive};const gate=relativeGate(checkedItem,reference,goal);return gate.pass?{...checkedItem,reason:gate.reason}:{...checkedItem,status:"validation_rejected" as const,reason:gate.reason};});
    relativeEvaluations.push(...evaluated);const passed=evaluated.filter(item=>item.status==="limited_candidate");validationWinners=[...validationWinners,...passed].sort((a,b)=>objectiveValue(b,goal)-objectiveValue(a,goal));const reachedTarget=validationWinners.length>=target;const reachedLimit=round===totalBatches;const stop=reachedLimit||(!exhaustBudget&&reachedTarget);
    rounds.push({round,generated:batch.length,passed_validation:validationWinners.length,stopped:stop,reason:reachedTarget&&!exhaustBudget?`已累计找到 ${validationWinners.length}/${target} 个验证区合格候选，停止后续批次并统一打开一次锁定测试。`:reachedLimit?`已用完本次 ${requested} 组预算，累计找到 ${validationWinners.length}/${target} 个验证区合格候选。`:`第 ${round} 批结束，累计 ${validationWinners.length}/${target} 个验证区合格候选；继续下一批未测试组合。`});
    if(stop){const slots=Math.min(target,input.plan.research_settings.locked_slots);selected=exhaustBudget||reachedTarget?validationWinners.slice(0,slots):[];break}
  }
  if(exhaustBudget&&!selected.length&&validationWinners.length)selected=validationWinners.slice(0,Math.min(target,input.plan.research_settings.locked_slots));
  if(selected.length)fixedEvaluations=base.map(strategy=>evaluateStrategy(strategy,series,true,split));
  const openedReference=fixedEvaluations.find(item=>item.strategy.id===reference.strategy.id)??reference;
  const selectedIds=new Set(selected.map(item=>item.strategy.id));const aiEvaluations=relativeEvaluations.map(item=>{if(!selectedIds.has(item.strategy.id))return item.status==="limited_candidate"?{...item,status:"validation_rejected" as const,reason:`已优于传统对照，但未进入本次统一最后检查名额。`}:item;const opened={...evaluateStrategy(item.strategy,series,true,split),sensitivity_passed:item.sensitivity_passed};if(opened.status!=="limited_candidate")return opened;const lockedGate=relativeGate(opened,openedReference,goal,"locked_test");return lockedGate.pass?{...opened,reason:`验证区和锁定测试区的${metricLabel(goal)}都优于“${reference.strategy.name}”，且稳定性护栏通过。`}:{...opened,status:"locked_failed" as const,reason:lockedGate.reason};});
  const attempted=attemptedCandidates.length;const candidateSpaceExhausted=!input.fixed_only&&attempted===ai.length&&ai.length===availableCandidates.length;const finalCount=aiEvaluations.filter(item=>item.status==="limited_candidate").length;const finalistIds=new Set(selected.map(item=>item.strategy.id));const closestRejected=aiEvaluations.filter(item=>!finalistIds.has(item.strategy.id)).sort((a,b)=>objectiveValue(b,goal)-objectiveValue(a,goal)).slice(0,6);const displayedCandidates=aiEvaluations.filter(item=>finalistIds.has(item.strategy.id)).concat(closestRejected);const evaluations=[...fixedEvaluations,...displayedCandidates];
  const funnel=[{id:"generated",label:"批量扫描受控组合",count:attempted,reasons:[candidateSpaceExhausted?`候选空间已扫描完；本次新增 ${attempted} 组，历史账本已测试 ${offset} 组。必须修改研究条件才能产生新组合。`:`本次扫描 ${attempted} 组新组合；从历史账本跳过 ${offset||skippedCandidates.length} 组已测试组合。`]},{id:"precheck",label:"最低数据与规则门槛",count:relativeEvaluations.filter(item=>item.status!=="precheck_rejected").length,reasons:rejected?[`${rejected} 个因 DSL 或参数规则被拒绝`]:[]},{id:"validation",label:"验证区优于传统对照",count:selected.length,reasons:aiEvaluations.filter(x=>x.status==="validation_rejected"||x.status==="research_rejected").slice(0,8).map(x=>`${x.strategy.name}：${x.reason}`)},{id:"locked",label:"统一打开最后检查",count:selected.length,reasons:selected.length?[`验证区达到目标或预算结束后，本次排名前 ${selected.length} 个候选统一查看最后一段历史；打开后本研究条件永久封存。`]:[candidateSpaceExhausted?"允许的候选组合已经全部检查完，没有打开最后一段历史；请修改股票样本、策略规则或参数范围。":"本次预算内没有候选通过验证，所有方法的最后一段历史都保持未使用；下次可从未测试组合继续。"]},{id:"survived",label:"最后仍优于传统对照",count:finalCount,reasons:aiEvaluations.filter(x=>x.status==="locked_failed").slice(0,8).map(x=>`${x.strategy.name}：${x.reason}`)}];
  const fixedOriginal=fixedEvaluations[0];const hasFixedLockedEvidence=Boolean(fixedOriginal.locked_test?.periods);const outputFunnel=input.fixed_only?[{id:"generated",label:"读取已保存规则",count:1,reasons:["没有生成新的 AI 候选，也没有改写原规则。"]},{id:"precheck",label:"规则与数据预检",count:fixedOriginal.status==="precheck_rejected"?0:1,reasons:fixedOriginal.status==="precheck_rejected"?[fixedOriginal.reason]:[]},{id:"validation",label:"统一验证区比较",count:fixedOriginal.status==="research_rejected"||fixedOriginal.validation.periods===0?0:1,reasons:[fixedOriginal.reason]},{id:"locked",label:"重新计算锁定检查",count:hasFixedLockedEvidence?1:0,reasons:[hasFixedLockedEvidence?"锁定区已实际形成可计算结果；结果不会用于继续修改本策略。":"历史长度不足，锁定区没有形成可计算观察期；这不等于方法已被证伪。"]},{id:"survived",label:"原方法是否仍达标",count:fixedOriginal.status==="limited_candidate"?1:0,reasons:[fixedOriginal.reason]}]:funnel;const interpretation=input.fixed_only?interpretFixedRecheck(fixedOriginal,reference,goal,audit):interpretResearch(aiEvaluations,input.plan.dsl.research_goal,audit);const referenceRule=input.plan.research_settings.comparison_gate==="goal_relative_equal_weight"?"用户明确指定的同股票样本等权持有":"目标相关的最佳传统方法";const comparisonRule=input.fixed_only?`已保存方法保持规则不变，使用同一股票样本、日期、组合、调仓和成本，与服务端固定传统对照分别计算研究区、验证区和锁定检查；重检结果不得用于回写参数。`:`候选必须先达到最低数据门槛，并在统一日期的验证区按“${metricLabel(goal)}”优于${referenceRule}，同时通过成本、集中度、换手和相邻参数护栏；进入锁定测试后仍按同一目标优于同一对照，才标记为通过。`;const now=new Date().toISOString();return {id:`run-${crypto.randomUUID()}`,plan_id:input.plan.plan_id,confirmation_hash:expected,confirmed_at:now,locked_at:input.fixed_only?(hasFixedLockedEvidence?now:null):(selected.length?now:null),created_at:now,engine_version:"strategy-research-engine-v1",method_version:"three-stage-harness-v6",research_settings:input.plan.research_settings,planning_trace:input.plan.planning_trace,data_audit:audit,split,candidates_generated:attempted,candidates_skipped:input.fixed_only?0:offset||skippedCandidates.length,candidate_fingerprints:attemptedCandidates.map(candidateFingerprint),candidate_space_exhausted:candidateSpaceExhausted,attempts_total:input.attempts_total??1,rounds,evaluations,funnel:outputFunnel,interpretation,comparison_standard:{benchmark_strategy_id:reference.strategy.id,benchmark_name:reference.strategy.name,rule:comparisonRule},allow_live_order:false};
}
