"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import {
  Braces,Check,Copy,Database,Download,Eye,EyeOff,GripVertical,History,
  LayoutDashboard,LockKeyhole,Palette,Plus,Redo2,Save,Settings2,Share2,ShieldCheck,
  Sparkles,Star,Trash2,Undo2,Upload,X,
} from "lucide-react";

import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {
  DASHBOARD_DATA_SOURCES,DASHBOARD_MODULE_REGISTRY,
  createDashboardWorkspace,normalizeDashboardWorkspace,
  validateDashboardWorkspace,type DashboardModule,type DashboardPatch,
  type DashboardDataSource,type DashboardModuleTemplate,type DashboardPatchChange,type DashboardVersion,type DashboardWorkspace,type RefreshPolicy,
} from "@/app/lib/dashboard-system";
import {createWorkspace,MODULE_LABELS,type ModuleType,type Workspace} from "@/app/lib/personal-workbench";

type Props={workspace:Workspace;workspaces:Workspace[]};
type Panel="modules"|"module"|"appearance"|"agent"|"json"|"versions"|"sources"|"privacy";
type ApiMessage={message?:string};

const refreshLabel=(policy:RefreshPolicy)=>policy.mode==="manual"?"手动更新":policy.mode==="event"?"事件触发":`每 ${policy.interval??"1h"}`;
const sourceStatus=(sourceId:string,sources:DashboardDataSource[]=DASHBOARD_DATA_SOURCES)=>sources.find(item=>item.sourceId===sourceId);
const categoryLabel={portfolio:"组合",research:"研究",risk:"风险",quant:"量化",education:"学习",workflow:"流程"} as const;
const newPosition=(modules:DashboardModule[])=>({x:0,y:modules.reduce((max,item)=>Math.max(max,item.position.y+item.position.h),0),w:6,h:3});
const changeLabel=(change:DashboardPatchChange)=>{
  if(change.action==="add_module")return `添加 ${MODULE_LABELS[change.moduleId]}`;
  if(change.action==="set_theme")return "调整视觉主题";
  if(change.action==="rename_workspace")return `重命名为“${change.value}”`;
  const moduleId="instanceId" in change?change.instanceId:"";
  const target=moduleId?moduleId.split("-").slice(0,-1).join("-") as ModuleType:undefined;
  const label=target&&MODULE_LABELS[target]||moduleId;
  return ({remove_module:"删除",hide_module:"隐藏",show_module:"显示",duplicate_module:"复制",move_module:"移动",resize_module:"调整大小",set_refresh:"修改刷新",set_data_source:"更换数据源",set_parameters:"修改参数"} as Record<string,string>)[change.action]+` ${label}`;
};
const modulePreview=(type:ModuleType,available:boolean)=>{
  const previews:Partial<Record<ModuleType,{eyebrow:string;value:string;items:string[];action:string;href:string}>>={
    portfolio_overview:{eyebrow:"组合状态",value:"导入后计算",items:["总资产","最大持仓","行业集中"],action:"打开我的组合",href:"/portfolio"},
    portfolio_risk:{eyebrow:"风险扫描",value:"等待持仓",items:["集中度","回撤","流动性"],action:"导入持仓",href:"/portfolio"},
    etf_overlap:{eyebrow:"底层重合",value:"选择 ETF",items:["重仓股","行业","主题"],action:"开始 ETF 诊断",href:"/etf-tool"},
    financial_quality:{eyebrow:"财务核对",value:"输入股票",items:["利润质量","现金流","负债"],action:"打开股票研究",href:"/analysis"},
    valuation:{eyebrow:"估值位置",value:"暂无标的",items:["PE","PB","历史分位"],action:"选择研究标的",href:"/analysis"},
    social_risk:{eyebrow:"内容核验",value:"粘贴一条说法",items:["来源","事实","情绪压力"],action:"检查一条消息",href:"/opportunity"},
    trade_review:{eyebrow:"交易行为",value:"导入交易记录",items:["追高","补仓","频率"],action:"开始交易复盘",href:"/trade-tool"},
    pretrade_checklist:{eyebrow:"交易前检查",value:"4 项待填写",items:["标的与金额","理由","退出条件"],action:"开始机会检查",href:"/opportunity"},
    investment_goal:{eyebrow:"个人目标",value:"尚未设置",items:["期限","用途","投入节奏"],action:"设置我的规则",href:"/profile"},
    risk_tolerance:{eyebrow:"个人边界",value:"尚未确认",items:["单股上限","可承受损失","冷静期"],action:"设置风险边界",href:"/profile"},
    simulation_portfolio:{eyebrow:"模拟组合",value:"0 个标的",items:["不接券商","可随时重置","仅作模拟"],action:"创建模拟持仓",href:"/portfolio"},
    term_explainer:{eyebrow:"概念解释",value:"输入一个术语",items:["一句话解释","为何重要","如何核对"],action:"打开 AI 助手",href:"/agent"},
    quant_backtest:{eyebrow:"历史模拟",value:"等待规则与数据",items:["基准","成本","样本外"],action:"打开量化研究",href:"/quant"},
  };
  return previews[type]??{eyebrow:available?"模块已连接":"数据未配置",value:available?"等待输入":"选择数据源",items:["来源时间","计算口径","结果状态"],action:"打开相关工具",href:"/analysis"};
};

export function DashboardEditor({workspace,workspaces}:Props){
  const [draft,setDraft]=useState(()=>normalizeDashboardWorkspace(workspace));
  const [saved,setSaved]=useState(()=>normalizeDashboardWorkspace(workspace));
  const [mode,setMode]=useState<"edit"|"view">("edit");
  const [panel,setPanel]=useState<Panel>("modules");
  const [selectedId,setSelectedId]=useState<string>();
  const [instruction,setInstruction]=useState("把持仓风险放到顶部，隐藏技术图表，每小时更新社交热点。");
  const [preview,setPreview]=useState<DashboardPatch>();
  const [jsonText,setJsonText]=useState(()=>JSON.stringify(normalizeDashboardWorkspace(workspace),null,2));
  const [jsonErrors,setJsonErrors]=useState<string[]>([]);
  const [versions,setVersions]=useState<DashboardVersion[]>([]);
  const [message,setMessage]=useState("");
  const [moduleSearch,setModuleSearch]=useState("");
  const [dataSources,setDataSources]=useState<DashboardDataSource[]>(DASHBOARD_DATA_SOURCES);
  const [moduleTemplates,setModuleTemplates]=useState<DashboardModuleTemplate[]>([]);
  const [busy,setBusy]=useState(false);
  const [dragging,setDragging]=useState<string>();
  const [privacy,setPrivacy]=useState({savePortfolio:false,saveTrades:false,saveAIConversation:false,saveBacktests:true,saveSocialContent:false,allowExternalModels:false,localModelsOnly:false,retentionDays:30});
  const fileRef=useRef<HTMLInputElement>(null);
  const gridRef=useRef<HTMLDivElement>(null);
  const selected=draft.modules.find(item=>item.instanceId===selectedId);
  const dirty=JSON.stringify(draft)!==JSON.stringify(saved);
  const visible=draft.modules.filter(item=>item.visible).sort((a,b)=>a.position.y-b.position.y||a.position.x-b.position.x);
  const hidden=draft.modules.filter(item=>!item.visible);
  const catalog=DASHBOARD_MODULE_REGISTRY.filter(item=>`${item.name}${item.description}${categoryLabel[item.category]}`.toLowerCase().includes(moduleSearch.trim().toLowerCase()));
  const loadVersions=useCallback((workspaceId:string)=>fetch(`/workspaces/${workspaceId}/versions`,{cache:"no-store"}).then(response=>response.ok?response.json():{}).then((body:{versions?:DashboardVersion[]})=>setVersions(body.versions??[])),[]);

  useEffect(()=>{void loadVersions(draft.id);void fetch("/api/privacy/settings",{cache:"no-store"}).then(response=>response.ok?response.json():{}).then((body:{privacy?:typeof privacy})=>body.privacy&&setPrivacy(body.privacy));void fetch("/data-sources",{cache:"no-store"}).then(response=>response.ok?response.json():{}).then((body:{data_sources?:DashboardDataSource[]})=>body.data_sources&&setDataSources(body.data_sources));void fetch("/module-templates",{cache:"no-store"}).then(response=>response.ok?response.json():{}).then((body:{templates?:DashboardModuleTemplate[]})=>setModuleTemplates(body.templates??[]));},[draft.id,loadVersions]);

  const notify=()=>window.dispatchEvent(new CustomEvent("anxin:snapshot-updated"));
  const request=async(url:string,options:RequestInit)=>{setBusy(true);setMessage("");try{const response=await fetch(url,options);const body=await response.json() as ApiMessage&{workspace?:DashboardWorkspace;url?:string;status?:string};if(!response.ok)throw new Error(body.message||"操作未完成");if(body.workspace){setDraft(body.workspace);setSaved(body.workspace);setJsonText(JSON.stringify(body.workspace,null,2));await loadVersions(body.workspace.id);}setMessage(body.message||"已保存");notify();return body;}catch(error){setMessage(error instanceof Error?error.message:"操作未完成");return undefined;}finally{setBusy(false);}};
  const save=()=>request(`/workspaces/${draft.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({workspace:draft,source:"manual",summary:"手工编辑工作台",confirmed:true})});
  const perform=async(action:"undo"|"redo")=>request(`/workspaces/${draft.id}/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true})});
  const applyPreview=async()=>{if(!preview)return;const result=await request("/agent/workspace/apply",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspace_id:draft.id,patch:preview,confirmed:true})});if(result)setPreview(undefined);};
  const makePreview=async()=>{setBusy(true);setMessage("");try{const response=await fetch("/agent/workspace/preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspace_id:draft.id,instruction})});const body=await response.json() as {patch?:DashboardPatch;message?:string};if(!response.ok||!body.patch)throw new Error(body.message||"无法生成预览");setPreview(body.patch);setPanel("agent");}catch(error){setMessage(error instanceof Error?error.message:"无法生成预览");}finally{setBusy(false);}};
  const addModule=(moduleId:ModuleType)=>{const definition=DASHBOARD_MODULE_REGISTRY.find(item=>item.moduleId===moduleId)!;const position=newPosition(draft.modules);const instanceId=`${moduleId}-${crypto.randomUUID().slice(0,8)}`;setDraft({...draft,modules:[...draft.modules,{type:moduleId,instanceId,visible:true,order:draft.modules.length,width:definition.uiSchema.defaultWidth===12?"full":"half",density:draft.density,position:{...position,w:definition.uiSchema.defaultWidth,h:definition.uiSchema.defaultHeight},locked:false,dataSourceId:definition.dataSources[0]??"workspace_state",refreshPolicy:{mode:"manual",timezone:"Asia/Shanghai"},parameters:{}}]});setSelectedId(instanceId);setPanel("module");};
  const updateSelected=(patch:Partial<DashboardModule>)=>selected&&setDraft({...draft,modules:draft.modules.map(item=>item.instanceId===selected.instanceId?{...item,...patch}:item)});
  const removeSelected=()=>{if(!selected)return;setDraft({...draft,modules:draft.modules.filter(item=>item.instanceId!==selected.instanceId)});setSelectedId(undefined);setPanel("modules");};
  const duplicateSelected=()=>{if(!selected)return;const copy=structuredClone(selected);copy.instanceId=`${copy.type}-${crypto.randomUUID().slice(0,8)}`;copy.title=copy.title?`${copy.title} 副本`:undefined;copy.position={...copy.position,x:Math.min(12-copy.position.w,copy.position.x+1),y:copy.position.y+1};setDraft({...draft,modules:[...draft.modules,copy]});setSelectedId(copy.instanceId);};
  const dropModule=(event:React.DragEvent)=>{event.preventDefault();if(!dragging||!gridRef.current)return;const item=draft.modules.find(row=>row.instanceId===dragging);if(!item||item.locked)return;const rect=gridRef.current.getBoundingClientRect();const x=Math.max(0,Math.min(12-item.position.w,Math.floor((event.clientX-rect.left)/rect.width*12)));const y=Math.max(0,Math.round((event.clientY-rect.top)/(draft.layout.rowHeight+draft.layout.gap)));updateModule(dragging,{position:{...item.position,x,y}});setDragging(undefined);};
  const startResize=(event:React.PointerEvent,module:DashboardModule)=>{event.preventDefault();event.stopPropagation();if(module.locked||!gridRef.current)return;const startX=event.clientX,startY=event.clientY,start={...module.position};const rect=gridRef.current.getBoundingClientRect();const col=(rect.width-draft.layout.gap*11)/12,row=draft.layout.rowHeight+draft.layout.gap;const move=(pointer:PointerEvent)=>{const w=Math.max(3,Math.min(12-start.x,Math.round(start.w+(pointer.clientX-startX)/(col+draft.layout.gap))));const h=Math.max(2,Math.min(12,Math.round(start.h+(pointer.clientY-startY)/row)));updateModule(module.instanceId,{position:{...start,w,h}});};const stop=()=>{document.removeEventListener("pointermove",move);document.removeEventListener("pointerup",stop);};document.addEventListener("pointermove",move);document.addEventListener("pointerup",stop);};
  const updateModule=(id:string,patch:Partial<DashboardModule>)=>setDraft(current=>({...current,modules:current.modules.map(item=>item.instanceId===id?{...item,...patch}:item)}));
  const validateJson=()=>{try{const parsed=JSON.parse(jsonText);const result=validateDashboardWorkspace(parsed);if(!result.valid){setJsonErrors(result.errors);return;}setJsonErrors([]);setDraft(result.workspace);setMessage("配置有效，尚未保存");}catch(error){setJsonErrors([error instanceof Error?error.message:"JSON 无法解析"]);}};
  const importJson=(file?:File)=>{if(!file)return;void file.text().then(text=>{setJsonText(text);setPanel("json");setMessage("已读取文件，请验证后应用");});};
  const exportJson=()=>{const blob=new Blob([JSON.stringify(draft,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`${draft.name}.dashboard.json`;link.click();URL.revokeObjectURL(url);};
  const savePrivacy=()=>request("/api/privacy/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({settings:privacy,confirmed:true})});
  const share=async()=>{const result=await request(`/workspaces/${draft.id}/share`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true})});if(result?.url){await navigator.clipboard?.writeText(`${location.origin}${result.url}`);setMessage("只读分享链接已复制；内容仅包含工作台配置");}};
  const createFromTemplate=(template:string)=>{const configured=normalizeDashboardWorkspace(createWorkspace(template));void request("/workspaces",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspace:configured,confirmed:true})});};
  const addFromModuleTemplate=(template:DashboardModuleTemplate)=>{const moduleItem=structuredClone(template.module);moduleItem.instanceId=`${moduleItem.type}-${crypto.randomUUID().slice(0,8)}`;moduleItem.position={...moduleItem.position,...newPosition(draft.modules)};setDraft({...draft,modules:[...draft.modules,moduleItem]});setSelectedId(moduleItem.instanceId);setPanel("module");};
  const saveModuleTemplate=async(module:DashboardModule)=>{const name=window.prompt("给这个模块模板命名",module.title||MODULE_LABELS[module.type]);if(!name)return;const response=await fetch("/module-templates",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,module,confirmed:true})});const body=await response.json() as {template?:DashboardModuleTemplate;message?:string};if(response.ok&&body.template){setModuleTemplates(current=>[...current,body.template!]);setMessage("模块模板已保存");}else setMessage(body.message||"模块模板未保存");};

  return <div className="personal-content dashboard-editor" data-theme={draft.theme.themeId} data-font-scale={draft.theme.fontScale} data-motion={draft.theme.motion}>
    <section className="dashboard-commandbar">
      <div className="dashboard-workspace-title"><LayoutDashboard/><div><span>当前工作台 · v{draft.version}</span><Input aria-label="工作台名称" value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/><small>{draft.modules.length} 个模块 · {visible.length} 个显示 · {draft.theme.mode==="dark"?"深色":"浅色"}</small></div></div>
      <div className="dashboard-command-actions"><div className="dashboard-mode-switch"><button className={mode==="view"?"active":undefined} onClick={()=>setMode("view")}><Eye/>查看</button><button className={mode==="edit"?"active":undefined} onClick={()=>setMode("edit")}><Settings2/>编辑</button></div><Button variant="outline" onClick={()=>void perform("undo")}><Undo2/>撤销</Button><Button variant="outline" onClick={()=>void perform("redo")}><Redo2/>重做</Button><Button onClick={()=>void save()} disabled={!dirty||busy}><Save/>保存布局</Button></div>
    </section>
    <section className="dashboard-statusbar"><span className={dirty?"unsaved":"saved"}>{dirty?"有尚未保存的修改":"配置已保存"}</span><span>刷新策略已保存；定时执行需部署调度器</span><span>外部数据会显示来源与时间</span>{message&&<strong>{message}</strong>}</section>
    <div className="dashboard-shell">
      {mode==="edit"&&<aside className="dashboard-toolbox"><nav>{([['modules','模块',LayoutDashboard],['appearance','外观',Palette],['agent','自然语言',Sparkles],['json','JSON',Braces],['versions','版本',History],['sources','数据源',Database],['privacy','隐私',ShieldCheck]] as const).map(([id,label,Icon])=><button key={id} className={panel===id?"active":undefined} onClick={()=>setPanel(id)}><Icon/><span>{label}</span></button>)}</nav>
        <div className="dashboard-tool-content">
          {panel==="modules"&&<><header><div><strong>模块目录</strong><small>点击添加，可重复使用</small></div><Badge variant="outline">{catalog.length}/{DASHBOARD_MODULE_REGISTRY.length}</Badge></header><div className="dashboard-template-strip"><span>从模板新建</span>{[["long_term","长期"],["etf","ETF"],["risk_control","风险"],["trade_review","复盘"],["beginner_safe_start","新手"]].map(([id,label])=><button key={id} onClick={()=>createFromTemplate(id)}>{label}</button>)}</div>{moduleTemplates.length>0&&<div className="dashboard-template-strip"><span>我的模块</span>{moduleTemplates.map(item=><button key={item.templateId} onClick={()=>addFromModuleTemplate(item)}>{item.name}</button>)}</div>}<Input placeholder="搜索模块、用途或类别" value={moduleSearch} onChange={event=>setModuleSearch(event.target.value)}/><div className="dashboard-catalog">{catalog.map(item=><button key={item.moduleId} onClick={()=>addModule(item.moduleId)}><span><strong>{item.name}</strong><small>{categoryLabel[item.category]} · 默认 {item.uiSchema.defaultWidth}/12 栏</small></span><Plus/></button>)}</div>{!catalog.length&&<p className="dashboard-empty-copy">没有匹配模块。试试“风险”“ETF”或“复盘”。</p>}{hidden.length>0&&<section className="dashboard-hidden"><strong>已隐藏</strong>{hidden.map(item=><button key={item.instanceId} onClick={()=>updateModule(item.instanceId,{visible:true})}>{item.title||MODULE_LABELS[item.type]}<Eye/></button>)}</section>}</>}
          {panel==="module"&&selected&&<ModuleInspector module={selected} dataSources={dataSources} onChange={updateSelected} onRemove={removeSelected} onDuplicate={duplicateSelected} onSaveTemplate={()=>void saveModuleTemplate(selected)}/>} 
          {panel==="appearance"&&<AppearancePanel workspace={draft} onChange={setDraft}/>} 
          {panel==="agent"&&<><header><div><strong>用一句话调整</strong><small>可用模型规划；失败时回退到本地注册表</small></div><Badge variant="outline">不会改数据</Badge></header><Textarea rows={5} value={instruction} onChange={event=>setInstruction(event.target.value)} placeholder="例如：只保留风险、估值和持仓相关内容"/><div className="dashboard-agent-examples">{["把持仓风险放到左上角","隐藏技术图表","改成浅色主题","只保留风险、估值和持仓相关内容"].map(item=><button key={item} onClick={()=>setInstruction(item)}>{item}</button>)}</div><Button disabled={busy} onClick={()=>void makePreview()}><Sparkles/>{busy?"正在规划":"生成修改预览"}</Button>{preview&&<section className="dashboard-patch-preview"><header><strong>{preview.summary}</strong><Badge variant="outline">基于 v{preview.baseVersion}</Badge></header>{preview.changes.length?preview.changes.map((item,index)=><p key={index}><Check/>{changeLabel(item)}</p>):<p><X/>没有识别到可安全应用的修改</p>}<footer><Button variant="outline" onClick={()=>setPreview(undefined)}>继续调整</Button><Button disabled={!preview.changes.length||busy} onClick={()=>void applyPreview()}>确认应用</Button></footer></section>}</>}
          {panel==="json"&&<><header><div><strong>代码配置</strong><small>只接受注册模块和授权数据源</small></div><Braces/></header><Textarea className="dashboard-json" rows={24} value={jsonText} spellCheck={false} onChange={event=>setJsonText(event.target.value)}/>{jsonErrors.map(item=><p className="dashboard-json-error" key={item}>{item}</p>)}<div className="dashboard-inline-actions"><Button variant="outline" onClick={validateJson}>验证并预览</Button><Button onClick={()=>void save()} disabled={!dirty||jsonErrors.length>0}>确认保存</Button></div></>}
          {panel==="versions"&&<><header><div><strong>版本历史</strong><small>每次确认都会留下快照和差异</small></div><History/></header><div className="dashboard-version-list">{versions.length?versions.slice().reverse().map(item=><article key={item.versionId}><div><strong>v{item.version}</strong><span>{item.changeSummary}</span><small>{item.diff.length?item.diff.slice(0,3).map(changeLabel).join("；"):"初始快照或恢复点"}{item.diff.length>3?` 等 ${item.diff.length} 项`:""}</small><small>{new Date(item.createdAt).toLocaleString("zh-CN")} · {item.changeSource}</small></div><div><Button variant="ghost" size="sm" onClick={()=>void request(`/workspaces/${draft.id}/versions/${item.versionId}/clone`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true})})}>建副本</Button><Button variant="outline" size="sm" onClick={()=>void request(`/workspaces/${draft.id}/restore`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({version_id:item.versionId,confirmed:true})})}>恢复</Button></div></article>):<p className="dashboard-empty-copy">保存一次后，这里会出现可恢复版本。</p>}</div>{workspaces.length>1&&<section className="dashboard-compare-note"><strong>工作台对比</strong><p>可通过 <code>/workspaces/compare?left=…&right=…</code> 获取结构化差异；不会比较或导出个人金融数据。</p></section>}</>}
          {panel==="sources"&&<DataSourcesPanel sources={dataSources} onChange={setDataSources} onMessage={setMessage}/>} 
          {panel==="privacy"&&<PrivacyPanel value={privacy} onChange={setPrivacy} onSave={()=>void savePrivacy()} onMessage={setMessage}/>} 
        </div>
      </aside>}
      <main className="dashboard-canvas-wrap">
        <header className="dashboard-canvas-header"><div><strong>{mode==="edit"?"布局画布":"工作台预览"}</strong><small>{mode==="edit"?"拖动卡片改变位置；打开模块可调整数据源和刷新频率":"当前显示已启用模块"}</small></div><div><Button variant="outline" size="sm" onClick={exportJson}><Download/>导出</Button><Button variant="outline" size="sm" onClick={()=>fileRef.current?.click()}><Upload/>导入</Button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={event=>importJson(event.target.files?.[0])}/><Button variant="outline" size="sm" onClick={()=>void share()}><Share2/>只读分享</Button><Button variant="outline" size="sm" onClick={()=>void request(`/workspaces/${draft.id}/set-default`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true})})}><Star/>设为默认</Button><Button variant="outline" size="sm" onClick={()=>{const fresh=createDashboardWorkspace("新工作台");void request("/workspaces",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspace:fresh,confirmed:true})});}}><Plus/>新建</Button><Button variant="outline" size="sm" onClick={()=>void request(`/workspaces/${draft.id}/duplicate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:`${draft.name} 副本`,confirmed:true})})}><Copy/>复制</Button><Button variant="outline" size="sm" disabled={workspaces.length<=1} onClick={()=>{if(window.confirm(`删除“${draft.name}”？该操作需要重新创建才能恢复。`))void request(`/workspaces/${draft.id}`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true})});}}><Trash2/>删除</Button></div></header>
        <div ref={gridRef} className={`dashboard-grid ${mode}`} style={{"--dashboard-row":`${draft.layout.rowHeight}px`,"--dashboard-gap":`${draft.layout.gap}px`} as React.CSSProperties} onDragOver={event=>event.preventDefault()} onDrop={dropModule}>
          {visible.map(module=><DashboardCard key={module.instanceId} module={module} dataSources={dataSources} edit={mode==="edit"} selected={module.instanceId===selectedId} onSelect={()=>{setSelectedId(module.instanceId);setPanel("module");}} onDragStart={()=>setDragging(module.instanceId)} onResizeStart={event=>startResize(event,module)} onChange={patch=>updateModule(module.instanceId,patch)}/>) }
          {!visible.length&&<div className="dashboard-empty-canvas"><LayoutDashboard/><strong>这个工作台还没有显示模块</strong><span>从左侧模块目录添加，或恢复一个隐藏模块。</span></div>}
        </div>
      </main>
    </div>
    <aside className="dashboard-footer-note"><ShieldCheck/>布局修改不会改变金融数据或投资结论；交易、资金和个人规则始终需要单独确认。当前账户共有 {workspaces.length} 个工作台。</aside>
  </div>;
}

function DashboardCard({module,dataSources,edit,selected,onSelect,onDragStart,onResizeStart,onChange}:{module:DashboardModule;dataSources:DashboardDataSource[];edit:boolean;selected:boolean;onSelect:()=>void;onDragStart:()=>void;onResizeStart:(event:React.PointerEvent)=>void;onChange:(patch:Partial<DashboardModule>)=>void}){
  const source=sourceStatus(module.dataSourceId,dataSources);const preview=modulePreview(module.type,Boolean(source?.available));return <article className={`dashboard-card ${selected?"selected":""} ${module.locked?"locked":""}`} draggable={edit&&!module.locked} onDragStart={onDragStart} onClick={onSelect} style={{gridColumn:`${module.position.x+1} / span ${module.position.w}`,gridRow:`${module.position.y+1} / span ${module.position.h}`}}>
    <header><div>{edit&&<GripVertical className="drag-handle"/>}<span><strong>{module.title||MODULE_LABELS[module.type]}</strong><small>{source?.name??"数据源待配置"} · {refreshLabel(module.refreshPolicy)}</small></span></div><div>{module.locked&&<LockKeyhole/>}<Badge variant={source?.available?"outline":"secondary"}>{source?.available?"可用":"待配置"}</Badge></div></header>
    <div className="dashboard-card-preview"><div className="dashboard-preview-main"><span>{preview.eyebrow}</span><strong>{preview.value}</strong><div>{preview.items.map(item=><i key={item}>{item}</i>)}</div></div><a href={preview.href} onClick={event=>event.stopPropagation()}>{preview.action}</a><p>{source?.statusLabel??"选择数据源后显示状态"}</p></div>
    {edit&&<><footer><button onClick={event=>{event.stopPropagation();onChange({visible:false})}}><EyeOff/>隐藏</button><button onClick={event=>{event.stopPropagation();onChange({locked:!module.locked})}}>{module.locked?<LockKeyhole/>:<Settings2/>}{module.locked?"已锁定":"设置"}</button><span>{module.position.w}/12 栏</span></footer>{!module.locked&&<button className="dashboard-resize-handle" aria-label={`拖动调整 ${module.title||MODULE_LABELS[module.type]} 大小`} onPointerDown={onResizeStart}/>}</>}
  </article>;
}

function ModuleInspector({module,dataSources,onChange,onRemove,onDuplicate,onSaveTemplate}:{module:DashboardModule;dataSources:DashboardDataSource[];onChange:(patch:Partial<DashboardModule>)=>void;onRemove:()=>void;onDuplicate:()=>void;onSaveTemplate:()=>void}){
  const compatible=DASHBOARD_MODULE_REGISTRY.find(item=>item.moduleId===module.type)?.dataSources??[];const selectable=dataSources.filter(item=>compatible.includes(item.sourceId)||item.sourceId==="workspace_state"||item.custom);
  return <><header><div><strong>模块设置</strong><small>{MODULE_LABELS[module.type]} · {module.instanceId}</small></div><Settings2/></header><div className="dashboard-inspector"><label><span>显示名称</span><Input value={module.title??""} placeholder={MODULE_LABELS[module.type]} onChange={event=>onChange({title:event.target.value})}/></label><label><span>数据源</span><select value={module.dataSourceId} onChange={event=>onChange({dataSourceId:event.target.value})}>{selectable.map(item=><option key={item.sourceId} value={item.sourceId}>{item.name}{item.available?"":"（待配置）"}</option>)}</select></label><label><span>刷新方式</span><select value={module.refreshPolicy.mode} onChange={event=>onChange({refreshPolicy:{...module.refreshPolicy,mode:event.target.value as RefreshPolicy["mode"]}})}><option value="manual">手动</option><option value="interval">固定间隔</option><option value="schedule">定时计划</option><option value="event">事件触发</option></select></label>{module.refreshPolicy.mode==="interval"&&<label><span>刷新间隔</span><select value={module.refreshPolicy.interval??"1h"} onChange={event=>onChange({refreshPolicy:{...module.refreshPolicy,interval:event.target.value as RefreshPolicy["interval"]}})}><option value="5m">5 分钟</option><option value="15m">15 分钟</option><option value="1h">1 小时</option><option value="4h">4 小时</option><option value="daily">每天</option><option value="weekly">每周</option></select></label>}<div className="dashboard-size-grid"><label><span>宽度（12 栏）</span><Input type="number" min="3" max="12" value={module.position.w} onChange={event=>onChange({position:{...module.position,w:Math.max(3,Math.min(12,Number(event.target.value)))}})}/></label><label><span>高度</span><Input type="number" min="2" max="12" value={module.position.h} onChange={event=>onChange({position:{...module.position,h:Math.max(2,Math.min(12,Number(event.target.value)))}})}/></label></div><ParameterEditor key={module.instanceId} value={module.parameters} onApply={parameters=>onChange({parameters})}/><label className="dashboard-check"><input type="checkbox" checked={module.locked} onChange={event=>onChange({locked:event.target.checked})}/><span>锁定位置和尺寸</span></label><div className="dashboard-source-note"><Database/><span><strong>{sourceStatus(module.dataSourceId,dataSources)?.statusLabel}</strong><small>{module.refreshPolicy.mode==="manual"?"由用户主动刷新。":"策略会保存；自动执行需要已部署的调度器。"}</small></span></div></div><footer className="dashboard-inspector-actions"><Button variant="outline" onClick={onSaveTemplate}><Star/>存为模板</Button><Button variant="outline" onClick={onDuplicate}><Copy/>复制模块</Button><Button variant="outline" onClick={onRemove}><Trash2/>删除</Button></footer></>;
}

function ParameterEditor({value,onApply}:{value:Record<string,string|number|boolean>;onApply:(value:Record<string,string|number|boolean>)=>void}){const [text,setText]=useState(JSON.stringify(value,null,2));const [error,setError]=useState("");return <label><span>模块参数（JSON）</span><Textarea rows={6} value={text} spellCheck={false} onChange={event=>setText(event.target.value)}/>{error&&<small className="dashboard-json-error">{error}</small>}<Button variant="outline" size="sm" onClick={()=>{try{const parsed=JSON.parse(text);if(!parsed||Array.isArray(parsed)||typeof parsed!=="object")throw new Error("参数必须是 JSON 对象");onApply(parsed);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"参数 JSON 无效");}}}>应用参数</Button></label>}

function AppearancePanel({workspace,onChange}:{workspace:DashboardWorkspace;onChange:(workspace:DashboardWorkspace)=>void}){const setTheme=(patch:Partial<DashboardWorkspace["theme"]>)=>onChange({...workspace,theme:{...workspace.theme,...patch}});return <><header><div><strong>布局与外观</strong><small>直接预览，保存后形成新版本</small></div><Palette/></header><div className="dashboard-inspector"><label><span>主题模式</span><select value={workspace.theme.mode} onChange={event=>setTheme({mode:event.target.value as "light"|"dark",themeId:event.target.value==="dark"?"dark_focus":"light_quiet"})}><option value="light">浅色</option><option value="dark">深色</option></select></label><label><span>强调色</span><select value={workspace.theme.accent} onChange={event=>setTheme({accent:event.target.value as DashboardWorkspace["theme"]["accent"]})}><option value="indigo">靛蓝</option><option value="blue">清透蓝</option><option value="slate">中性灰</option></select></label><label><span>字号</span><select value={workspace.theme.fontScale} onChange={event=>setTheme({fontScale:event.target.value as DashboardWorkspace["theme"]["fontScale"]})}><option value="small">紧凑</option><option value="medium">标准</option><option value="large">大字</option></select></label><label><span>动效</span><select value={workspace.theme.motion} onChange={event=>setTheme({motion:event.target.value as DashboardWorkspace["theme"]["motion"]})}><option value="standard">轻量</option><option value="reduced">减少动效</option></select></label><div className="dashboard-size-grid"><label><span>行高</span><Input type="number" min="56" max="120" value={workspace.layout.rowHeight} onChange={event=>onChange({...workspace,layout:{...workspace.layout,rowHeight:Math.max(56,Math.min(120,Number(event.target.value)))}})}/></label><label><span>间距</span><Input type="number" min="6" max="24" value={workspace.layout.gap} onChange={event=>onChange({...workspace,layout:{...workspace.layout,gap:Math.max(6,Math.min(24,Number(event.target.value)))}})}/></label></div><div className="dashboard-theme-preview"><i/><i/><i/><span>风险状态始终同时使用文字、图标与颜色；主题不会隐藏提示。</span></div></div></>}

function DataSourcesPanel({sources,onChange,onMessage}:{sources:DashboardDataSource[];onChange:(items:DashboardDataSource[])=>void;onMessage:(message:string)=>void}){const [name,setName]=useState("");const [endpoint,setEndpoint]=useState("");const add=async()=>{const response=await fetch("/data-sources",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,type:"api",endpoint,retentionPolicy:"none",confirmed:true})});const body=await response.json() as {data_source?:DashboardDataSource;message?:string};if(response.ok&&body.data_source){onChange([...sources,body.data_source]);setName("");setEndpoint("");onMessage("数据源配置已保存，联网前仍需批准适配器");}else onMessage(body.message||"数据源未保存");};return <><header><div><strong>数据源</strong><small>只登记安全元数据，不在页面保存密钥</small></div><Database/></header><div className="dashboard-source-list">{sources.map(source=><article key={source.sourceId}><div><strong>{source.name}</strong><small>{source.type} · {source.statusLabel}</small>{source.endpointHost&&<small>主机：{source.endpointHost}</small>}</div><Badge variant={source.available?"outline":"secondary"}>{source.available?"可用":"待适配"}</Badge>{source.custom&&<Button variant="ghost" size="sm" onClick={async()=>{if(!window.confirm(`删除数据源“${source.name}”？`))return;const response=await fetch(`/data-sources/${source.sourceId}`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true})});if(response.ok)onChange(sources.filter(item=>item.sourceId!==source.sourceId));else onMessage(((await response.json()) as {message?:string}).message||"无法删除");}}><Trash2/></Button>}</article>)}</div><div className="dashboard-source-form"><strong>登记外部 API</strong><Input value={name} onChange={event=>setName(event.target.value)} placeholder="显示名称"/><Input value={endpoint} onChange={event=>setEndpoint(event.target.value)} placeholder="https://api.example.com"/><small>不会直接连接任意 URL。保存后需要后端白名单适配器，API Key 只能配置在服务器端。</small><Button disabled={!name.trim()||!endpoint.trim()} onClick={()=>void add()}><Plus/>保存配置</Button></div></>}

function PrivacyPanel({value,onChange,onSave,onMessage}:{value:{savePortfolio:boolean;saveTrades:boolean;saveAIConversation:boolean;saveBacktests:boolean;saveSocialContent:boolean;allowExternalModels:boolean;localModelsOnly:boolean;retentionDays:number};onChange:(next:typeof value)=>void;onSave:()=>void;onMessage:(message:string)=>void}){
  const rows:[[keyof typeof value,string,string]]=[
    ["savePortfolio","保存持仓","默认不连接证券账户，仅保存用户主动输入的数据"],
  ];
  const checks:Array<[keyof typeof value,string,string]>=[...rows,["saveTrades","保存交易记录","CSV 默认仅用于本次分析"],["saveAIConversation","保存 AI 对话","关闭后不用于任务历史"],["saveBacktests","保存回测结果","只保存参数、结果与数据时间"],["saveSocialContent","保存社交内容原文","默认仅保存特征，不保存原文"],["allowExternalModels","允许发送到外部模型","发送前仍会显示当前模型"],["localModelsOnly","仅使用本机模型","云端页面需要服务器可访问的推理地址"]];
  const exportAll=async()=>{const response=await fetch("/api/privacy/data",{cache:"no-store"});if(!response.ok){onMessage("个人数据暂时无法导出");return;}const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`anxin-personal-data-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);onMessage("个人数据已导出");};const erase=async(category:"holdings"|"decisions"|"ai"|"quant"|"profile")=>{if(!window.confirm("确认删除这一类个人数据？该操作不会删除工作台布局。"))return;const response=await fetch("/api/privacy/data",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({category,confirmed:true})});onMessage(response.ok?"所选个人数据已删除":((await response.json()) as {message?:string}).message||"删除失败");};const eraseAll=async()=>{if(!window.confirm("确认永久删除账号下全部安心看股数据？此操作不可撤销。"))return;const response=await fetch("/api/me/snapshot",{method:"DELETE"});onMessage(response.ok?"全部个人数据已删除，请刷新页面":"全部数据删除失败");};
  return <><header><div><strong>数据与隐私</strong><small>默认少收集、短保留</small></div><ShieldCheck/></header><div className="dashboard-privacy-list">{checks.map(([key,label,detail])=><label key={key}><input type="checkbox" checked={Boolean(value[key])} onChange={event=>onChange({...value,[key]:event.target.checked})}/><span><strong>{label}</strong><small>{detail}</small></span></label>)}<label className="retention"><span><strong>数据保留时间</strong><small>到期清理需要服务器定时任务；设置会立即保存为策略</small></span><select value={value.retentionDays} onChange={event=>onChange({...value,retentionDays:Number(event.target.value)})}><option value="0">不保存</option><option value="7">7 天</option><option value="30">30 天</option><option value="90">90 天</option><option value="365">1 年</option></select></label></div><div className="dashboard-inline-actions"><Button onClick={onSave}><Save/>保存设置</Button><Button variant="outline" onClick={()=>void exportAll()}><Download/>导出全部数据</Button></div><section className="dashboard-danger-zone"><strong>删除个人数据</strong><div>{([['holdings','持仓与关注'],['decisions','决策记录'],['ai','Agent 任务'],['quant','量化研究'],['profile','规则与偏好']] as const).map(([id,label])=><button key={id} onClick={()=>void erase(id)}>{label}</button>)}</div><Button variant="outline" onClick={()=>void eraseAll()}><Trash2/>删除全部数据</Button></section></>;
}
