"use client";

import { useState } from "react";
import { ArrowRight, CheckCircle2, Clock3, FileSearch, ShieldCheck } from "lucide-react";

const steps=["设定计划","选择理由","查看核实","作出决定"];
const reasons=[
  {id:"rumor",label:"朋友说有大订单，很快会反弹",fact:"价格近期下跌",external:"大订单尚未找到正式披露",inference:"“很快反弹”不能由传闻推出"},
  {id:"fomo",label:"最近讨论很多，我怕错过机会",fact:"近期讨论热度上升",external:"讨论热度不等于资金或盈利改善",inference:"“怕错过”属于时间压力"},
  {id:"fundamental",label:"我看好长期需求，但想核对现金流",fact:"长期需求是待验证假设",external:"需要财报与经营现金流数据",inference:"当前理由仍缺少明确失效条件"},
] as const;

const money=(value:number)=>`¥${value.toLocaleString("zh-CN")}`;

export function DemoWalkthrough(){
  const[step,setStep]=useState(0);const[amount,setAmount]=useState(50000);const[reasonId,setReasonId]=useState<(typeof reasons)[number]["id"]>("rumor");const[choice,setChoice]=useState<"reduce"|"delay"|null>(null);
  const capital=200000,current=20000,limit=.25;const reason=reasons.find(item=>item.id===reasonId)!;const afterValue=current+amount;const afterWeight=afterValue/capital;const scenarioLoss=afterValue*.2;const overLimit=Math.max(0,afterWeight-limit);const reducedAmount=Math.max(0,capital*limit-current);const finalAmount=choice==="reduce"?Math.min(amount,reducedAmount):0;const finalWeight=choice==="reduce"?(current+finalAmount)/capital:current/capital;
  const next=(target:number)=>{setStep(target);if(target<3)setChoice(null)};
  return <section className="demo-walkthrough demo-sandbox"><header><div><span>可操作教学场景</span><strong>生益科技补仓前检查</strong><p>修改金额和理由，所有仓位、损失和冲突会随你的选择重新计算。</p></div><div><Clock3/><span><strong>约 90 秒</strong><small>规则计算 · 不调用外部模型</small></span></div></header>
    <nav aria-label="演示步骤">{steps.map((name,index)=><button key={name} className={step===index?"active":index<step?"done":""} onClick={()=>next(index)}><i>{index<step?<CheckCircle2/>:index+1}</i><span>{name}</span></button>)}</nav>
    <main>{step===0&&<section><div className="demo-kicker">先改变一个真实变量</div><h2>你准备补仓多少钱？</h2><div className="demo-input-panel"><label><span>计划金额</span><input type="number" min="0" max="180000" step="1000" value={amount} onChange={event=>setAmount(Math.max(0,Math.min(180000,Number(event.target.value)||0)))}/></label><div>{[10000,30000,50000].map(value=><button className={amount===value?"selected":""} onClick={()=>setAmount(value)} key={value}>{money(value)}</button>)}</div></div><div className="demo-metrics"><article><span>当前持仓</span><strong>{money(current)}</strong></article><article><span>计划后持仓</span><strong>{money(afterValue)}</strong></article><article><span>计划后占比</span><strong className={afterWeight>limit?"warning":""}>{(afterWeight*100).toFixed(0)}%</strong></article><article><span>下跌 20% 情景</span><strong>−{money(scenarioLoss)}</strong></article></div><button onClick={()=>next(1)}>继续：说明为什么现在操作<ArrowRight/></button></section>}
      {step===1&&<section><div className="demo-kicker">选择最接近你的真实想法</div><h2>为什么现在想补仓？</h2><div className="demo-reason-options">{reasons.map(item=><button key={item.id} className={reasonId===item.id?"selected":""} onClick={()=>setReasonId(item.id)}><i>{reasonId===item.id?<CheckCircle2/>:null}</i><span>{item.label}</span></button>)}</div><div className="demo-selected-reason"><span>系统将核实</span><strong>{reason.label}</strong></div><button onClick={()=>next(2)}>拆分说法并计算影响<ArrowRight/></button></section>}
      {step===2&&<section><div className="demo-kicker">证据和规则分别处理</div><h2>{overLimit>0?`计划超过个人上限 ${(overLimit*100).toFixed(0)} 个百分点`:"计划未超过个人仓位上限，但理由仍需核实"}</h2><div className="demo-claim-grid"><article><span>当前可核实</span><strong>{reason.fact}</strong><small>事实需要对应数据时间与来源</small></article><article><span>仍缺证据</span><strong>{reason.external}</strong><small>没有来源就不当成已证实事实</small></article><article><span>推断风险</span><strong>{reason.inference}</strong><small>系统不据此预测未来涨跌</small></article></div><div className="demo-findings"><article><FileSearch/><span><strong>证据状态</strong><small>教学快照没有找到支持该说法的完整证据链。</small></span></article><article><ShieldCheck/><span><strong>个人规则</strong><small>你的单股上限是 25%；本计划后为 {(afterWeight*100).toFixed(0)}%。</small></span></article><article><Clock3/><span><strong>金额影响</strong><small>若计划后下跌 20%，持仓金额影响约为 −{money(scenarioLoss)}。</small></span></article></div><button onClick={()=>next(3)}>我来决定下一步<ArrowRight/></button></section>}
      {step===3&&<section><div className="demo-kicker">系统不替你执行</div><h2>看完核实结果，你如何处理原计划？</h2><div className="demo-before-after"><div><span>原计划</span><strong>{money(amount)} · 计划后 {(afterWeight*100).toFixed(0)}%</strong><small>{afterWeight>limit?"超过个人上限":"未超过个人上限"}</small></div><ArrowRight/><div><span>你的选择</span><strong>{choice==="reduce"?`${money(finalAmount)} · 计划后 ${(finalWeight*100).toFixed(0)}%`:choice==="delay"?"稍后再看":"等待选择"}</strong><small>{choice?"只记录决定，不连接券商":"选择后查看变化"}</small></div></div><div className="demo-choice"><button className={choice==="reduce"?"selected":""} onClick={()=>setChoice("reduce")}><strong>调整到个人上限以内</strong><small>计划金额变为 {money(Math.min(amount,reducedAmount))}</small></button><button className={choice==="delay"?"selected":""} onClick={()=>setChoice("delay")}><strong>稍后再看</strong><small>保留当前 10% 持仓，不执行交易</small></button></div>{choice&&<div className="demo-outcome"><CheckCircle2/><div><strong>{choice==="reduce"?`计划金额减少 ${money(amount-finalAmount)}`:"本次计划已延迟"}</strong><span>计划后占比 {(afterWeight*100).toFixed(0)}% → 最终 {(finalWeight*100).toFixed(0)}%</span><small>你刚完成了“信息 → 核实 → 个人影响 → 自主决定”的完整闭环。</small></div></div>}</section>}
    </main><footer><span>这不是自动荐股演示；可交互部分是金额、理由、证据缺口和个人选择。</span><button onClick={()=>{setStep(0);setChoice(null);setAmount(50000);setReasonId("rumor")}}>重新开始</button></footer>
  </section>;
}
