"use client";

import {useEffect,useState} from "react";
import {Activity,ArrowRight,BarChart3,Bell,Check,Clock3,Copy,Database,Download,Layers3,Pause,Play,RefreshCw,ShieldCheck,Sparkles,Trash2,TriangleAlert,X} from "lucide-react";
import type {BacktestResult,PricePoint} from "@/app/lib/quant-research";
import type {StrategyPreview} from "@/app/lib/natural-language-strategy";

type SavedStrategy={id:string;name:string;original_text:string;status:"active"|"paused";version:number;dsl:StrategyPreview["dsl"];schedule:{frequency:string;run_at:string|null;runner_status:string;enabled:boolean};last_run_at:string|null;failure_count:number;reliability:{status:string;message:string};created_at:string};
type Notification={notification_id:string;strategy_id:string;strategy_name:string;triggered_at:string;message:string;data_timestamp:string|null;conditions:string[];risk_tags:string[];disclaimer:string};
type BacktestEnvelope={backtest_id:string;strategy_id:string;trigger_count:number;average_return_pct:number|null;result:BacktestResult;risk_warnings:string[]};
type WorkspacePreview={command_id:string;workspace_patch:{summary:string;changes:string[];affectedModules:string[]}};
const examples=["当 510300 沪深300 ETF 的 5 日均线上穿 20 日均线，且成交量较前一日放大 50% 时，每日收盘后提醒我。","当 510300 的 RSI 低于 30，或者近 60 日回撤超过 12% 时加入观察。","每周检查 512480 的波动率是否低于 25%，条件满足时进行纸面模拟。","当公告出现减持、立案调查或业绩预告恶化时提醒我。"];
const frequencyLabel:Record<string,string>={manual:"手动",daily_close:"每日收盘后",weekly:"每周",monthly:"每月",event:"事件触发",realtime:"盘中"};
const actionLabel:Record<string,string>={notify:"提醒",watch:"加入观察",paper_simulation:"纸面模拟"};

function normalizeHistory(payload:unknown):PricePoint[]{if(!payload||typeof payload!=="object")return [];const rows=(payload as {history?:{data?:Array<{date?:string;close?:number;volume?:number}>}}).history?.data??[];return rows.map(item=>({date:String(item.date??""),close:Number(item.close),volume:Number(item.volume)||undefined})).filter(item=>/^\d{4}-\d{2}-\d{2}$/.test(item.date)&&Number.isFinite(item.close)&&item.close>0);}
export function NaturalStrategyAssistant(){
  const [text,setText]=useState(examples[0]);const [preview,setPreview]=useState<StrategyPreview|null>(null);const [strategies,setStrategies]=useState<SavedStrategy[]>([]);const [notifications,setNotifications]=useState<Notification[]>([]);const [selected,setSelected]=useState<SavedStrategy|null>(null);const [backtest,setBacktest]=useState<BacktestEnvelope|null>(null);const [workspace,setWorkspace]=useState<WorkspacePreview|null>(null);const [busy,setBusy]=useState("");const [message,setMessage]=useState("");
  const load=()=>fetch("/quant/strategy",{cache:"no-store"}).then(response=>response.ok?response.json():null).then((body:{strategies?:SavedStrategy[];notifications?:Notification[]}|null)=>{setStrategies(body?.strategies??[]);setNotifications(body?.notifications??[]);setSelected(current=>current?(body?.strategies??[]).find(item=>item.id===current.id)??null:(body?.strategies??[])[0]??null)}).catch(()=>undefined);
  useEffect(()=>{void load()},[]);
  const request=async(url:string,init:RequestInit,action:string)=>{setBusy(action);setMessage("");try{const response=await fetch(url,init);const body=await response.json() as Record<string,unknown>;if(!response.ok)throw new Error(String(body.message??"操作未完成"));return body;}catch(error){setMessage(error instanceof Error?error.message:"操作未完成");return null;}finally{setBusy("");}};
  const createPreview=async()=>{setBacktest(null);setWorkspace(null);const body=await request("/quant/strategy/preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text})},"preview");if(body?.preview)setPreview(body.preview as StrategyPreview);};
  const confirm=async()=>{if(!preview)return;const body=await request("/quant/strategy/confirm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({preview_id:preview.preview_id,confirmed:true})},"confirm");if(body?.strategy){setSelected(body.strategy as SavedStrategy);setPreview(null);setMessage("策略已保存。现在可以读取真实日线并运行回测或条件核验。");await load();}};
  const loadMarket=async(strategy:SavedStrategy)=>{const code=strategy.dsl.asset_universe[0];if(!code)throw new Error("策略缺少 6 位标的代码");const response=await fetch(`/api/information/${code}`,{cache:"no-store"});const body=await response.json() as Record<string,unknown>;const points=normalizeHistory(body);if(!response.ok||!points.length)throw new Error(String(body.message??"没有取得可用历史行情"));return {points,source:String(body.provider??"公开行情"),data_timestamp:String(body.data_timestamp??points.at(-1)?.date??""),cached:body.status==="cached",reliability:body.reliability};};
  const runBacktest=async(strategy:SavedStrategy)=>{setBusy("backtest");setMessage("");try{const market=await loadMarket(strategy);const response=await fetch(`/quant/strategy/${strategy.id}/backtest`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prices:market.points,dataReliability:market.reliability})});const body=await response.json() as BacktestEnvelope&{message?:string};if(!response.ok)throw new Error(body.message??"回测未完成");setBacktest(body);setSelected(strategy);setMessage(body.result.reliability.allow_signal?"回测完成，可信度门禁允许生成研究信号。":"回测完成，但数据新鲜度或可信度不允许生成新信号。");await load();}catch(error){setMessage(error instanceof Error?error.message:"回测未完成");}finally{setBusy("");}};
  const runNow=async(strategy:SavedStrategy)=>{setBusy("run");setMessage("");try{const market=await loadMarket(strategy);const response=await fetch(`/quant/strategy/${strategy.id}/run`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(market)});const body=await response.json() as {run?:{triggered:boolean;warnings:string[]};notification?:Notification|null;message?:string};if(!response.ok)throw new Error(body.message??"运行失败");setSelected(strategy);setMessage(body.notification?"条件已满足，已生成一条待人工确认提醒。":body.run?.warnings?.[0]??"本次条件未满足，没有生成提醒。");await load();}catch(error){setMessage(error instanceof Error?error.message:"运行失败");}finally{setBusy("");}};
  const status=async(strategy:SavedStrategy,action:"pause"|"resume")=>{const body=await request(`/quant/strategy/${strategy.id}/${action}`,{method:"POST"},action);if(body)await load();};
  const copy=async(strategy:SavedStrategy)=>{const body=await request(`/quant/strategy/${strategy.id}/copy`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true})},"copy");if(body)await load();};
  const remove=async(strategy:SavedStrategy)=>{if(!window.confirm(`确认删除“${strategy.name}”？运行历史将继续保留在审计记录中。`))return;const body=await request(`/quant/strategy/${strategy.id}`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true})},"delete");if(body){setSelected(null);setBacktest(null);await load();}};
  const exportStrategy=(strategy:SavedStrategy)=>{const blob=new Blob([JSON.stringify(strategy,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${strategy.id}.json`;link.click();URL.revokeObjectURL(url);};
  const previewWorkspace=async(strategy:SavedStrategy)=>{const body=await request("/workspace/preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({instruction:`把“${strategy.name}”策略概览、回测结果、触发历史、风险检查和模拟组合加入当前工作台`})},"workspace");if(body)setWorkspace(body as unknown as WorkspacePreview);};
  const applyWorkspace=async()=>{if(!workspace)return;const body=await request("/workspace/apply",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({command_id:workspace.command_id,confirmed:true})},"apply-workspace");if(body){setWorkspace(null);setMessage("策略模块已经加入当前工作台，可从工作台撤销。")}};
  return <section className="nl-strategy-shell">
    <header className="nl-strategy-header"><div><span><Sparkles/>自然语言策略助手</span><h2>先说想法，再检查规则</h2><p>把中文描述转换为可核对的 A 股规则。缺少阈值、频率或确认时点时会先提问，不会替你猜。</p></div><aside><ShieldCheck/><span><b>安全 DSL</b><small>白名单指标 · 人工确认 · 不执行代码</small></span></aside></header>
    <div className="nl-strategy-composer"><textarea value={text} onChange={event=>setText(event.target.value)} aria-label="自然语言策略" maxLength={3000}/><button onClick={()=>void createPreview()} disabled={!text.trim()||busy==="preview"}>{busy==="preview"?"正在解析…":"生成策略预览"}<ArrowRight/></button></div>
    <div className="nl-strategy-examples">{examples.map(item=><button key={item} onClick={()=>setText(item)}>{item}</button>)}</div>{message&&<div className="nl-strategy-message"><TriangleAlert/><span>{message}</span><button onClick={()=>setMessage("")} aria-label="关闭"><X/></button></div>}
    {preview&&<section className="strategy-preview-card"><header><div><span>确认前预览</span><h3>{preview.name}</h3></div><em data-status={preview.validation.status}>{preview.validation.status==="pass"?"可以保存":preview.validation.status==="warning"?"需要补充":"已阻断"}</em></header><div className="strategy-preview-summary"><article><span>标的</span><b>{preview.asset||"待确认"}</b></article><article><span>频率</span><b>{frequencyLabel[preview.frequency]??preview.frequency}</b></article><article><span>条件关系</span><b>{preview.logic}</b></article><article><span>触发动作</span><b>{actionLabel[preview.action]}</b></article></div><p className="strategy-plain-explanation">{preview.explanation}</p><div className="strategy-condition-list">{preview.conditions.map((item,index)=><article key={item.id}><i>{index+1}</i><span><b>{item.explanation}</b><small>{item.name} · {item.operator} · {item.required_data.join(" / ")}</small></span></article>)}</div>{preview.questions.length>0&&<aside className="strategy-questions"><strong>保存前还需确认</strong>{preview.questions.map(item=><p key={item}>{item}</p>)}</aside>}<div className="strategy-source-row">{preview.data_sources.map(item=><span key={item.id}><Database/>{item.name}<small>{item.status==="available"?"可用":item.status==="user_input"?"由用户提供":"需要授权"}</small></span>)}</div><footer><button className="secondary" onClick={()=>setPreview(null)}>取消</button><button className="secondary" onClick={()=>{setText(preview.original_text);setPreview(null)}}>修改描述</button><button onClick={()=>void confirm()} disabled={!preview.validation.allow_save||busy==="confirm"}><Check/>应用并保存</button></footer></section>}
    <div className="strategy-manager-grid"><section className="strategy-library"><header><div><span>我的策略</span><h3>{strategies.length} 个已保存版本</h3></div><Clock3/></header>{strategies.length?<div>{strategies.map(item=><article className={selected?.id===item.id?"selected":undefined} key={item.id} onClick={()=>setSelected(item)}><div><b>{item.name}</b><small>v{item.version} · {frequencyLabel[item.schedule.frequency]??item.schedule.frequency} · {item.status==="active"?"启用":"暂停"}</small></div><em data-status={item.reliability.status}>{item.failure_count?`失败 ${item.failure_count}`:item.schedule.runner_status==="unavailable"&&item.schedule.enabled?"需手动运行":"就绪"}</em><p>{item.original_text}</p><footer><button onClick={event=>{event.stopPropagation();void runBacktest(item)}} disabled={busy==="backtest"}><BarChart3/>回测</button><button onClick={event=>{event.stopPropagation();void runNow(item)}} disabled={busy==="run"}><Play/>运行</button><button onClick={event=>{event.stopPropagation();void status(item,item.status==="active"?"pause":"resume")}}>{item.status==="active"?<Pause/>:<RefreshCw/>}{item.status==="active"?"暂停":"恢复"}</button><button onClick={event=>{event.stopPropagation();void copy(item)}}><Copy/></button><button onClick={event=>{event.stopPropagation();exportStrategy(item)}}><Download/></button><button onClick={event=>{event.stopPropagation();void remove(item)}}><Trash2/></button></footer></article>)}</div>:<Empty title="还没有保存策略" detail="先生成预览，补齐不明确的条件，再确认保存。"/>}</section>
      <section className="strategy-inspector"><header><div><span>策略详情</span><h3>{selected?.name??"选择一个策略"}</h3></div>{selected&&<button onClick={()=>void previewWorkspace(selected)}><Layers3/>加入工作台</button>}</header>{selected?<><div className="strategy-flow">{selected.dsl.conditions.map((item,index)=><span key={item.id}><b>{item.explanation}</b>{index<selected.dsl.conditions.length-1&&<i>{selected.dsl.logic}</i>}</span>)}<ArrowRight/><span className="action"><Bell/><b>{actionLabel[selected.dsl.action]}</b><small>始终人工确认</small></span></div><div className="strategy-schedule-state"><Clock3/><span><b>{frequencyLabel[selected.schedule.frequency]??selected.schedule.frequency}{selected.schedule.run_at?` · ${selected.schedule.run_at}`:""}</b><small>{selected.schedule.enabled&&selected.schedule.runner_status==="unavailable"?"托管定时运行器尚未接入；当前可手动运行，不会假装自动监控。":selected.status==="paused"?"策略已暂停":"手动策略"}</small></span></div>{backtest&&selected.id===backtest.strategy_id&&<BacktestSummary value={backtest}/>}</>:<Empty title="从左侧选择策略" detail="这里会显示条件流程、频率、运行状态与最近回测。"/>}{workspace&&<aside className="strategy-workspace-preview"><b>{workspace.workspace_patch.summary}</b><p>{workspace.workspace_patch.changes.join("；")}</p><div><button onClick={()=>setWorkspace(null)}>继续调整</button><button onClick={()=>void applyWorkspace()}>确认应用</button></div></aside>}</section></div>
    <section className="strategy-notification-center"><header><div><span>触发记录</span><h3>为什么满足，一眼看清</h3></div><Bell/></header>{notifications.length?<div>{notifications.slice(0,8).map(item=><article key={item.notification_id}><time>{new Date(item.triggered_at).toLocaleString("zh-CN")}</time><span><b>{item.strategy_name}</b><p>{item.message}</p><small>{item.conditions.join("；")} · 数据截至 {item.data_timestamp??"暂无"}</small></span><em>待人工确认</em></article>)}</div>:<Empty title="还没有触发记录" detail="只有全部可计算条件满足时才生成提醒；数据缺失不会被解释为触发。"/>}</section>
  </section>;
}
function BacktestSummary({value}:{value:BacktestEnvelope}){const metrics=value.result.metrics;return <div className="nl-backtest-summary"><header><span><Activity/>最近回测</span><em>{value.result.credibility.score}/100 可信度</em></header>{metrics?<div><article><span>触发次数</span><b>{value.trigger_count}</b></article><article><span>累计收益</span><b>{metrics.totalReturnPct}%</b></article><article><span>最大回撤</span><b>{metrics.maxDrawdownPct}%</b></article><article><span>波动率</span><b>{metrics.volatilityPct}%</b></article><article><span>Sharpe</span><b>{metrics.sharpe}</b></article><article><span>成本</span><b>{metrics.costImpactPct}%</b></article></div>:<p>{value.result.dataStatus}</p>}<small>{value.result.reliability.message} · 历史回测不代表未来收益。</small></div>}
function Empty({title,detail}:{title:string;detail:string}){return <div className="nl-strategy-empty"><Sparkles/><b>{title}</b><span>{detail}</span></div>}
