"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowRight, CheckCircle2, Clock3, ShieldCheck, Users } from "lucide-react";
import { pick, useI18n } from "../i18n";
import { PARTICIPANT_SEGMENTS, type ParticipantRelation, type ParticipantSegment } from "../lib/user-study-validation";
import { StrategyResearchFlow, type StrategyLabStudyDetails, type StrategyLabStudyEvent } from "./strategy-research/strategy-research-flow";

const labels:Record<ParticipantSegment,{zh:string;en:string;detailZh:string;detailEn:string}>={
  "投资经验不足1年":{zh:"投资经验不足 1 年",en:"Less than one year of investing",detailZh:"仍在建立自己的投资方法",detailEn:"Still building an investing method"},
  "ETF或长期持有":{zh:"主要持有 ETF 或长期投资",en:"Mainly ETFs or long-term holdings",detailZh:"交易不频繁，更重视稳定性",detailEn:"Trades less often and values stability"},
  "近3个月主动交易":{zh:"近 3 个月有主动交易",en:"Actively traded in the past 3 months",detailZh:"近期做过主动买卖决定",detailEn:"Recently made an active buy or sell"},
};
const buildId=process.env.NEXT_PUBLIC_BUILD_ID??"local-unversioned";

export function StrategyLabPilot(){
  const {isEnglish}=useI18n();
  const [started,setStarted]=useState(false);const [relation,setRelation]=useState<ParticipantRelation>();const [segment,setSegment]=useState<ParticipantSegment>();const [inviteCode,setInviteCode]=useState("");const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  const [finished,setFinished]=useState(false);const [answers,setAnswers]=useState<Array<boolean|undefined>>([undefined,undefined,undefined]);const [understandingSubmitted,setUnderstandingSubmitted]=useState(false);
  const sessionId=useRef("");const startedAt=useRef(0);const completed=useRef(false);const runStartedAt=useRef(0);const runAttempt=useRef(0);const eventQueue=useRef<Promise<void>>(Promise.resolve());

  useEffect(()=>{sessionId.current=`lab-${crypto.randomUUID()}`;return()=>{if(!startedAt.current||completed.current||!segment)return;const payload=JSON.stringify({sessionId:sessionId.current,event:"abandoned",participantSegment:segment,inviteCode,durationMs:Date.now()-startedAt.current,buildId});if(navigator.sendBeacon)navigator.sendBeacon("/api/evaluation/strategy-lab",new Blob([payload],{type:"application/json"}));else void fetch("/api/evaluation/strategy-lab",{method:"POST",headers:{"content-type":"application/json"},body:payload,keepalive:true})}},[inviteCode,segment]);

  const postEvent=useCallback(async(event:StrategyLabStudyEvent|"lab_viewed",details:StrategyLabStudyDetails={})=>{if(!segment)throw new Error("请先选择参与者类型");const response=await fetch("/api/evaluation/strategy-lab",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId:sessionId.current,event,participantSegment:segment,inviteCode,durationMs:startedAt.current?Date.now()-startedAt.current:undefined,buildId,...details})});const body=await response.json() as {message?:string;participantRelation?:ParticipantRelation};if(!response.ok)throw new Error(body.message??"体验事件记录失败");return body},[inviteCode,segment]);
  const enqueue=useCallback((event:StrategyLabStudyEvent,details:StrategyLabStudyDetails={})=>{const next=eventQueue.current.then(async()=>{if(event==="run_started"){runAttempt.current+=1;runStartedAt.current=Date.now()}if(["run_started","run_completed","run_failed","result_viewed"].includes(event))details={...details,attemptIndex:runAttempt.current};if(event==="run_completed"&&runStartedAt.current)details={...details,durationMs:Date.now()-runStartedAt.current};await postEvent(event,details)});eventQueue.current=next.catch(()=>undefined);return next},[postEvent]);
  const record=useCallback((event:StrategyLabStudyEvent,details:StrategyLabStudyDetails={})=>{void enqueue(event,details).then(()=>{if(event==="save_completed"){completed.current=true;setFinished(true)}}).catch(error=>setMessage(error instanceof Error?error.message:"体验事件记录失败"))},[enqueue]);

  async function begin(){if(!segment||!consent||!inviteCode.trim())return;setBusy(true);setMessage("");try{startedAt.current=Date.now();const body=await postEvent("lab_viewed");setRelation(body.participantRelation);setStarted(true)}catch(error){startedAt.current=0;setMessage(error instanceof Error?error.message:"体验码验证失败")}finally{setBusy(false)}}
  function answer(index:number,value:boolean){setAnswers(current=>current.map((item,itemIndex)=>itemIndex===index?value:item))}
  async function submitUnderstanding(){if(answers.some(item=>item===undefined))return;setBusy(true);setMessage("");try{const correct=[true,false,true];const understandingScore=answers.reduce((score,item,index)=>score+(item===correct[index]?1:0),0);await enqueue("comprehension_submitted",{understandingScore});setUnderstandingSubmitted(true)}catch(error){setMessage(error instanceof Error?error.message:"理解检查提交失败")}finally{setBusy(false)}}

  if(started&&relation)return <div className="strategy-lab-pilot"><aside className="strategy-lab-task-note"><CheckCircle2/><span><strong>{pick(isEnglish,"请按自己的理解完成，不需要寻找“正确答案”","Use your own judgment; there is no correct answer")}</strong><small>{pick(isEnglish,"从两个入口任选其一，看到比较结果后选择一个单独方法并保存。","Choose either entry, review the comparison, then select and save one individual method.")}</small></span></aside>{message&&<p className="pilot-error" role="alert">{message}</p>}{finished&&<section className="strategy-lab-understanding" aria-labelledby="strategy-lab-understanding-title"><header><CheckCircle2/><div><h2 id="strategy-lab-understanding-title">{pick(isEnglish,"研究方法已保存，再确认三件事","Method saved—check three ideas")}</h2><p>{pick(isEnglish,"这不是满意度题，用来判断页面有没有把比较规则讲清楚。","This is not a satisfaction survey. It checks whether the comparison rules were clear.")}</p></div></header>{understandingSubmitted?<strong>{pick(isEnglish,"理解检查已化名记录，谢谢。","Your pseudonymous comprehension check was recorded. Thank you.")}</strong>:<><div>{[pick(isEnglish,"传统参照与候选使用相同股票样本、时间和成本。","The fixed reference and candidates use the same stock sample, dates and costs."),pick(isEnglish,"锁定测试只用于验收，不用于继续调参。","The final check is for acceptance only and is never used for further tuning."),pick(isEnglish,"这次历史结果不能保证未来表现。","These historical results cannot guarantee future performance.")].map((question,index)=><fieldset key={question}><legend>{question}</legend><button type="button" aria-pressed={answers[index]===true} className={answers[index]===true?"selected":""} onClick={()=>answer(index,true)}>{pick(isEnglish,"对","True")}</button><button type="button" aria-pressed={answers[index]===false} className={answers[index]===false?"selected":""} onClick={()=>answer(index,false)}>{pick(isEnglish,"不对","False")}</button></fieldset>)}</div><button className="pilot-primary" disabled={busy||answers.some(item=>item===undefined)} onClick={()=>void submitUnderstanding()}>{busy?pick(isEnglish,"正在提交…","Submitting…"):pick(isEnglish,"提交理解检查","Submit comprehension check")}</button></>}</section>}<StrategyResearchFlow onStudyEvent={record}/></div>;

  return <section className="pilot-intro strategy-lab-intro"><header><span>{pick(isEnglish,"策略研究室 · 受邀无引导体验","Strategy Lab · invited unmoderated study")}</span><h2>{pick(isEnglish,"用一句话完成一次策略研究，约 5 分钟","Complete one strategy study from a single sentence in about 5 minutes")}</h2><p>{pick(isEnglish,"我们观察你能否自己看懂规则、比较和保存。系统不会推荐股票，也没有标准答案。","We are observing whether the rules, comparison and save flow make sense without help. The system does not recommend stocks.")}</p></header>
    <div className="pilot-task-brief"><Clock3/><span><strong>{pick(isEnglish,"你的任务","Your task")}</strong><small>{pick(isEnglish,"提出一个想法或目标，确认规则，运行统一历史比较，然后保存一个你看得懂的研究方法。","Describe an idea or goal, review the rules, run a consistent historical comparison, then save one method you understand.")}</small></span></div>
    <label className="strategy-lab-invite"><span>{pick(isEnglish,"受邀体验码","Invitation code")}</span><input value={inviteCode} maxLength={120} autoComplete="off" onChange={event=>setInviteCode(event.target.value)} placeholder={pick(isEnglish,"由研究负责人提供","Provided by the study owner")}/><small>{pick(isEnglish,"体验码由服务器决定该记录属于外部样本还是内部排错，页面不能自行选择。","The server binds this code to an external cohort or internal debugging; the page cannot self-declare the relationship.")}</small></label>
    <fieldset><legend>{pick(isEnglish,"请选择最符合你的情况","Choose the closest description")}</legend>{PARTICIPANT_SEGMENTS.map(item=>{const label=labels[item];return <button type="button" key={item} className={segment===item?"selected":""} aria-pressed={segment===item} onClick={()=>setSegment(item)}><Users/><span><strong>{isEnglish?label.en:label.zh}</strong><small>{isEnglish?label.detailEn:label.detailZh}</small></span>{segment===item&&<CheckCircle2/>}</button>})}</fieldset>
    <label className="pilot-consent strategy-lab-consent"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/><span>{pick(isEnglish,"我同意记录化名化的步骤、耗时和错误；不会保存输入正文、股票代码、金额或身份。","I consent to pseudonymous step, timing and error events. Prompts, tickers, amounts and identity are not stored.")}</span></label>
    {message&&<p className="pilot-error" role="alert">{message}</p>}<button className="pilot-primary" disabled={busy||!segment||!consent||!inviteCode.trim()} onClick={()=>void begin()}>{busy?pick(isEnglish,"正在验证…","Checking…"):pick(isEnglish,"开始体验任务","Start the task")}<ArrowRight/></button>
    <footer><ShieldCheck/>{pick(isEnglish,"可随时关闭退出；未完成会记为一次化名化放弃，用于发现流程障碍。","You can leave at any time. An incomplete session is recorded pseudonymously to identify workflow barriers.")}</footer>
  </section>;
}
