import {DATA_SOURCE_REGISTRY,MODULE_REGISTRY,TOOL_CATALOG,WORKFLOW_REGISTRY} from "./agent-registry";
import {ENGINE_REGISTRY} from "./quant-engine-router";
import {STRATEGY_REGISTRY} from "./quant-research";
import {CAPABILITY_MANIFEST_GENERATED_AT,GENERATED_ROUTE_CAPABILITIES} from "./generated-capability-manifest";
import {WORKSPACE_TEMPLATES} from "./personal-workbench";
import type {AIProviderProfile} from "./ai-provider-catalog";

export type CapabilityStatus="available"|"beta"|"planned"|"disabled"|"unavailable";
export type CapabilityCategory="page"|"api"|"tool"|"module"|"provider"|"data_source"|"workflow"|"engine";
export type CapabilityDocument={capability_id:string;name:string;category:CapabilityCategory;description:string;status:CapabilityStatus;route:string|null;inputs:string[];outputs:string[];requirements:string[];limitations:string[];permissions:string[];requires_confirmation:boolean;supports_agent:boolean;supports_workspace:boolean;data_sources:string[];example_requests:string[];last_updated:string;version:string;source:"registry"|"api"|"generated"|"manual";knowledge_type:"platform_capabilities"};
export type CapabilityHit=Pick<CapabilityDocument,"capability_id"|"name"|"category"|"status"|"route"|"inputs"|"outputs"|"limitations"|"permissions"|"last_updated"|"version"|"source"|"knowledge_type">&{score:number;why_relevant:string;next_action:"open"|"configure"|"run"|"ask_user"};
export type CapabilityChunk={chunk_id:string;capability_id:string;section:string;content:string;embedding:number[];content_hash:string;version:string;indexed_at:string};

const UPDATED_AT=CAPABILITY_MANIFEST_GENERATED_AT;
const routeName=(route:string)=>route==="/"?"首页":route.split("/").filter(Boolean).map(part=>part.replaceAll("-"," ")).join(" / ");
const page=(id:string,name:string,route:string,description:string,status:CapabilityStatus="available"):CapabilityDocument=>({capability_id:id,name,category:"page",description,status,route,inputs:[],outputs:["可交互页面"],requirements:[],limitations:[],permissions:["登录用户保存个人数据"],requires_confirmation:false,supports_agent:true,supports_workspace:true,data_sources:[],example_requests:[`打开${name}`,`${name}能做什么`],last_updated:UPDATED_AT,version:"1.0",source:"manual",knowledge_type:"platform_capabilities"});
const curatedPages=[page("page_home","首页","/","目标入口、当前工作台和最近状态"),page("page_agent","任务助手","/agent","拆解自然语言目标、调用已授权工具并预览工作台修改"),page("page_workspace","模块化工作台","/workspace","手工、自然语言和 JSON 配置工作台"),page("page_etf","ETF 诊断","/etf-tool","搜索 ETF、穿透持仓并检查重复暴露"),page("page_trade","交易复盘","/trade-tool","导入 CSV，进行 FIFO 归因和行为复盘"),page("page_quant","低频量化研究","/quant","用自然语言创建低频研究、回测和纸面模拟","beta"),page("page_ai","AI 模型设置","/ai-settings","查看和切换已配置模型"),page("page_features","产品能力说明","/features","面向组员、测试用户和评委展示实时功能状态、产品差异、限制与可追溯能力问答"),page("page_privacy","数据与隐私","/profile","管理个人偏好与数据边界")];

const productWorkflows:CapabilityDocument[]=[
  {capability_id:"workflow_decision_layer",name:"研究到决策闭环",category:"workflow",description:"在行情、公告和财务信息之上，连接用户理由、持仓影响、个人规则、行动前确认与后续复核。区别于通用聊天工具的是确定性计算、来源追踪和持续决策记录。",status:"available",route:"/opportunity",inputs:["公开信息","用户理由","模拟或手工持仓","个人规则"],outputs:["事实与推断拆分","组合影响","规则冲突","待确认行动"],requirements:[],limitations:["不推荐股票","不预测涨跌","不连接券商或执行交易"],permissions:["金融数据只读","任何配置修改先确认"],requires_confirmation:true,supports_agent:true,supports_workspace:true,data_sources:["market_public","announcement_public","user_portfolio"],example_requests:["为什么不用 ChatGPT","为什么不用同花顺","安心看股的核心差异是什么","从研究到决策怎么完成"],last_updated:UPDATED_AT,version:"1.0",source:"registry",knowledge_type:"platform_capabilities"},
  {capability_id:"workflow_no_key_fallback",name:"无 API Key 降级使用",category:"workflow",description:"未配置外部模型时，行情查询、规则计算、ETF 重合、交易归因、能力检索和演示流程仍可使用；需要生成式解释的步骤会明确显示规则版结果或不可用状态。",status:"available",route:"/ai-settings",inputs:["无需外部模型密钥"],outputs:["规则计算结果","明确降级状态","可追溯能力问答"],requirements:[],limitations:["不会假装调用真实模型","开放模型能力取决于服务器部署资源"],permissions:["密钥仅后端使用"],requires_confirmation:false,supports_agent:true,supports_workspace:false,data_sources:[],example_requests:["没有 API Key 能用什么","模型连不上怎么办","默认开源模型是否可用"],last_updated:UPDATED_AT,version:"1.0",source:"registry",knowledge_type:"platform_capabilities"},
  {capability_id:"workflow_pitch_demo",name:"90 秒产品演示",category:"workflow",description:"用固定、可重复的场景展示消息核实、仓位影响、个人规则冲突和用户修改前后变化，不依赖实时行情或外部模型。",status:"available",route:"/demo",inputs:["演示场景"],outputs:["完整决策审查流程","修改前后对比"],requirements:[],limitations:["演示数据不代表实时市场"],permissions:["不执行交易"],requires_confirmation:false,supports_agent:true,supports_workspace:true,data_sources:["demo_snapshot"],example_requests:["如何演示产品","课堂 Pitch 走哪条路径","给组员看目前进度"],last_updated:UPDATED_AT,version:"1.0",source:"registry",knowledge_type:"platform_capabilities"}
];

export function buildCapabilityRegistry(providers:AIProviderProfile[]=[]):CapabilityDocument[]{
  const knownPages=new Set(curatedPages.map(item=>item.route));
  const discovered=GENERATED_ROUTE_CAPABILITIES.filter(item=>item.kind==="page"&&!knownPages.has(item.route)).map<CapabilityDocument>(item=>({capability_id:`page_auto_${item.route.replace(/[^a-z0-9]+/gi,"_")||"home"}`,name:routeName(item.route),category:"page",description:`自动发现的页面入口 ${item.route}`,status:"available",route:item.route,inputs:[],outputs:["可交互页面"],requirements:[],limitations:["页面说明来自构建清单；业务能力以已注册工具为准"],permissions:["以当前登录与页面权限为准"],requires_confirmation:false,supports_agent:true,supports_workspace:false,data_sources:[],example_requests:[`打开 ${item.route}`],last_updated:UPDATED_AT,version:"generated",source:"generated",knowledge_type:"platform_capabilities"}));
  const apis=GENERATED_ROUTE_CAPABILITIES.filter(item=>item.kind==="api").map<CapabilityDocument>(item=>({capability_id:`api_${item.route.replace(/[^a-z0-9]+/gi,"_")}`,name:`${item.methods.join("/")||"API"} ${item.route}`,category:"api",description:`自动发现的接口 ${item.route}`,status:"available",route:item.route,inputs:["按接口契约提交参数"],outputs:["结构化 JSON"],requirements:[],limitations:["字段口径以接口响应和对应工具注册信息为准"],permissions:["以当前用户与接口权限为准"],requires_confirmation:item.methods.some(method=>method!=="GET"),supports_agent:false,supports_workspace:false,data_sources:[],example_requests:[],last_updated:UPDATED_AT,version:"generated",source:"generated",knowledge_type:"platform_capabilities"}));
  const tools=TOOL_CATALOG.map<CapabilityDocument>(item=>({capability_id:`tool_${item.toolId}`,name:item.name,category:"tool",description:item.description,status:item.enabled?"available":"disabled",route:item.category==="quant"?"/quant":item.toolId.includes("etf")?"/etf-tool":item.toolId.includes("trade")?"/trade-tool":"/agent",inputs:Object.keys(item.inputSchema),outputs:Object.keys(item.outputSchema),requirements:item.dataSources,limitations:item.permissionLevel==="restricted"?["产品安全策略禁止执行"]:[],permissions:[item.permissionLevel],requires_confirmation:item.permissionLevel!=="safe",supports_agent:item.permissionLevel!=="restricted",supports_workspace:true,data_sources:item.dataSources,example_requests:item.keywords.slice(0,4),last_updated:UPDATED_AT,version:item.version,source:"registry",knowledge_type:"platform_capabilities"}));
  const modules=MODULE_REGISTRY.map<CapabilityDocument>(item=>({capability_id:`module_${item.moduleId}`,name:item.name,category:"module",description:`可复用的${item.name}工作台模块`,status:"available",route:"/workspace",inputs:item.requiredSources,outputs:["工作台卡片"],requirements:item.requiredSources,limitations:[],permissions:["修改前确认"],requires_confirmation:true,supports_agent:true,supports_workspace:true,data_sources:item.requiredSources,example_requests:[`把${item.name}加入工作台`],last_updated:UPDATED_AT,version:item.version,source:"registry",knowledge_type:"platform_capabilities"}));
  const sources=DATA_SOURCE_REGISTRY.map<CapabilityDocument>(item=>({capability_id:`source_${item.sourceId}`,name:item.name,category:"data_source",description:item.scope,status:item.available?"available":"unavailable",route:null,inputs:[],outputs:["结构化工具数据"],requirements:[],limitations:item.available?[]:["尚未授权或接入"],permissions:item.sourceId.includes("user")?["用户主动提供"]:[],requires_confirmation:false,supports_agent:item.available,supports_workspace:item.available,data_sources:[item.sourceId],example_requests:[],last_updated:UPDATED_AT,version:"1.0",source:"registry",knowledge_type:"platform_capabilities"}));
  const workflows=Object.entries(WORKFLOW_REGISTRY).map<CapabilityDocument>(([id,steps])=>({capability_id:`workflow_${id}`,name:`${id} 流程`,category:"workflow",description:`可组合步骤：${steps.join(" → ")}`,status:"available",route:"/workspace",inputs:["用户目标"],outputs:["可确认工作流"],requirements:[],limitations:[],permissions:["修改前确认"],requires_confirmation:true,supports_agent:true,supports_workspace:true,data_sources:[],example_requests:[`创建${id}流程`],last_updated:UPDATED_AT,version:"1.0",source:"registry",knowledge_type:"platform_capabilities"}));
  const workspaceTemplates=Object.entries(WORKSPACE_TEMPLATES).map<CapabilityDocument>(([id,item])=>({capability_id:`workspace_template_${id}`,name:item.name,category:"workflow",description:item.description,status:"available",route:"/workspace",inputs:["用户目标","明确确认"],outputs:["工作台模块组合","工作流","提醒频率"],requirements:[],limitations:["模板只是界面和流程起点，不是投资适当性结论"],permissions:["修改前确认"],requires_confirmation:true,supports_agent:true,supports_workspace:true,data_sources:[],example_requests:[`创建${item.name}`],last_updated:UPDATED_AT,version:"1.0",source:"registry",knowledge_type:"platform_capabilities"}));
  const strategies=STRATEGY_REGISTRY.map<CapabilityDocument>(item=>({capability_id:`strategy_${item.id}`,name:item.name,category:"workflow",description:item.description,status:item.backtestSupported?"beta":"available",route:"/quant",inputs:["标的","频率",...item.requiredData],outputs:item.backtestSupported?["历史回测","可信度检查","纸面模拟"]:["研究配置","风险解释"],requirements:item.requiredData,limitations:item.limitations,permissions:["配置确认","不支持真实交易"],requires_confirmation:true,supports_agent:true,supports_workspace:true,data_sources:item.requiredData,example_requests:[`创建${item.name}策略`],last_updated:UPDATED_AT,version:"1.0",source:"registry",knowledge_type:"platform_capabilities"}));
  const engines=ENGINE_REGISTRY.map<CapabilityDocument>(item=>({capability_id:`engine_${item.engine_id}`,name:item.display_name,category:"engine",description:item.data_processing,status:item.status==="healthy"?"available":"unavailable",route:"/quant",inputs:item.supports,outputs:["统一研究结果"],requirements:item.installed?[]:["后台适配器尚未安装"],limitations:item.limitations,permissions:[item.production_approved?"可运行":"不可执行"],requires_confirmation:false,supports_agent:item.status==="healthy",supports_workspace:true,data_sources:[],example_requests:[`使用${item.display_name}`],last_updated:UPDATED_AT,version:item.version,source:"registry",knowledge_type:"platform_capabilities"}));
  const models=providers.map<CapabilityDocument>(item=>({capability_id:`provider_${item.providerId}`,name:item.displayName,category:"provider",description:item.description,status:item.enabled&&item.connectionStatus==="available"?"available":"unavailable",route:"/ai-settings",inputs:["自然语言任务"],outputs:["规划或解释"],requirements:item.secretStatus==="missing"?["需要服务器端或个人安全配置"]:[],limitations:[item.privacyLabel],permissions:[item.mode??"external"],requires_confirmation:item.mode==="external",supports_agent:item.connectionStatus==="available",supports_workspace:false,data_sources:[],example_requests:[`使用${item.displayName}`],last_updated:UPDATED_AT,version:item.model||"未配置",source:"registry",knowledge_type:"platform_capabilities"}));
  return [...curatedPages,...productWorkflows,...discovered,...apis,...tools,...modules,...sources,...strategies,...workflows,...workspaceTemplates,...engines,...models];
}

function tokens(value:string){const normalized=value.toLowerCase().replace(/[^\p{L}\p{N}]+/gu," ");const words=normalized.split(/\s+/).filter(Boolean);const compact=normalized.replaceAll(" ","");const grams=Array.from({length:Math.max(0,compact.length-1)},(_,i)=>compact.slice(i,i+2));return [...new Set([...words,...grams])];}
export function embedCapabilityText(value:string,dimensions=64){const vector=Array.from({length:dimensions},()=>0);for(const token of tokens(value)){let hash=2166136261;for(const char of token){hash^=char.codePointAt(0)??0;hash=Math.imul(hash,16777619);}vector[Math.abs(hash)%dimensions]+=1;}const norm=Math.hypot(...vector)||1;return vector.map(value=>+(value/norm).toFixed(6));}
export function capabilityDocumentText(item:CapabilityDocument){return [`# ${item.name}`,`状态：${item.status}`,`类别：${item.category}`,`功能说明：${item.description}`,`使用方式：${item.example_requests.join("；")||"从对应入口使用"}`,`输入参数：${item.inputs.join("；")||"无"}`,`输出结果：${item.outputs.join("；")||"无"}`,`限制：${item.limitations.join("；")||"无"}`,`入口：${item.route??"无独立页面"}`,`权限：${item.permissions.join("；")||"无额外权限"}`,`更新时间：${item.last_updated}`,`版本：${item.version}`].join("\n");}
export function chunkCapability(item:CapabilityDocument,indexedAt=new Date().toISOString()):CapabilityChunk[]{const sections=[{section:"overview",content:[item.name,item.description,`状态 ${item.status}`,`入口 ${item.route??"无"}`].join("\n")},{section:"contract",content:[`输入 ${item.inputs.join("；")||"无"}`,`输出 ${item.outputs.join("；")||"无"}`,`数据 ${item.data_sources.join("；")||"无"}`].join("\n")},{section:"limits",content:[`限制 ${item.limitations.join("；")||"无"}`,`权限 ${item.permissions.join("；")||"无"}`,`版本 ${item.version}`,`更新时间 ${item.last_updated}`].join("\n")}];return sections.map(({section,content})=>{const hash=stableHash(`${item.capability_id}|${section}|${content}`);return {chunk_id:`${item.capability_id}:${section}`,capability_id:item.capability_id,section,content,embedding:embedCapabilityText(content),content_hash:hash,version:item.version,indexed_at:indexedAt};});}
export function stableHash(value:string){let hash=2166136261;for(const char of value){hash^=char.codePointAt(0)??0;hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16).padStart(8,"0");}
export function registryVersion(registry:CapabilityDocument[]){return stableHash(registry.slice().sort((a,b)=>a.capability_id.localeCompare(b.capability_id)).map(item=>`${item.capability_id}:${item.status}:${item.version}:${item.route}:${stableHash(capabilityDocumentText(item))}`).join("|"));}
export function searchCapabilities(query:string,registry:CapabilityDocument[],options:{route?:string;limit?:number;statuses?:CapabilityStatus[]}={}):CapabilityHit[]{const wanted=new Set(tokens(query));const queryVector=embedCapabilityText(query);const statuses=options.statuses??["available","beta","planned","disabled","unavailable"];return registry.filter(item=>statuses.includes(item.status)).map(item=>{const hay=new Set(tokens(capabilityDocumentText(item)));let lexical=0;for(const token of wanted)if(hay.has(token))lexical+=token.length>2?3:1;const vector=embedCapabilityText(capabilityDocumentText(item));const semantic=vector.reduce((sum,value,index)=>sum+value*(queryVector[index]??0),0);let score=lexical+semantic*2;if(options.route&&item.route===options.route)score+=2;if(/能做什么|有哪些|支持什么|平台/.test(query))score+=item.status==="available"?1:0;return {...item,score:+score.toFixed(4),why_relevant:item.description,next_action:item.status==="available"||item.status==="beta"?(item.route?"open":"run"):"ask_user"} as CapabilityHit;}).filter(item=>item.score>.12).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,options.limit??8);}
export function capabilityHealth(registry:CapabilityDocument[]){return {status:registry.length?"healthy":"unavailable",indexed_count:registry.length,pending_count:0,failed_count:0,available_count:registry.filter(item=>item.status==="available").length,beta_count:registry.filter(item=>item.status==="beta").length,unavailable_count:registry.filter(item=>item.status==="unavailable").length,last_success_at:UPDATED_AT,current_version:registryVersion(registry),stale_documents:[],sources:["generated_route_manifest","tool_registry","module_registry","data_source_registry","strategy_registry","workflow_registry","engine_registry","provider_registry"]};}
