import {freshness,reliability,type ReliabilityState} from "./failure-control";

export type QuantPricePoint={date:string;close:number;volume?:number;benchmarkClose?:number;availableAt?:string;suspended?:boolean;limitUp?:boolean;limitDown?:boolean;dividend?:number};
export type GateStatus="passed"|"warning"|"blocked";
export type DataQualityReport={status:"pass"|"warning"|"blocked";coverage:{rows:number;start_date:string|null;end_date:string|null;frequency:"daily"};freshness:{updated_at:string|null;max_age:number;status:"fresh"|"stale"|"unknown"};missing_dates:string[];duplicate_dates:string[];anomalies:string[];stale_fields:string[];adjustment_mode:string;warnings:string[];blocking_reasons:string[];reliability:ReliabilityState};
export type CNMarketRulesConfig={market:"CN_A";asset_type:"stock"|"etf"|"index"|"fund";t_plus_one:boolean;price_limit:{standard_pct:number;st_pct:number|null};suspension_policy:"no_trade";adjustment:"qfq"|"hfq"|"raw";commission_bps:number;stamp_tax_bps:number;transfer_fee_bps:number;slippage_bps:number;lot_size:number;rule_version:string};
export type RuleCheck={status:GateStatus;rule_version:string;config:CNMarketRulesConfig;checks:Array<{id:string;status:GateStatus;message:string}>;warnings:string[];blocking_reasons:string[]};
export type LookAheadReport={status:GateStatus;violations:Array<{field:string;observed_at:string;available_at:string;message:string}>;checked_features:string[];future_fields:string[];warnings:string[]};
export type UniverseReport={status:GateStatus;universe_mode:"single_asset"|"historical"|"current_snapshot";includes_delisted:boolean|null;historical_constituents:boolean;code_changes_checked:boolean;listing_dates_checked:boolean;warnings:string[];blocking_reasons:string[]};
export type CredibilityReport={status:GateStatus;score:number;data_quality:DataQualityReport;cn_market_rules:RuleCheck;lookahead_check:LookAheadReport;universe_check:UniverseReport;costs_included:boolean;out_of_sample:boolean;parameter_sensitivity:"completed"|"missing";allow_backtest:boolean;allow_signal:boolean;summary:string};

export function defaultCNMarketRules(assetType:CNMarketRulesConfig["asset_type"]="stock",adjustment:CNMarketRulesConfig["adjustment"]="qfq"):CNMarketRulesConfig{return {market:"CN_A",asset_type:assetType,t_plus_one:assetType==="stock",price_limit:{standard_pct:assetType==="stock"?10:20,st_pct:assetType==="stock"?5:null},suspension_policy:"no_trade",adjustment,commission_bps:3,stamp_tax_bps:assetType==="stock"?5:0,transfer_fee_bps:assetType==="stock"?.1:0,slippage_bps:5,lot_size:assetType==="fund"?1:100,rule_version:"cn-market-rules-2026.1"};}

export function checkDataQuality(points:QuantPricePoint[],options:{source?:string;adjustment?:string;dataTimestamp?:string|null;nowMs?:number}={}):DataQualityReport{const dates=points.map(item=>item.date);const counts=new Map<string,number>();for(const date of dates)counts.set(date,(counts.get(date)??0)+1);const duplicate=[...counts].filter(([,count])=>count>1).map(([date])=>date);const anomalies=points.flatMap((item,index)=>{const issues:string[]=[];if(!/^\d{4}-\d{2}-\d{2}$/.test(item.date)||!Number.isFinite(item.close)||item.close<=0)issues.push(`第 ${index+1} 行日期或价格无效`);if(item.volume!==undefined&&(!Number.isFinite(item.volume)||item.volume<0))issues.push(`${item.date} 成交量无效`);if(index&&points[index-1].close>0&&Math.abs(item.close/points[index-1].close-1)>.35&&!item.suspended)issues.push(`${item.date} 单日价格变化超过 35%，需核对复权或异常数据`);return issues;});const sorted=[...new Set(dates.filter(date=>/^\d{4}-\d{2}-\d{2}$/.test(date)))].sort();const gaps:string[]=[];for(let i=1;i<sorted.length;i++){const days=(Date.parse(sorted[i])-Date.parse(sorted[i-1]))/86400000;if(days>10)gaps.push(`${sorted[i-1]} → ${sorted[i]}`);}const last=options.dataTimestamp??sorted.at(-1)??null;const fresh=freshness("market_daily",last,options.source??"用户或授权行情",null,options.nowMs);const blocking=[...(!points.length?["关键行情为空"]:[]),...(duplicate.length?["存在重复交易日"]:[]),...(anomalies.some(item=>item.includes("无效"))?["存在无效价格或日期"]:[])];const warnings=[...(gaps.length?[`发现 ${gaps.length} 个超过 10 天的日期间隔；可能包含停牌或数据缺口`]:[]),...(anomalies.filter(item=>!item.includes("无效"))),...(fresh.freshness_status!=="fresh"?["数据时间已过期或无法确认"]:[])];const status=blocking.length?"blocked":warnings.length?"warning":"pass";return {status,coverage:{rows:points.length,start_date:sorted[0]??null,end_date:sorted.at(-1)??null,frequency:"daily"},freshness:{updated_at:fresh.updated_at,max_age:fresh.max_age,status:fresh.freshness_status},missing_dates:gaps,duplicate_dates:duplicate,anomalies,stale_fields:fresh.freshness_status==="fresh"?[]:["market_prices"],adjustment_mode:options.adjustment??"unknown",warnings,blocking_reasons:blocking,reliability:reliability({status:status==="blocked"?"blocked":fresh.freshness_status==="stale"?"stale":status==="warning"?"degraded":"healthy",message:status==="blocked"?"数据质量检查未通过":status==="warning"?"数据可用于有限研究，但存在已标注限制":"数据质量检查通过",error_code:blocking.length?"DATA_QUALITY_BLOCKED":fresh.freshness_status==="stale"?"DATA_STALE":null,warnings:[...warnings,...blocking],retryable:blocking.length>0||fresh.freshness_status!=="fresh",data_timestamp:last,allow_signal:status!=="blocked"&&fresh.freshness_status==="fresh"})};}

export function checkCNMarketRules(points:QuantPricePoint[],config:CNMarketRulesConfig):RuleCheck{const checks=[{id:"t_plus_one",status:config.asset_type==="stock"&&!config.t_plus_one?"blocked":"passed",message:config.asset_type==="stock"?(config.t_plus_one?"股票按 T+1；信号与成交日期分离":"股票回测必须启用 T+1"):"非股票标的按所选品种结算规则核验"},{id:"price_limit",status:config.price_limit.standard_pct>0?"passed":"blocked",message:"涨跌停日按不可成交处理，不把理论信号当成成交"},{id:"suspension",status:config.suspension_policy==="no_trade"?"passed":"blocked",message:"停牌期间禁止模拟成交"},{id:"adjustment",status:["qfq","hfq","raw"].includes(config.adjustment)?"passed":"blocked",message:`信号与收益统一使用 ${config.adjustment} 口径`},{id:"costs",status:[config.commission_bps,config.stamp_tax_bps,config.transfer_fee_bps,config.slippage_bps].every(value=>Number.isFinite(value)&&value>=0)?"passed":"blocked",message:"佣金、税费、过户费与滑点已显式配置"},{id:"lot_size",status:config.lot_size>0?"warning":"blocked",message:`最小交易单位为 ${config.lot_size} 份；当前标准化净值回测不模拟实际份额取整`}] as Array<{id:string;status:GateStatus;message:string}>;const blocking=checks.filter(item=>item.status==="blocked").map(item=>item.message);const warnings=[...checks.filter(item=>item.status==="warning").map(item=>item.message),...(!points.some(item=>item.suspended||item.limitUp||item.limitDown)?["输入行情没有停牌和涨跌停字段；无法逐日复原成交限制"]:[])];return {status:blocking.length?"blocked":warnings.length?"warning":"passed",rule_version:config.rule_version,config,checks,warnings,blocking_reasons:blocking};}

export function checkLookAhead(points:QuantPricePoint[],parameters:Record<string,unknown>={}):LookAheadReport{const violations=points.flatMap(item=>item.availableAt&&Date.parse(item.availableAt)>Date.parse(`${item.date}T23:59:59Z`)?[{field:"price",observed_at:item.date,available_at:item.availableAt,message:"数据在该交易日之后才可见"}]:[]);const futureFields=Object.keys(parameters).filter(key=>/future|lookahead|next_|forward_return/i.test(key)&&Boolean(parameters[key]));if(futureFields.length)for(const field of futureFields)violations.push({field,observed_at:"strategy_config",available_at:"future",message:"参数引用未来信息"});return {status:violations.length?"blocked":"passed",violations,checked_features:["价格日期","available_at","策略参数","收盘信号次日成交"],future_fields:futureFields,warnings:violations.length?[]:["财报、新闻和社交特征接入时仍必须提供 available_at；本次仅检查价格序列"]};}

export function checkUniverse(input:{symbols?:string[];historicalConstituents?:boolean;includesDelisted?:boolean;codeChangesChecked?:boolean;listingDatesChecked?:boolean}={}):UniverseReport{const count=input.symbols?.length??1;if(count<=1)return {status:"passed",universe_mode:"single_asset",includes_delisted:null,historical_constituents:false,code_changes_checked:true,listing_dates_checked:true,warnings:["单标的时间序列不涉及股票池幸存者偏差；仍可能有数据修订偏差"],blocking_reasons:[]};const historical=Boolean(input.historicalConstituents);const warnings=historical?[]:["当前数据缺少历史成分和退市标的，结果可能存在幸存者偏差，不代表历史真实可投资范围。"] ;return {status:historical&&input.includesDelisted?"passed":"warning",universe_mode:historical?"historical":"current_snapshot",includes_delisted:input.includesDelisted??false,historical_constituents:historical,code_changes_checked:Boolean(input.codeChangesChecked),listing_dates_checked:Boolean(input.listingDatesChecked),warnings,blocking_reasons:[]};}

export function buildCredibilityReport(input:{points:QuantPricePoint[];source?:string;dataTimestamp?:string|null;adjustment?:string;parameters?:Record<string,unknown>;assetType?:CNMarketRulesConfig["asset_type"];symbols?:string[];historicalConstituents?:boolean;includesDelisted?:boolean;costsIncluded?:boolean;outOfSample?:boolean;parameterSensitivity?:boolean}):CredibilityReport{const data=checkDataQuality(input.points,{source:input.source,adjustment:input.adjustment,dataTimestamp:input.dataTimestamp});const rules=checkCNMarketRules(input.points,defaultCNMarketRules(input.assetType,input.adjustment==="backward"?"hfq":input.adjustment==="none"?"raw":"qfq"));const lookahead=checkLookAhead(input.points,input.parameters);const universe=checkUniverse({symbols:input.symbols,historicalConstituents:input.historicalConstituents,includesDelisted:input.includesDelisted});const blocked=data.status==="blocked"||rules.status==="blocked"||lookahead.status==="blocked";const warnings=[data.status,rules.status,lookahead.status,universe.status].filter(status=>status==="warning").length;const score=Math.max(0,100-(blocked?60:0)-warnings*10-(input.costsIncluded?0:15)-(input.outOfSample?0:10)-(input.parameterSensitivity?0:5));return {status:blocked?"blocked":warnings||score<85?"warning":"passed",score,data_quality:data,cn_market_rules:rules,lookahead_check:lookahead,universe_check:universe,costs_included:Boolean(input.costsIncluded),out_of_sample:Boolean(input.outOfSample),parameter_sensitivity:input.parameterSensitivity?"completed":"missing",allow_backtest:!blocked,allow_signal:!blocked&&data.reliability.allow_signal,summary:blocked?"关键可信度检查未通过，已阻断回测结果。":warnings?"回测可运行，但结论必须连同限制一起阅读。":"核心可信度检查通过。"};}

export function compareBacktestPaper(input:{backtestReturn?:number|null;paperReturn?:number|null;expectedSlippageBps?:number;actualSlippageBps?:number;expectedCostBps?:number;actualCostBps?:number;signalDifference?:number;positionDifference?:number}){const returnDifference=(input.paperReturn??0)-(input.backtestReturn??0);const slippageDifference=(input.actualSlippageBps??0)-(input.expectedSlippageBps??0);const costDifference=(input.actualCostBps??0)-(input.expectedCostBps??0);const signalDifference=input.signalDifference??0;const positionDifference=input.positionDifference??0;const magnitude=Math.abs(returnDifference)+Math.abs(slippageDifference)/100+Math.abs(costDifference)/100+Math.abs(signalDifference)*10+Math.abs(positionDifference)*10;const riskLevel=magnitude>20?"high":magnitude>8?"medium":"low";return {return_difference:+returnDifference.toFixed(4),slippage_difference:+slippageDifference.toFixed(2),cost_difference:+costDifference.toFixed(2),signal_difference:signalDifference,position_difference:positionDifference,risk_level:riskLevel,status:riskLevel==="high"?"blocked":"healthy",allow_signal:riskLevel!=="high",message:riskLevel==="high"?"回测与模拟偏差过大，策略应暂停并重新校准。":"偏差处于当前观察范围。"};}

export type SocialDataRecord={content_id:string;platform:string;source_url:string|null;published_at:string|null;collected_at:string;sample_type:"user_upload"|"licensed_api"|"public_sample";permission:"allowed"|"restricted"|"unknown";retention:"none"|"cache"|"persistent";text_hash:string;sentiment:string|null;topics:string[]};
export function validateSocialData(record:SocialDataRecord){const allowed=record.permission==="allowed"&&(record.sample_type==="user_upload"||record.sample_type==="licensed_api"||record.sample_type==="public_sample");return {status:allowed?"healthy":"blocked",allow_analysis:allowed,allow_persist:allowed&&record.retention!=="none",store_raw_text:false,message:allowed?"社交样本授权信息完整；默认只保存摘要、标签和哈希。":"授权不明确，禁止抓取、分析或持久化。",disclaimer:"社交讨论热度不代表投资价值或未来收益。"};}
