import type {QuantFrequency} from "./quant-research";

export type QuantTaskType="etf_strategy"|"stock_screening"|"factor_research"|"classic_backtest"|"machine_learning_research"|"reinforcement_learning_experiment"|"paper_trading"|"portfolio_allocation"|"risk_analysis"|"social_sentiment_strategy"|"event_driven_strategy"|"education_simulation";
export type QuantEngineId="native_ashare"|"backtrader"|"qlib"|"finrl"|"veighna";
export type ResearchMode="education"|"backtest"|"paper"|"candidate";
export type GoalParse={type:"quant_goal";goal:string;task_type:QuantTaskType;asset_type:"stock"|"etf"|"fund"|"index"|"unknown";assets:string[];universe:string[];frequency:QuantFrequency;horizon:string|null;risk_preference:"conservative"|"balanced"|"aggressive"|"unknown";max_drawdown:number|null;capital:number|null;mode:ResearchMode;automation_level:"manual"|"scheduled"|"confirm";data_requirements:string[];analysis_requirements:string[];missing_information:string[];questions:string[];risk_level:"low"|"medium"|"high"|"restricted"};
export type EngineDefinition={engine_id:QuantEngineId;internal_name:string;display_name:string;version:string;adapter_version:string;status:"healthy"|"unavailable"|"blocked";installed:boolean;production_approved:boolean;supports:QuantTaskType[];data_processing:string;limitations:string[];license_package:string|null};
export type EngineRoute={type:"engine_route";task_type:QuantTaskType;asset_type:GoalParse["asset_type"];frequency:QuantFrequency;complexity:"basic"|"advanced"|"experimental";selected_engine:QuantEngineId;engine_display_name:string;selection_reason:string;engine_visible_to_user:false;execution_status:"ready"|"degraded"|"blocked";fallback_engine:QuantEngineId|null;fallback_used:boolean;warnings:string[];requires_user_confirmation:false};
export type UnifiedStrategyDSL={strategy_id:string;name:string;task_type:QuantTaskType;engine:QuantEngineId;market:"CN_A";asset_type:"stock"|"etf"|"index"|"unknown";universe:string[];frequency:QuantFrequency;features:string[];conditions:Array<{field:string;operator:string;value:number|string|null;source:string}>;portfolio_rules:Record<string,number|string|boolean>;risk_rules:{max_drawdown:number|null;allow_live_order:false};costs:{commission_bps:number;stamp_duty_bps:number;transfer_fee_bps:number;slippage_bps:number};mode:ResearchMode;allow_live_order:false;data_requirements:string[];requires_confirmation:true};

export const ENGINE_REGISTRY:EngineDefinition[]=[
  {engine_id:"native_ashare",internal_name:"NativeAShareEngine",display_name:"平台低频策略引擎",version:"1.1.0",adapter_version:"native",status:"healthy",installed:true,production_approved:true,supports:["etf_strategy","stock_screening","classic_backtest","paper_trading","portfolio_allocation","risk_analysis","education_simulation"],data_processing:"统一日线数据 → 数据质量检查 → A 股规则层 → 下一交易日模拟",limitations:["当前以日频和低频研究为主","不训练机器学习模型"],license_package:null},
  {engine_id:"backtrader",internal_name:"BacktraderAdapter",display_name:"经典规则研究引擎",version:"not-installed",adapter_version:"0.1.0",status:"unavailable",installed:false,production_approved:false,supports:["classic_backtest","education_simulation"],data_processing:"统一 DSL 经适配器转换后进入经典事件回测",limitations:["当前部署未安装依赖","许可证与结果一致性审核未完成"],license_package:"backtrader"},
  {engine_id:"qlib",internal_name:"QlibAdapter",display_name:"因子与机器学习研究引擎",version:"not-installed",adapter_version:"0.1.0",status:"unavailable",installed:false,production_approved:false,supports:["factor_research","machine_learning_research","stock_screening","portfolio_allocation"],data_processing:"统一特征与历史股票池 → 训练/验证/样本外测试",limitations:["当前部署未安装依赖","需要历史股票池和横截面数据","许可证审核未完成"],license_package:"qlib"},
  {engine_id:"finrl",internal_name:"FinRLAdapter",display_name:"实验性强化学习研究引擎",version:"not-installed",adapter_version:"0.1.0",status:"unavailable",installed:false,production_approved:false,supports:["reinforcement_learning_experiment"],data_processing:"隔离实验环境中的历史数据训练与模拟",limitations:["仅限实验，不适合作为直接交易依据","当前部署未安装且未审核"],license_package:"finrl"},
  {engine_id:"veighna",internal_name:"VeighNaAdapter",display_name:"事件与纸面执行研究引擎",version:"not-installed",adapter_version:"0.1.0",status:"unavailable",installed:false,production_approved:false,supports:["event_driven_strategy","paper_trading","social_sentiment_strategy"],data_processing:"授权事件 → 事件时间校验 → 纸面执行模拟",limitations:["当前部署未安装依赖","不连接券商或真实账户","许可证审核未完成"],license_package:"veighna"},
];

export type LicenseEntry={package:string;version:string;license:string;source_url:string;commercial_review_required:boolean;notice_required:boolean;status:"approved"|"review"|"blocked"};
export const LICENSE_REGISTRY:LicenseEntry[]=[
  {package:"backtrader",version:"not-installed",license:"GPL-3.0",source_url:"https://github.com/mementum/backtrader",commercial_review_required:true,notice_required:true,status:"review"},
  {package:"qlib",version:"not-installed",license:"MIT",source_url:"https://github.com/microsoft/qlib",commercial_review_required:true,notice_required:true,status:"review"},
  {package:"finrl",version:"not-installed",license:"Apache-2.0",source_url:"https://github.com/AI4Finance-Foundation/FinRL",commercial_review_required:true,notice_required:true,status:"review"},
  {package:"veighna",version:"not-installed",license:"MIT",source_url:"https://github.com/vnpy/vnpy",commercial_review_required:true,notice_required:true,status:"review"},
];

const unique=<T,>(items:T[])=>[...new Set(items)];
const codes=(text:string)=>unique(text.match(/(?<!\d)[036159]\d{5}(?!\d)/g)??[]);
const frequency=(text:string):QuantFrequency=>/每月|月频/.test(text)?"monthly":/每周|周频/.test(text)?"weekly":/每天|每日|日频|收盘/.test(text)?"daily_close":/事件|新闻|公告|社交/.test(text)?"event":"manual";
const taskType=(text:string):QuantTaskType=>/强化学习|RL\b/i.test(text)?"reinforcement_learning_experiment":/机器学习|自己.*找规律|训练模型|横截面预测/i.test(text)?"machine_learning_research":/多因子|因子研究|价值.*动量|比较.*方法/.test(text)?"factor_research":/社交|情绪|小红书|雪球/.test(text)?"social_sentiment_strategy":/新闻|公告|事件驱动/.test(text)?"event_driven_strategy":/配置|资产配置|再平衡/.test(text)?"portfolio_allocation":/ETF.*策略|低频\s*ETF|ETF\s*低频/i.test(text)?"etf_strategy":/风险分析|持仓诊断|分析.*风险/.test(text)?"risk_analysis":/筛选|找出/.test(text)&&!/策略/.test(text)?"stock_screening":/模拟组合|纸面账户/.test(text)?"paper_trading":/学习|教学|入门/.test(text)?"education_simulation":/ETF/i.test(text)?"etf_strategy":"classic_backtest";

export function parseQuantGoal(raw:string):GoalParse{
  const goal=raw.trim().slice(0,4000);if(!goal)throw new Error("请描述想完成的研究目标");const type=taskType(goal);const assets=codes(goal);const asset_type=/ETF/i.test(goal)?"etf":/指数|沪深300|中证500/.test(goal)?"index":assets.length?"stock":"unknown";const max=goal.match(/(?:最大)?回撤[^\d]{0,10}(\d+(?:\.\d+)?)\s*%/);const money=goal.match(/(?:资金|本金|模拟)[^\d]{0,10}(\d+(?:\.\d+)?)\s*(万|元)?/);const freq=frequency(goal);const mode:ResearchMode=/模拟|纸面/.test(goal)?"paper":/回测|比较|历史/.test(goal)?"backtest":/学习/.test(goal)?"education":"candidate";const missing:string[]=[];const questions:string[]=[];
  if(asset_type==="unknown"&&!assets.length){missing.push("研究资产");questions.push("你想研究 ETF、股票、指数，还是自己的持仓？");}
  if(freq==="manual"&&!/手动|一次/.test(goal)){missing.push("运行频率或研究区间");questions.push("希望只运行一次，还是按日、周或月检查？");}
  if(max===null&&!/学习|教学/.test(goal)){missing.push("风险限制");questions.push("你最希望控制的是最大回撤、波动，还是单一资产占比？");}
  const experimental=["machine_learning_research","reinforcement_learning_experiment"].includes(type);return {type:"quant_goal",goal,task_type:type,asset_type,assets,universe:assets,frequency:freq,horizon:goal.match(/(?:近|过去)?\s*(\d+)\s*(年|月|周)/)?.[0]??null,risk_preference:/保守|低风险|稳健/.test(goal)?"conservative":/激进|高风险/.test(goal)?"aggressive":/平衡|适中/.test(goal)?"balanced":"unknown",max_drawdown:max?Number(max[1])/100:null,capital:money?Number(money[1])*(money[2]==="万"?10000:1):null,mode,automation_level:freq==="manual"?"manual":"scheduled",data_requirements:dataFor(type),analysis_requirements:analysisFor(type),missing_information:missing,questions:questions.slice(0,3),risk_level:experimental?"high":mode==="paper"?"medium":"low"};
}

function dataFor(type:QuantTaskType){const base=["A 股/ETF 日线行情","数据时间与复权口径"];if(["factor_research","machine_learning_research","stock_screening"].includes(type))base.push("财务与估值","历史股票池");if(["event_driven_strategy","social_sentiment_strategy"].includes(type))base.push("授权事件样本","事件发布时间");return base;}
function analysisFor(type:QuantTaskType){if(type==="factor_research")return ["价值、动量、低波动因子对比","换手率与稳定性","样本外检验"];if(type==="machine_learning_research")return ["特征与标签定义","训练/验证/测试切分","过拟合检查"];if(type==="reinforcement_learning_experiment")return ["实验环境定义","基线策略比较","训练稳定性"];if(type==="risk_analysis")return ["集中度","波动率","最大回撤"];return ["规则历史核验","最大回撤与成本","样本外表现"]}

export function routeQuantEngine(goal:GoalParse,requested?:QuantEngineId):EngineRoute{
  const automatic:QuantEngineId=goal.task_type==="reinforcement_learning_experiment"?"finrl":["factor_research","machine_learning_research"].includes(goal.task_type)?"qlib":["event_driven_strategy","social_sentiment_strategy"].includes(goal.task_type)?"veighna":"native_ashare";const chosen=requested??automatic;const definition=ENGINE_REGISTRY.find(item=>item.engine_id===chosen)!;const native=ENGINE_REGISTRY[0];const canFallback=!definition.installed&&native.supports.includes(goal.task_type);const actual=canFallback?native:definition;const complexity:["basic"|"advanced"|"experimental"][number]=["machine_learning_research","factor_research"].includes(goal.task_type)?"advanced":goal.task_type==="reinforcement_learning_experiment"?"experimental":"basic";const warnings:string[]=[];if(!definition.installed)warnings.push(`${definition.display_name}当前未安装，未生成任何该引擎结果。`);if(canFallback)warnings.push(`已降级为${native.display_name}；只执行它能够完整解释的规则部分。`);if(!actual.production_approved)warnings.push("该适配器尚未通过生产与许可证审核，任务已阻断。");return {type:"engine_route",task_type:goal.task_type,asset_type:goal.asset_type,frequency:goal.frequency,complexity,selected_engine:actual.engine_id,engine_display_name:actual.display_name,selection_reason:reasonFor(goal,actual,Boolean(requested)),engine_visible_to_user:false,execution_status:actual.status==="healthy"?(canFallback?"degraded":"ready"):"blocked",fallback_engine:canFallback?native.engine_id:null,fallback_used:canFallback,warnings,requires_user_confirmation:false};
}

function reasonFor(goal:GoalParse,engine:EngineDefinition,requested:boolean){if(requested)return `你要求切换研究方式；系统检查后选择${engine.display_name}，仍保留统一数据和 A 股规则检查。`;if(engine.engine_id==="native_ashare")return "该任务以低频规则、风险或纸面模拟为主，透明规则引擎更容易核对，也不需要机器学习。";if(engine.engine_id==="qlib")return "任务包含多因子、横截面或机器学习研究，需要训练/验证/样本外流程。";if(engine.engine_id==="finrl")return "只有明确的强化学习实验才进入该研究路径，结果仅用于历史实验。";return "任务依赖事件时间与纸面执行流程，需要事件驱动研究能力。";}

export function compileGoalToDSL(goal:GoalParse,route:EngineRoute):UnifiedStrategyDSL{return {strategy_id:`goal_strategy_${crypto.randomUUID()}`,name:goal.goal.slice(0,48),task_type:goal.task_type,engine:route.selected_engine,market:"CN_A",asset_type:goal.asset_type==="fund"?"unknown":goal.asset_type,universe:goal.universe,frequency:goal.frequency,features:goal.analysis_requirements,conditions:[],portfolio_rules:goal.capital?{paper_capital:goal.capital}:{},risk_rules:{max_drawdown:goal.max_drawdown,allow_live_order:false},costs:{commission_bps:3,stamp_duty_bps:5,transfer_fee_bps:.1,slippage_bps:5},mode:goal.mode,allow_live_order:false,data_requirements:goal.data_requirements,requires_confirmation:true};}

export function switchEnginePreview(goal:GoalParse,current:QuantEngineId,instruction:string){let target:QuantEngineId|null=/传统|透明|不要.*机器学习/.test(instruction)?"native_ashare":null;if(!target)target=/Qlib|因子/.test(instruction)?"qlib":/FinRL|强化学习/.test(instruction)?"finrl":/VeighNa|事件驱动/.test(instruction)?"veighna":/backtrader|经典/.test(instruction)?"backtrader":null;if(!target)throw new Error("请说明希望改成透明规则、经典回测、因子研究、强化学习或事件研究方式");const route=routeQuantEngine(goal,target);return {type:"engine_switch_preview",current_engine:current,target_engine:route.selected_engine,target_display_name:route.engine_display_name,route,changes:["数据处理方式可能变化","结果需要重新回测","运行成本与耗时可能变化","不同引擎结果不保证可直接比较"],requires_confirmation:true};}
