import { FACTORS } from "./catalog";
import { validateStrategyDSL } from "./strategy-dsl";
import type { FactorId, PeriodResult, PriceSeries, SegmentMetrics, StrategyDSL, StrategyEvaluation } from "./types";

const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:null;
const sd=(x:number[])=>{const m=mean(x);return m===null?null:Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/x.length)};
function value(id:FactorId,prices:number[],i:number){const n=FACTORS[id].lookback;if(i<n)return null;if(id==="momentum_60")return prices[i]/prices[i-60]-1;if(id==="reversal_5")return -(prices[i]/prices[i-5]-1);if(id==="trend_ma20_60"){const a=mean(prices.slice(i-19,i+1))!,b=mean(prices.slice(i-59,i+1))!;return a/b-1;}const returns=prices.slice(i-20,i+1).slice(1).map((v,j)=>v/prices[i-20+j]-1);return sd(returns);}
function ranks(rows:Array<{raw:number}>){const sorted=rows.map((r,i)=>({v:r.raw,i})).sort((a,b)=>a.v-b.v);const out=Array(rows.length).fill(0);sorted.forEach((r,i)=>out[r.i]=sorted.length===1?0:i/(sorted.length-1));return out;}
type PreparedRow={symbol:string;forward:number;raw:Record<FactorId,number>;vol:number;trend:number};
type PreparedPeriod={signal:string;date:string;end:string;rows:PreparedRow[]};
type PreparedData={monthly:PreparedPeriod[];biweekly:PreparedPeriod[]};
export type ResearchSplit={research_end:string;validation_end:string;locked_test_start:string};
const preparedCache=new WeakMap<PriceSeries[],PreparedData>();
function prepare(input:PriceSeries[]):PreparedData{
  const cached=preparedCache.get(input);if(cached)return cached;
  const normalized=input.map(series=>{const prices=[...new Map(series.prices.filter(point=>/^\d{4}-\d{2}-\d{2}$/.test(point.date)&&Number.isFinite(point.close)&&point.close>0).map(point=>[point.date,point.close])).entries()].sort((a,b)=>a[0].localeCompare(b[0]));return {symbol:series.symbol,prices,indices:new Map(prices.map((point,index)=>[point[0],index])),closes:prices.map(point=>point[1])};});
  const dates=[...new Set(normalized.flatMap(series=>series.prices.map(point=>point[0])))].sort();
  const build=(frequency:"monthly"|"biweekly")=>{const every=frequency==="monthly"?20:10,holding=frequency==="monthly"?20:10;const periods:PreparedPeriod[]=[];for(let di=60;di+holding+1<dates.length;di+=every){const signal=dates[di],date=dates[di+1],end=dates[di+holding+1];const rows=normalized.flatMap(series=>{const signalIdx=series.indices.get(signal),entryIdx=series.indices.get(date),endIdx=series.indices.get(end);if(signalIdx===undefined||entryIdx===undefined||endIdx===undefined||signalIdx<60||!(signal<date&&date<end))return [];const raw={momentum_60:value("momentum_60",series.closes,signalIdx),low_volatility_20:value("low_volatility_20",series.closes,signalIdx),reversal_5:value("reversal_5",series.closes,signalIdx),trend_ma20_60:value("trend_ma20_60",series.closes,signalIdx)};if(Object.values(raw).some(item=>item===null))return [];return [{symbol:series.symbol,forward:series.closes[endIdx]/series.closes[entryIdx]-1,raw:raw as Record<FactorId,number>,vol:raw.low_volatility_20 as number,trend:raw.trend_ma20_60 as number}]});periods.push({signal,date,end,rows});}return periods;};
  const prepared={monthly:build("monthly"),biweekly:build("biweekly")};preparedCache.set(input,prepared);return prepared;
}
export function deriveResearchSplit(input:PriceSeries[]):ResearchSplit{const dates=[...new Set(input.flatMap(series=>series.prices.map(point=>point.date)))].sort();const researchIndex=Math.max(0,Math.floor((dates.length-1)*.5));const validationIndex=Math.max(researchIndex+1,Math.floor((dates.length-1)*.75));return {research_end:dates[researchIndex]??"—",validation_end:dates[validationIndex]??"—",locked_test_start:dates[Math.min(dates.length-1,validationIndex+1)]??"—"};}
function metrics(periods:PeriodResult[],annualPeriods:number):SegmentMetrics{
  if(!periods.length)return {periods:0,net_return_pct:null,annualized_return_pct:null,max_drawdown_pct:null,volatility_pct:null,sharpe:null,turnover_pct:null,positive_period_ratio:null,stability_pct:null,concentration_pct:null,cost_impact_pct:null};
  let equity=1,peak=1,maxDd=0;const net=periods.map(p=>p.net_return),gross=periods.map(p=>p.gross_return);for(const r of net){equity*=1+r;peak=Math.max(peak,equity);maxDd=Math.min(maxDd,equity/peak-1);}const vol=sd(net)??0;const annual=Math.pow(equity,annualPeriods/periods.length)-1;const positive=net.filter(x=>x>0).length/net.length;const chunks=Array.from({length:Math.min(4,periods.length)},(_,index)=>net.slice(Math.floor(index*net.length/Math.min(4,periods.length)),Math.floor((index+1)*net.length/Math.min(4,periods.length))));const stable=chunks.filter(chunk=>chunk.reduce((value,item)=>value*(1+item),1)>1).length/chunks.length;const absolute=net.map(Math.abs);const total=absolute.reduce((a,b)=>a+b,0);const concentration=total?absolute.sort((a,b)=>b-a).slice(0,Math.max(1,Math.ceil(net.length*.2))).reduce((a,b)=>a+b,0)/total:0;
  return {periods:periods.length,net_return_pct:+((equity-1)*100).toFixed(2),annualized_return_pct:+(annual*100).toFixed(2),max_drawdown_pct:+(maxDd*100).toFixed(2),volatility_pct:+(vol*Math.sqrt(annualPeriods)*100).toFixed(2),sharpe:vol?+(mean(net)!/vol*Math.sqrt(annualPeriods)).toFixed(2):null,turnover_pct:+(mean(periods.map(p=>p.turnover))!*100).toFixed(1),positive_period_ratio:+positive.toFixed(3),stability_pct:+(stable*100).toFixed(1),concentration_pct:+(concentration*100).toFixed(1),cost_impact_pct:+((mean(gross)!-mean(net)!)*periods.length*100).toFixed(2)};
}

export function evaluateStrategy(strategy:StrategyDSL,input:PriceSeries[],runLocked=true,split:ResearchSplit=deriveResearchSplit(input)):StrategyEvaluation{
  const annualPeriods=strategy.rebalance.frequency==="biweekly"?25.2:12.6;const checked=validateStrategyDSL(strategy);const empty=metrics([],annualPeriods);if(!checked.valid)return {strategy,status:"precheck_rejected",reason:checked.errors.join("；"),research:empty,validation:empty,locked_test:null,all_periods:[],equity_curve:[],drawdown_curve:[],sensitivity_passed:false,lookahead_check:"fail"};
  const prepared=prepare(input);const periods:PeriodResult[]=[];let previous=new Set<string>();
  let lookaheadSafe=true;for(const preparedPeriod of prepared[strategy.rebalance.frequency]){const {signal,date,end}=preparedPeriod;lookaheadSafe&&=signal<date&&date<end;const candidates=preparedPeriod.rows.filter(row=>!(strategy.filters.some(f=>f.enabled&&f.id==="trend_positive")&&row.trend<=0));
    if(candidates.length<10)continue;const scores=Array(candidates.length).fill(0);for(const factor of strategy.factors){const rs=ranks(candidates.map(candidate=>({raw:candidate.raw[factor.id]})));rs.forEach((rank,i)=>scores[i]+=(factor.direction==="lower"?1-rank:rank)*factor.weight);}
    let pool=candidates.map((c,i)=>({...c,score:strategy.factors.length?scores[i]:1}));if(strategy.filters.some(f=>f.enabled&&f.id==="exclude_high_volatility")){const limit=[...pool].sort((a,b)=>a.vol-b.vol)[Math.floor(pool.length*.75)]?.vol;pool=pool.filter(c=>c.vol<=limit);}
    pool.sort((a,b)=>b.score-a.score);const minimumForCap=Math.ceil(100/strategy.portfolio.max_single_weight_pct);const count=strategy.factors.length?Math.min(strategy.portfolio.max_positions,Math.max(3,minimumForCap,Math.floor(pool.length*strategy.portfolio.quantile))):pool.length;const selected=pool.slice(0,count);if(selected.length<3||100/selected.length>strategy.portfolio.max_single_weight_pct+.001)continue;const current=new Set(selected.map(s=>s.symbol));const retained=[...current].filter(s=>previous.has(s)).length;const turnover=previous.size?1-retained/Math.max(previous.size,current.size):1;previous=current;const gross=mean(selected.map(s=>s.forward))??0;const universe=mean(candidates.map(s=>s.forward))??0;const cost=turnover*(strategy.costs.commission_bps+strategy.costs.stamp_tax_bps+strategy.costs.slippage_bps)/10000;periods.push({date,end_date:end,gross_return:gross,net_return:gross-cost,universe_return:universe,turnover,valid_symbols:candidates.length});}
  const researchPeriods=periods.filter(period=>period.date<=split.research_end&&period.end_date<=split.research_end),validationPeriods=periods.filter(period=>period.date>split.research_end&&period.date<split.locked_test_start&&period.end_date<=split.validation_end),lockedPeriods=periods.filter(period=>period.date>=split.locked_test_start&&period.end_date>split.locked_test_start);const research=metrics(researchPeriods,annualPeriods),validation=metrics(validationPeriods,annualPeriods),locked=runLocked?metrics(lockedPeriods,annualPeriods):null;
  const prelockedPeriods=researchPeriods.length+validationPeriods.length;const minimumPeriods=strategy.rebalance.frequency==="monthly"?24:48;
  let status:StrategyEvaluation["status"]="limited_candidate",reason="通过预检、验证与锁定历史测试，但结论仅限本次历史样本。";if(prelockedPeriods<minimumPeriods){status="research_rejected";reason=`研究区与验证区的完整非重叠观察期不足 ${minimumPeriods} 个。`;}else if((validation.net_return_pct??-1)<=0||(validation.positive_period_ratio??0)<.42){status="validation_rejected";reason="验证区间的成本后结果或阶段稳定性未达到最低门槛。";}else if(runLocked&&((locked?.net_return_pct??-1)<=0||(locked?.positive_period_ratio??0)<.4)){status="locked_failed";reason="候选在锁定历史测试中未延续。";}
  const visiblePeriods=runLocked?[...researchPeriods,...validationPeriods,...lockedPeriods]:[...researchPeriods,...validationPeriods];
  let equity=1,peak=1;const equity_curve=visiblePeriods.map(p=>{equity*=1+p.net_return;const segment=p.date<=split.research_end?"research" as const:p.date<=split.validation_end?"validation" as const:"locked_test" as const;return {date:p.end_date,value:+equity.toFixed(4),segment}});const drawdown_curve=equity_curve.map(p=>{peak=Math.max(peak,p.value);return {date:p.date,value:+((p.value/peak-1)*100).toFixed(2)}});
  return {strategy,status,reason,research,validation,locked_test:locked,all_periods:visiblePeriods,equity_curve,drawdown_curve,sensitivity_passed:false,lookahead_check:lookaheadSafe?"pass":"fail"};
}

export function evaluateSensitivity(strategy:StrategyDSL,input:PriceSeries[],split:ResearchSplit){
  const quantiles=([.2,.25,.33] as const).filter(value=>value!==strategy.portfolio.quantile).sort((a,b)=>Math.abs(a-strategy.portfolio.quantile)-Math.abs(b-strategy.portfolio.quantile));
  const variants:StrategyDSL[]=[{...structuredClone(strategy),portfolio:{...strategy.portfolio,quantile:quantiles[0]??strategy.portfolio.quantile}}];
  if(strategy.factors.length>1){const factors=strategy.factors.map((factor,index)=>({...factor,weight:Math.max(.05,factor.weight+(index===0 ? .1 : -.1/(strategy.factors.length-1)))}));const total=factors.reduce((sum,item)=>sum+item.weight,0);variants.push({...structuredClone(strategy),factors:factors.map(item=>({...item,weight:item.weight/total}))});}
  const base=evaluateStrategy(strategy,input,false,split).validation;return variants.every(variant=>{const result=evaluateStrategy(variant,input,false,split).validation;return (base.net_return_pct??-999)>0&&(result.net_return_pct??-999)>0&&Math.abs((result.net_return_pct??0)-(base.net_return_pct??0))<=15&&Math.abs((result.max_drawdown_pct??0)-(base.max_drawdown_pct??0))<=10;});
}
