[theme]
base = "light"
primaryColor = "#2d8cff"
backgroundColor = "#f4f8fd"
secondaryBackgroundColor = "#eaf2fb"
textColor = "#14283d"
font = "sans serif"

[server]
headless = true
runOnSave = true
enableStaticServing = true

[browser]
gatherUsageStats = false
